// GENERATED by scripts/fetch-college-tournaments.mjs -- do not edit.
// College tournaments (ITA/NCAA events + invitationals involving covered
// schools) from the ITA GraphQL td_tournaments feed, next-90-day window
// as of 2026-09-24. Empty until events are
// entered on the platform (they appear days-to-weeks before play). No UI
// consumer yet -- the hand calendar in collegeEvents.js stays the marquee
// layer; this module is the watcher's ledger and the future live source.
export const collegeTournaments = globalThis.__BAGEL_REMOTE__?.["collegeTournaments"]?.collegeTournaments ?? [
  {
    "id": "6ab0280ce3ae706de9772798",
    "name": "2026 ITA DIII Women's Southwest Regional Championships",
    "start": "2026-09-24",
    "end": "2026-09-27"
  },
  {
    "id": "6ab19316e3ae706de9d18eb0",
    "name": "2026 ITA NAIA Men's and Women's South Regional Championship",
    "start": "2026-09-24",
    "end": "2026-09-27"
  },
  {
    "id": "6ab2e318e3ae706de9f36bb8",
    "name": "2026 ITA NAIA Men's and Women's Florida Regional Championship",
    "start": "2026-09-24",
    "end": "2026-09-28"
  },
  {
    "id": "6ab360c8e3ae706de998a846",
    "name": "2026 ITA NAIA Men's & Women's Southeast Regional Championship",
    "start": "2026-09-24",
    "end": "2026-09-28"
  },
  {
    "id": "6ab3e952e3ae706de927e5cc",
    "name": "2026 ITA JUCO Women's Florida Regional Championship",
    "start": "2026-09-24",
    "end": "2026-09-25"
  },
  {
    "id": "6ab035fde3ae706de98cdf10",
    "name": "Florida Bedford Cup",
    "start": "2026-09-25",
    "end": "2026-09-27"
  },
  {
    "id": "6ab190a6e3ae706de9cf9513",
    "name": "2026 ITA JUCO Women's Southeast Regional Championships",
    "start": "2026-09-25",
    "end": "2026-09-27"
  },
  {
    "id": "6ab2cf6ce3ae706de9d72122",
    "name": "2026 ITA DIII Women's Central Regional Championship",
    "start": "2026-09-25",
    "end": "2026-09-27"
  },
  {
    "id": "6ab2e19ee3ae706de9f1d147",
    "name": "2026 ITA NAIA Men's and Women's Central West Regional Championship",
    "start": "2026-09-25",
    "end": "2026-09-27"
  },
  {
    "id": "6ab3f30ee3ae706de93b2628",
    "name": "2026 ITA DIII Women's South Regional Championship",
    "start": "2026-09-25",
    "end": "2026-09-27"
  },
  {
    "id": "6ab3f5aee3ae706de940f182",
    "name": "2026 ITA DIII Men's Northeast Regional Championship",
    "start": "2026-09-25",
    "end": "2026-09-28"
  },
  {
    "id": "6ab3f7b1e3ae706de9470ecc",
    "name": "2026 ITA DIII Women's Southeast Regional Championship",
    "start": "2026-09-25",
    "end": "2026-09-28"
  },
  {
    "id": "6ab40520e3ae706de969c0a8",
    "name": "2026 ITA DIII Men's Northwest Regional Championships",
    "start": "2026-09-26",
    "end": "2026-09-28"
  }
];
