// GENERATED by scripts/fetch-college-tournaments.mjs -- do not edit.
// College tournaments (ITA/NCAA events + invitationals involving covered
// schools) from the ITA GraphQL td_tournaments feed, next-90-day window
// as of 2026-10-01. Empty until events are
// entered on the platform (they appear days-to-weeks before play). No UI
// consumer yet -- the hand calendar in collegeEvents.js stays the marquee
// layer; this module is the watcher's ledger and the future live source.
export const collegeTournaments = globalThis.__BAGEL_REMOTE__?.["collegeTournaments"]?.collegeTournaments ?? [
  {
    "id": "6ababface3ae706de97add09",
    "name": "2026 ITA JUCO Women's Southwest Regional Championships",
    "start": "2026-10-01",
    "end": "2026-10-03"
  },
  {
    "id": "6abad3bfe3ae706de98d8047",
    "name": "2026 ITA JUCO Men's Southwest Regional Championships",
    "start": "2026-10-01",
    "end": "2026-10-03"
  },
  {
    "id": "6abadc06e3ae706de993555a",
    "name": "2026 ITA Dlll Men's Southwest Regional Championships",
    "start": "2026-10-01",
    "end": "2026-10-04"
  },
  {
    "id": "6abb3580e3ae706de9cbee00",
    "name": "2026 ITA DIII Women's Northeast Regional Championship",
    "start": "2026-10-01",
    "end": "2026-10-04"
  },
  {
    "id": "6abc700033a5117ef000542a",
    "name": "2026 ITA NAIA Men's and Women's West Regional Championship",
    "start": "2026-10-01",
    "end": "2026-10-03"
  },
  {
    "id": "6ab85a59e3ae706de9c63f84",
    "name": "2026 ITA DIII Men's Midwest Regional Championships",
    "start": "2026-10-02",
    "end": "2026-10-04"
  },
  {
    "id": "6abca7d833a5117ef059f263",
    "name": "2026 ITA DIII Men's & Women's West Regional Championships",
    "start": "2026-10-02",
    "end": "2026-10-04"
  },
  {
    "id": "6abd222d33a5117ef0d2f070",
    "name": "Bedford Cup - HOST UCF",
    "start": "2026-10-02",
    "end": "2026-10-04"
  },
  {
    "id": "6abd3ca133a5117ef00406c5",
    "name": "2026 ITA DIII Men's Central Regional Championship",
    "start": "2026-10-02",
    "end": "2026-10-04"
  },
  {
    "id": "6abe7a4133a5117ef03f8558",
    "name": "2026 ITA DIII Men's South Regional Championship",
    "start": "2026-10-02",
    "end": "2026-10-04"
  },
  {
    "id": "6abece7233a5117ef09304a2",
    "name": "2026 ITA DI Men's Mountain Regional Championship",
    "start": "2026-10-06",
    "end": "2026-10-10"
  }
];
