// GENERATED by scripts/build-draw-fixtures.mjs -- do not edit.
// Draw presence for our players in this week's events (main + quali),
// from the per-tournament draws endpoint. "Entered" precedes "played":
// quali draws land ~Saturday, main draws ~Sun/Mon. asOf 2026-09-01.
export const drawFixtures = globalThis.__BAGEL_REMOTE__?.["drawFixtures"]?.drawFixtures ?? [
 {
  "playerId": "ucla-w-p3",
  "event": "W15 Torello",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "prin-w-p4",
  "event": "W15 Torello",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "lsu-p8",
  "event": "W35 Barueri",
  "seed": "3",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "corn-w-h13",
  "event": "W35 Barueri",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tenn-w-h9",
  "event": "W35 Barueri",
  "seed": "8",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "aub-w-h6",
  "event": "W35 Barueri",
  "seed": "2",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "lmu-w-p4",
  "event": "W35 Barueri",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ore-w-h7",
  "event": "W35 Barueri",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ore-w-p2",
  "event": "W35 Barueri",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "aub-p12",
  "event": "W35 Verbier",
  "seed": "6",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tcu-w-h2",
  "event": "W35 Verbier",
  "seed": "5",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "wash-w-p3",
  "event": "W35 Verbier",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "wsu-w-h7",
  "event": "W35 Verbier",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "okst-w-p1",
  "event": "W15 Brasov",
  "seed": "3",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ncst-w-h11",
  "event": "W15 Tianjin",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "utah-w-h2",
  "event": "W15 Tianjin",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "bay-w-h13",
  "event": "W50 Oldenzaal",
  "seed": "4",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ala-w-h1",
  "event": "W50 Oldenzaal",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "usc-w-h12",
  "event": "W50 Oldenzaal",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uga-w-h7",
  "event": "Abierto GNP Seguros - Monterrey",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "pepp-w-h4",
  "event": "Abierto GNP Seguros - Monterrey",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "fla-w-n3",
  "event": "Philly Open - Philadelphia",
  "seed": null,
  "entry": "LL",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "okst-w-h10",
  "event": "Philly Open - Philadelphia",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "okst-w-h7",
  "event": "Philly Open - Philadelphia",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "unc-w-h2",
  "event": "Philly Open - Philadelphia",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ucla-w-h6",
  "event": "Philly Open - Philadelphia",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uga-w-h6",
  "event": "Philly Open - Philadelphia",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tamu-p5",
  "event": "Philly Open - Philadelphia",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "aub-w-h7",
  "event": "Philly Open - Philadelphia",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "unc-w-p4",
  "event": "Philly Open - Philadelphia",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tenn-w-h4",
  "event": "W75 Bytom",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ou-w-h13",
  "event": "W75 Bytom",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ala-w-h8",
  "event": "W75 Bytom",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "uva-w-h6",
  "event": "W75 Bytom",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "ncst-w-h5",
  "event": "W75 Bytom",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "miss-w-h1",
  "event": "W75 Bytom",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "ala-p10",
  "event": "W35 Trieste",
  "seed": "SE",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "rice-w-h2",
  "event": "W35 Trieste",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ucf-w-h5",
  "event": "W35 Trieste",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tenn-w-h7",
  "event": "W35 Trieste",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "msu-w-h16",
  "event": "W50 Kursumlijska Banja",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "pepp-w-h5",
  "event": "W75 Kursumlijska Banja",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tamu-m-h9",
  "event": "M15 Trelew",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "uga-m-p3",
  "event": "M15 Trelew",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "usf-m-p3",
  "event": "M15 Trelew",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "bay-m-h11",
  "event": "Como Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ttu-m-h1",
  "event": "Como Challenger",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tex-m-n3",
  "event": "Como Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "unc-m-h2",
  "event": "M15 Buzau",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "unc-m-p1",
  "event": "M15 Buzau",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ore-m-p1",
  "event": "M15 Buzau",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "fla-m-h11",
  "event": "Kingston 2 Challenger",
  "seed": "2",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "gt-m-h8",
  "event": "Kingston 2 Challenger",
  "seed": "6",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "mich-m-h5",
  "event": "Kingston 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "gt-m-h3",
  "event": "Kingston 2 Challenger",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ucla-m-h8",
  "event": "Kingston 2 Challenger",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "duke-m-h2",
  "event": "Kingston 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "unc-m-h8",
  "event": "Kingston 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "okst-m-h4",
  "event": "Kingston 2 Challenger",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "wich-m-fp92",
  "event": "Kingston 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "osu-m-p5",
  "event": "Kingston 2 Challenger",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tenn-m-h10",
  "event": "Kingston 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "pepp-m-p6",
  "event": "Kingston 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "sc-m-p1",
  "event": "Kingston 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "fla-m-p1",
  "event": "Kingston 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "clem-m-p9",
  "event": "Kingston 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "tulsa-m-h3",
  "event": "Kingston 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "usc-m-p3",
  "event": "M15 Kursumlijska Banja",
  "seed": "1",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "msu-m-h10",
  "event": "M15 Kursumlijska Banja",
  "seed": "8",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "miss-m-p2",
  "event": "M15 Kursumlijska Banja",
  "seed": "3",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "osu-m-p7",
  "event": "M15 Champaign",
  "seed": "5",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ark-m-p6",
  "event": "M15 Champaign",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "asu-m-p2",
  "event": "M15 Champaign",
  "seed": "8",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uga-m-h1",
  "event": "M15 Champaign",
  "seed": "1",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "asu-m-p10",
  "event": "M15 Champaign",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tamu-m-n1",
  "event": "M15 Champaign",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uk-m-p7",
  "event": "M15 Champaign",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "osu-m-p11",
  "event": "M15 Champaign",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "osu-m-fp278",
  "event": "M15 Champaign",
  "seed": "3",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "clem-m-p6",
  "event": "M15 Champaign",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ill-m-p8",
  "event": "M15 Champaign",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "aub-m-n1",
  "event": "M15 Champaign",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ill-m-p1",
  "event": "M15 Champaign",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uk-m-p2",
  "event": "M15 Champaign",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uk-m-p1",
  "event": "M15 Champaign",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ill-m-p6",
  "event": "M15 Champaign",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ill-m-p7",
  "event": "M15 Champaign",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "asu-m-p4",
  "event": "M15 Champaign",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tamu-m-h9",
  "event": "M15 Champaign",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "asu-m-fp38",
  "event": "M15 Champaign",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "clem-m-p7",
  "event": "M15 Champaign",
  "seed": "2",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uci-m-p9",
  "event": "M15 Champaign",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "prin-m-p5",
  "event": "M15 Champaign",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "tenn-m-p8",
  "event": "M15 Champaign",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "stan-m-h4",
  "event": "Winston-Salem Open - Winston-Salem",
  "seed": "4",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "fla-m-h9",
  "event": "Winston-Salem Open - Winston-Salem",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "wake-m-p5",
  "event": "Winston-Salem Open - Winston-Salem",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ore-m-h7",
  "event": "Winston-Salem Open - Winston-Salem",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "wake-m-fp302",
  "event": "Winston-Salem Open - Winston-Salem",
  "seed": null,
  "entry": "LL",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tex-m-p8",
  "event": "Winston-Salem Open - Winston-Salem",
  "seed": null,
  "entry": "LL",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tenn-m-h15",
  "event": "Winston-Salem Open - Winston-Salem",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ucla-m-h13",
  "event": "Winston-Salem Open - Winston-Salem",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "unc-m-h9",
  "event": "Winston-Salem Open - Winston-Salem",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "tcu-m-p6",
  "event": "Winston-Salem Open - Winston-Salem",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "wake-m-p4",
  "event": "Winston-Salem Open - Winston-Salem",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "ill-m-h3",
  "event": "Winston-Salem Open - Winston-Salem",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "ill-m-fp217",
  "event": "Winston-Salem Open - Winston-Salem",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "neb-m-h6",
  "event": "M15 Allershausen",
  "seed": "6",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ou-m-h5",
  "event": "M15 Allershausen",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "okst-m-h6",
  "event": "M15 Maanshan",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ore-m-h2",
  "event": "M15 Maanshan",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tulsa-m-p5",
  "event": "M15 Maanshan",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "cal-m-h7",
  "event": "M15 Maanshan",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "temple-m-n1",
  "event": "M15 Maanshan",
  "seed": "6",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ttu-m-h2",
  "event": "M25 Poznan",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tamu-m-h16",
  "event": "M25 Poznan",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ala-m-h4",
  "event": "M25 Maribor",
  "seed": "6",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "pur-m-p2",
  "event": "M25 Maribor",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "miss-m-h3",
  "event": "M15 Pecs",
  "seed": "4",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "harv-m-p5",
  "event": "M15 Pecs",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ariz-m-h1",
  "event": "M15 Pecs",
  "seed": "3",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "clem-m-fp162",
  "event": "M15 Vienna",
  "seed": "6",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "msst-m-p8",
  "event": "Augsburg Challenger",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "bay-m-h11",
  "event": "Augsburg Challenger",
  "seed": "3",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tamu-m-h7",
  "event": "Augsburg Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "mich-m-h4",
  "event": "M25 Lausanne",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uva-m-h6",
  "event": "M25 Lausanne",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "usd-m-p8",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "stan-m-h6",
  "event": "Roehampton 2 Challenger",
  "seed": "1",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tenn-m-h5",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ucla-m-h5",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uva-m-h4",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tenn-m-h7",
  "event": "Roehampton 2 Challenger",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ariz-m-fp226",
  "event": "Roehampton 2 Challenger",
  "seed": "8",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tcu-m-h5",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "aub-m-p1",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "bay-m-h12",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "neb-m-h9",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "usc-m-h3",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "tamu-m-h6",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "duke-m-h1",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "uk-m-h10",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "uk-m-h14",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "mem-m-h2",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "usc-m-h10",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "uga-m-h16",
  "event": "M25 Oviedo",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "duke-m-fp157",
  "event": "M25 Oviedo",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "msst-m-h4",
  "event": "M25 Oviedo",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "asu-m-p9",
  "event": "M25 Oviedo",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "cal-m-p9",
  "event": "M25 Oviedo",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "usd-m-p4",
  "event": "M25 Oldenzaal",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "pepp-m-h6",
  "event": "M25 Oldenzaal",
  "seed": "3",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "usd-m-h3",
  "event": "M25 Oldenzaal",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uga-m-p3",
  "event": "M15 Mar Del Plata",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "fsu-m-fp26",
  "event": "M15 Mar Del Plata",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "ore-m-p1",
  "event": "M15 Bucharest",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "unc-m-h2",
  "event": "M15 Bucharest",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "unc-m-p1",
  "event": "M15 Bucharest",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tcu-m-h11",
  "event": "Cincinnati Open - Cincinnati",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uva-m-h12",
  "event": "Cincinnati Open - Cincinnati",
  "seed": "12",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uva-m-h16",
  "event": "Cincinnati Open - Cincinnati",
  "seed": "27",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tamu-m-h19",
  "event": "Cincinnati Open - Cincinnati",
  "seed": "15",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "stan-m-h4",
  "event": "Cincinnati Open - Cincinnati",
  "seed": "32",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tenn-m-h15",
  "event": "Cincinnati Open - Cincinnati",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "usc-m-h13",
  "event": "Cincinnati Open - Cincinnati",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "usc-m-h8",
  "event": "Cincinnati Open - Cincinnati",
  "seed": "16",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "fla-m-h8",
  "event": "Cincinnati Open - Cincinnati",
  "seed": "8",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "osu-m-h11",
  "event": "Cincinnati Open - Cincinnati",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tamu-m-h20",
  "event": "Cincinnati Open - Cincinnati",
  "seed": "25",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ucla-m-h14",
  "event": "Cincinnati Open - Cincinnati",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "ucla-m-h13",
  "event": "Cincinnati Open - Cincinnati",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "tcu-m-h1",
  "event": "Cincinnati Open - Cincinnati",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "stan-m-h6",
  "event": "Manacor Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tcu-m-h8",
  "event": "Manacor Challenger",
  "seed": "6",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "uva-m-h4",
  "event": "Manacor Challenger",
  "seed": null,
  "entry": "ALT",
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ariz-m-fp226",
  "event": "Manacor Challenger",
  "seed": "CO",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "usd-m-h8",
  "event": "Manacor Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "bay-m-h12",
  "event": "Manacor Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "tcu-m-h5",
  "event": "Manacor Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "neb-m-h9",
  "event": "Manacor Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "cal-m-h6",
  "event": "Manacor Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "lou-m-h5",
  "event": "M25+H Bagneres-de-Bigorre",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "tcu-m-h2",
  "event": "M25+H Bagneres-de-Bigorre",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "scu-m-h2",
  "event": "M25+H Bagneres-de-Bigorre",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ark-m-h14",
  "event": "M25+H Bagneres-de-Bigorre",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "fla-m-p4",
  "event": "M25+H Bagneres-de-Bigorre",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "tamu-m-h7",
  "event": "M25+H Bagneres-de-Bigorre",
  "seed": "2WC",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "asu-w-h8",
  "event": "W50 Leiria",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "cal-w-h2",
  "event": "W50 Leiria",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "aub-w-h7",
  "event": "W50 Leiria",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "tex-w-h5",
  "event": "W50 Leiria",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "uga-w-h6",
  "event": "W50 Leiria",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "neb-w-h7",
  "event": "W50 Leiria",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ncst-w-h3",
  "event": "W50 Leiria",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "msu-w-h16",
  "event": "W50 Leiria",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "osu-w-h3",
  "event": "W50 Leiria",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "rice-w-h2",
  "event": "W15 Fiano Romano",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "okst-w-h2",
  "event": "W15 Fiano Romano",
  "seed": "6",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "lmu-w-h8",
  "event": "W15 Fiano Romano",
  "seed": "2",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "tenn-w-h7",
  "event": "W15 Fiano Romano",
  "seed": "4",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ala-m-h4",
  "event": "Plovdiv 3 Challenger",
  "seed": null,
  "entry": "ALT",
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ttu-m-h2",
  "event": "Plovdiv 3 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "tamu-m-p6",
  "event": "Plovdiv 3 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "tenn-w-h9",
  "event": "W15 Lujan",
  "seed": "4",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ou-w-h9",
  "event": "W15 Lujan",
  "seed": "3",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ou-m-h5",
  "event": "M25 Meerbusch",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "usd-m-h3",
  "event": "M25 Meerbusch",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "mich-m-h4",
  "event": "M25 Meerbusch",
  "seed": "5",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "pepp-m-h6",
  "event": "M25 Meerbusch",
  "seed": "2",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "aub-w-h1",
  "event": "W15 Grodzisk Mazowiecki",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "uga-w-h2",
  "event": "W15 Grodzisk Mazowiecki",
  "seed": "6",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "uva-w-h6",
  "event": "W15 Grodzisk Mazowiecki",
  "seed": "2",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "usc-w-h12",
  "event": "W50 Saint-Palais-sur-Mer",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ucf-w-h5",
  "event": "W50 Saint-Palais-sur-Mer",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": true
 },
 {
  "playerId": "ala-w-h1",
  "event": "W50 Saint-Palais-sur-Mer",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "tenn-m-h6",
  "event": "M25 Urayasu",
  "seed": "4",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "okst-m-h6",
  "event": "M25 Urayasu",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "tex-w-h11",
  "event": "W15 Cap d'Agde",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "wsu-w-h7",
  "event": "W15 Cap d'Agde",
  "seed": "4",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ncst-w-h11",
  "event": "W75 Tianjin",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ucla-w-h6",
  "event": "W75 Tianjin",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "wash-w-h7",
  "event": "W75 Tianjin",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 }
];
