// GENERATED by scripts/build-draw-fixtures.mjs -- do not edit.
// Per-event draw state for this week: finished flag (the singleton
// final round has a result), our champion when one of ours won it, and
// per-player entry status (seed, main/quali, eliminated). Draws appear
// when made: quali ~Saturday, main ~Sun/Mon. asOf 2026-09-01.
export const drawEvents = globalThis.__BAGEL_REMOTE__?.["drawFixtures"]?.drawEvents ?? [
 {
  "event": "W15 Fiano Romano",
  "tournamentId": 17243,
  "tour": "wta",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "rice-w-h2",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": false
   },
   {
    "playerId": "okst-w-h2",
    "seed": "6",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": false
   },
   {
    "playerId": "lmu-w-h8",
    "seed": "2",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "tenn-w-h7",
    "seed": "4",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "W50 Leiria",
  "tournamentId": 17236,
  "tour": "wta",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "asu-w-h8",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "uga-w-h6",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "cal-w-h2",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "aub-w-h7",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": false
   },
   {
    "playerId": "tex-w-h5",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": false
   },
   {
    "playerId": "neb-w-h7",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "ncst-w-h3",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "msu-w-h16",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "osu-w-h3",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "W75 Tianjin",
  "tournamentId": 17234,
  "tour": "wta",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "ncst-w-h11",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "ucla-w-h6",
    "seed": "7",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": false
   },
   {
    "playerId": "wash-w-h7",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "W50 Saint-Palais-sur-Mer",
  "tournamentId": 17235,
  "tour": "wta",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "usc-w-h12",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": false
   },
   {
    "playerId": "ucf-w-h5",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "ala-w-h1",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": false,
    "played": true
   }
  ]
 },
 {
  "event": "W15 Cap d'Agde",
  "tournamentId": 17247,
  "tour": "wta",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "tex-w-h11",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "wsu-w-h7",
    "seed": "4",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": false
   }
  ]
 },
 {
  "event": "W35 Verbier",
  "tournamentId": 17226,
  "tour": "wta",
  "finished": true,
  "finalDate": "2026-08-30",
  "champion": null,
  "entries": [
   {
    "playerId": "aub-p12",
    "seed": "6",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tcu-w-h2",
    "seed": "5",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "wash-w-p3",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "wsu-w-h7",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "W15 Torello",
  "tournamentId": 17229,
  "tour": "wta",
  "finished": true,
  "finalDate": "2026-08-30",
  "champion": {
   "playerId": "ucla-w-p3",
   "score": "4-6 6-0 6-4",
   "date": "2026-08-30"
  },
  "entries": [
   {
    "playerId": "ucla-w-p3",
    "seed": "7",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "prin-w-p4",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "W35 Barueri",
  "tournamentId": 17228,
  "tour": "wta",
  "finished": true,
  "finalDate": "2026-08-30",
  "champion": {
   "playerId": "lsu-p8",
   "score": "1-6 7-5 6-3",
   "date": "2026-08-30"
  },
  "entries": [
   {
    "playerId": "lsu-p8",
    "seed": "3",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "corn-w-h13",
    "seed": "7",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tenn-w-h9",
    "seed": "8",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "aub-w-h6",
    "seed": "2",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "lmu-w-p4",
    "seed": null,
    "entry": "WC",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ore-w-h7",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ore-w-p2",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "W15 Brasov",
  "tournamentId": 17238,
  "tour": "wta",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "okst-w-p1",
    "seed": "3",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": false
   }
  ]
 },
 {
  "event": "W50 Oldenzaal",
  "tournamentId": 17225,
  "tour": "wta",
  "finished": true,
  "finalDate": "2026-08-30",
  "champion": null,
  "entries": [
   {
    "playerId": "bay-w-h13",
    "seed": "4",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ala-w-h1",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "usc-w-h12",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "Abierto GNP Seguros - Monterrey",
  "tournamentId": 16741,
  "tour": "wta",
  "finished": true,
  "finalDate": "2026-08-30",
  "champion": null,
  "entries": [
   {
    "playerId": "uga-w-h7",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "pepp-w-h4",
    "seed": "7",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "Philly Open - Philadelphia",
  "tournamentId": 17191,
  "tour": "wta",
  "finished": true,
  "finalDate": "2026-08-29",
  "champion": null,
  "entries": [
   {
    "playerId": "fla-w-n3",
    "seed": null,
    "entry": "LL",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "okst-w-h10",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "okst-w-h7",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "unc-w-h2",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ucla-w-h6",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "uga-w-h6",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tamu-p5",
    "seed": null,
    "entry": "WC",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "aub-w-h7",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "unc-w-p4",
    "seed": null,
    "entry": "WC",
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "W75 Bytom",
  "tournamentId": 17223,
  "tour": "wta",
  "finished": true,
  "finalDate": "2026-08-30",
  "champion": null,
  "entries": [
   {
    "playerId": "tenn-w-h4",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ou-w-h13",
    "seed": null,
    "entry": "WC",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ala-w-h8",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "uva-w-h6",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ncst-w-h5",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "miss-w-h1",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "W35 Trieste",
  "tournamentId": 17227,
  "tour": "wta",
  "finished": true,
  "finalDate": "2026-08-29",
  "champion": null,
  "entries": [
   {
    "playerId": "ala-p10",
    "seed": null,
    "entry": "SE",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "rice-w-h2",
    "seed": null,
    "entry": "WC",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ucf-w-h5",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tenn-w-h7",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "W15 Tianjin",
  "tournamentId": 17230,
  "tour": "wta",
  "finished": true,
  "finalDate": "2026-08-30",
  "champion": null,
  "entries": [
   {
    "playerId": "ncst-w-h11",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "utah-w-h2",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "W75 Kursumlijska Banja",
  "tournamentId": 17213,
  "tour": "wta",
  "finished": true,
  "finalDate": "2026-08-23",
  "champion": null,
  "entries": [
   {
    "playerId": "pepp-w-h5",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "Manacor Challenger",
  "tournamentId": 21942,
  "tour": "atp",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "stan-m-h6",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tcu-m-h8",
    "seed": "6",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "uva-m-h4",
    "seed": null,
    "entry": "ALT",
    "inMain": true,
    "eliminated": false,
    "played": false
   },
   {
    "playerId": "ariz-m-fp226",
    "seed": null,
    "entry": "CO",
    "inMain": true,
    "eliminated": false,
    "played": false
   },
   {
    "playerId": "usd-m-h8",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "bay-m-h12",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tcu-m-h5",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "neb-m-h9",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "cal-m-h6",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "Como Challenger",
  "tournamentId": 21941,
  "tour": "atp",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "bay-m-h11",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ttu-m-h1",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tex-m-n3",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   }
  ]
 },
 {
  "event": "M25 Urayasu",
  "tournamentId": 22005,
  "tour": "atp",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "tenn-m-h6",
    "seed": "4",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "okst-m-h6",
    "seed": "7",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": false
   }
  ]
 },
 {
  "event": "M15 Buzau",
  "tournamentId": 22016,
  "tour": "atp",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "unc-m-h2",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "unc-m-p1",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": false
   },
   {
    "playerId": "ore-m-p1",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M15 Trelew",
  "tournamentId": 22011,
  "tour": "atp",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "tamu-m-h9",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": false
   },
   {
    "playerId": "uga-m-p3",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": false
   },
   {
    "playerId": "usf-m-p3",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "Plovdiv 3 Challenger",
  "tournamentId": 21945,
  "tour": "atp",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "ala-m-h4",
    "seed": null,
    "entry": "ALT",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ttu-m-h2",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tamu-m-p6",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "Zhangjiagang Challenger",
  "tournamentId": 21944,
  "tour": "atp",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "port-m-h5",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "temple-m-n1",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ore-m-h2",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M25+H Bagneres-de-Bigorre",
  "tournamentId": 22002,
  "tour": "atp",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "lou-m-h5",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": false
   },
   {
    "playerId": "tcu-m-h2",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "scu-m-h2",
    "seed": "7",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": false
   },
   {
    "playerId": "ark-m-h14",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": false
   },
   {
    "playerId": "fla-m-p4",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": false
   },
   {
    "playerId": "tamu-m-h7",
    "seed": null,
    "entry": "2WC",
    "inMain": true,
    "eliminated": false,
    "played": false
   }
  ]
 },
 {
  "event": "Kingston 2 Challenger",
  "tournamentId": 21938,
  "tour": "atp",
  "finished": true,
  "finalDate": "2026-08-30",
  "champion": null,
  "entries": [
   {
    "playerId": "fla-m-h11",
    "seed": "2",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "gt-m-h8",
    "seed": "6",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "mich-m-h5",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "gt-m-h3",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ucla-m-h8",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "duke-m-h2",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "unc-m-h8",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "okst-m-h4",
    "seed": "7",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "wich-m-fp92",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "osu-m-p5",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tenn-m-h10",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "pepp-m-p6",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "sc-m-p1",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "fla-m-p1",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "clem-m-p9",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tulsa-m-h3",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M15 Kursumlijska Banja",
  "tournamentId": 22009,
  "tour": "atp",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "usc-m-p3",
    "seed": "1",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": false
   },
   {
    "playerId": "msu-m-h10",
    "seed": "8",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": false
   },
   {
    "playerId": "miss-m-p2",
    "seed": "3",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": false
   }
  ]
 },
 {
  "event": "M15 Champaign",
  "tournamentId": 21997,
  "tour": "atp",
  "finished": true,
  "finalDate": "2026-08-30",
  "champion": {
   "playerId": "osu-m-p7",
   "score": "6-2 7-6(6)",
   "date": "2026-08-30"
  },
  "entries": [
   {
    "playerId": "osu-m-p7",
    "seed": "5",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "ark-m-p6",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "asu-m-p2",
    "seed": "8",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "uga-m-h1",
    "seed": "1",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "asu-m-p10",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tamu-m-n1",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "uk-m-p7",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "osu-m-p11",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "osu-m-fp278",
    "seed": "3",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "clem-m-p6",
    "seed": null,
    "entry": "WC",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ill-m-p8",
    "seed": null,
    "entry": "WC",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "aub-m-n1",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ill-m-p1",
    "seed": null,
    "entry": "WC",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "uk-m-p2",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "uk-m-p1",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ill-m-p6",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ill-m-p7",
    "seed": null,
    "entry": "WC",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "asu-m-p4",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tamu-m-h9",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "asu-m-fp38",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "clem-m-p7",
    "seed": "2",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "uci-m-p9",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "prin-m-p5",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tenn-m-p8",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M15 Allershausen",
  "tournamentId": 22000,
  "tour": "atp",
  "finished": true,
  "finalDate": "2026-08-30",
  "champion": null,
  "entries": [
   {
    "playerId": "neb-m-h6",
    "seed": "6",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ou-m-h5",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M15 Vienna",
  "tournamentId": 22001,
  "tour": "atp",
  "finished": true,
  "finalDate": "2026-08-30",
  "champion": null,
  "entries": [
   {
    "playerId": "clem-m-fp162",
    "seed": "6",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "Winston-Salem Open - Winston-Salem",
  "tournamentId": 21348,
  "tour": "atp",
  "finished": true,
  "finalDate": "2026-08-29",
  "champion": null,
  "entries": [
   {
    "playerId": "stan-m-h4",
    "seed": "4",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "fla-m-h9",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "wake-m-p5",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ore-m-h7",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "wake-m-fp302",
    "seed": null,
    "entry": "LL",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tex-m-p8",
    "seed": null,
    "entry": "LL",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tenn-m-h15",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ucla-m-h13",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "unc-m-h9",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tcu-m-p6",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "wake-m-p4",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ill-m-h3",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ill-m-fp217",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M15 Maanshan",
  "tournamentId": 21994,
  "tour": "atp",
  "finished": true,
  "finalDate": "2026-08-30",
  "champion": null,
  "entries": [
   {
    "playerId": "okst-m-h6",
    "seed": "7",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ore-m-h2",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tulsa-m-p5",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "cal-m-h7",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "temple-m-n1",
    "seed": "6",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M25 Poznan",
  "tournamentId": 21989,
  "tour": "atp",
  "finished": true,
  "finalDate": "2026-08-30",
  "champion": null,
  "entries": [
   {
    "playerId": "ttu-m-h2",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tamu-m-h16",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M25 Maribor",
  "tournamentId": 21988,
  "tour": "atp",
  "finished": true,
  "finalDate": "2026-08-30",
  "champion": null,
  "entries": [
   {
    "playerId": "ala-m-h4",
    "seed": "6",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "pur-m-p2",
    "seed": null,
    "entry": "WC",
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M15 Pecs",
  "tournamentId": 21998,
  "tour": "atp",
  "finished": true,
  "finalDate": "2026-08-30",
  "champion": null,
  "entries": [
   {
    "playerId": "miss-m-h3",
    "seed": "4",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "harv-m-p5",
    "seed": null,
    "entry": "WC",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ariz-m-h1",
    "seed": "3",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "Augsburg Challenger",
  "tournamentId": 21939,
  "tour": "atp",
  "finished": true,
  "finalDate": "2026-08-29",
  "champion": null,
  "entries": [
   {
    "playerId": "msst-m-p8",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "bay-m-h11",
    "seed": "3",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tamu-m-h7",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M25 Lausanne",
  "tournamentId": 21985,
  "tour": "atp",
  "finished": true,
  "finalDate": "2026-08-30",
  "champion": null,
  "entries": [
   {
    "playerId": "mich-m-h4",
    "seed": "7",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "uva-m-h6",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "Roehampton 2 Challenger",
  "tournamentId": 21940,
  "tour": "atp",
  "finished": true,
  "finalDate": "2026-08-29",
  "champion": null,
  "entries": [
   {
    "playerId": "usd-m-p8",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "stan-m-h6",
    "seed": "1",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tenn-m-h5",
    "seed": null,
    "entry": "WC",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ucla-m-h5",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "uva-m-h4",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tenn-m-h7",
    "seed": "7",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ariz-m-fp226",
    "seed": "8",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tcu-m-h5",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "aub-m-p1",
    "seed": null,
    "entry": "WC",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "bay-m-h12",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "neb-m-h9",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "usc-m-h3",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tamu-m-h6",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "duke-m-h1",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "uk-m-h10",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "uk-m-h14",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "mem-m-h2",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "usc-m-h10",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M25 Oviedo",
  "tournamentId": 21990,
  "tour": "atp",
  "finished": true,
  "finalDate": "2026-08-29",
  "champion": null,
  "entries": [
   {
    "playerId": "uga-m-h16",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "duke-m-fp157",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "msst-m-h4",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "asu-m-p9",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "cal-m-p9",
    "seed": null,
    "entry": "WC",
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M25 Oldenzaal",
  "tournamentId": 21986,
  "tour": "atp",
  "finished": true,
  "finalDate": "2026-08-30",
  "champion": null,
  "entries": [
   {
    "playerId": "usd-m-p4",
    "seed": null,
    "entry": "WC",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "pepp-m-h6",
    "seed": "3",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "usd-m-h3",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M15 Mar Del Plata",
  "tournamentId": 21992,
  "tour": "atp",
  "finished": true,
  "finalDate": "2026-08-30",
  "champion": null,
  "entries": [
   {
    "playerId": "uga-m-p3",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "fsu-m-fp26",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "W15 Lujan",
  "tournamentId": 17248,
  "tour": "wta",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "tenn-w-h9",
    "seed": "4",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": false
   },
   {
    "playerId": "ou-w-h9",
    "seed": "3",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": false
   }
  ]
 },
 {
  "event": "M25 Meerbusch",
  "tournamentId": 22004,
  "tour": "atp",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "ou-m-h5",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "usd-m-h3",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": false
   },
   {
    "playerId": "mich-m-h4",
    "seed": "5",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "pepp-m-h6",
    "seed": "2",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": false
   }
  ]
 },
 {
  "event": "W15 Grodzisk Mazowiecki",
  "tournamentId": 17242,
  "tour": "wta",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "aub-w-h1",
    "seed": "7",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": false
   },
   {
    "playerId": "uga-w-h2",
    "seed": "6",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": false
   },
   {
    "playerId": "uva-w-h6",
    "seed": "2",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": false
   }
  ]
 }
];

// §244: champions from the trailing 14 days (ledger-backed, survives
// the Monday week reset)
export const recentChampions = globalThis.__BAGEL_REMOTE__?.["drawFixtures"]?.recentChampions ?? [
 {
  "key": "wta:17229",
  "playerId": "ucla-w-p3",
  "event": "W15 Torello",
  "score": "4-6 6-0 6-4",
  "date": "2026-08-30"
 },
 {
  "key": "wta:17228",
  "playerId": "lsu-p8",
  "event": "W35 Barueri",
  "score": "1-6 7-5 6-3",
  "date": "2026-08-30"
 },
 {
  "key": "atp:21997",
  "playerId": "osu-m-p7",
  "event": "M15 Champaign",
  "score": "6-2 7-6(6)",
  "date": "2026-08-30"
 }
];

// legacy flat view (§243 consumers)
export const drawFixtures = globalThis.__BAGEL_REMOTE__?.["drawFixtures"]?.drawFixtures ?? [
 {
  "playerId": "rice-w-h2",
  "event": "W15 Fiano Romano",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "okst-w-h2",
  "event": "W15 Fiano Romano",
  "seed": "6",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "lmu-w-h8",
  "event": "W15 Fiano Romano",
  "seed": "2",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "tenn-w-h7",
  "event": "W15 Fiano Romano",
  "seed": "4",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "asu-w-h8",
  "event": "W50 Leiria",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "uga-w-h6",
  "event": "W50 Leiria",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "cal-w-h2",
  "event": "W50 Leiria",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "aub-w-h7",
  "event": "W50 Leiria",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "tex-w-h5",
  "event": "W50 Leiria",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "neb-w-h7",
  "event": "W50 Leiria",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ncst-w-h3",
  "event": "W50 Leiria",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "msu-w-h16",
  "event": "W50 Leiria",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "osu-w-h3",
  "event": "W50 Leiria",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "ncst-w-h11",
  "event": "W75 Tianjin",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ucla-w-h6",
  "event": "W75 Tianjin",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "wash-w-h7",
  "event": "W75 Tianjin",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "usc-w-h12",
  "event": "W50 Saint-Palais-sur-Mer",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ucf-w-h5",
  "event": "W50 Saint-Palais-sur-Mer",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": true
 },
 {
  "playerId": "ala-w-h1",
  "event": "W50 Saint-Palais-sur-Mer",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": true
 },
 {
  "playerId": "tex-w-h11",
  "event": "W15 Cap d'Agde",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "wsu-w-h7",
  "event": "W15 Cap d'Agde",
  "seed": "4",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "aub-p12",
  "event": "W35 Verbier",
  "seed": "6",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tcu-w-h2",
  "event": "W35 Verbier",
  "seed": "5",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "wash-w-p3",
  "event": "W35 Verbier",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "wsu-w-h7",
  "event": "W35 Verbier",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ucla-w-p3",
  "event": "W15 Torello",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "prin-w-p4",
  "event": "W15 Torello",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "lsu-p8",
  "event": "W35 Barueri",
  "seed": "3",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "corn-w-h13",
  "event": "W35 Barueri",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tenn-w-h9",
  "event": "W35 Barueri",
  "seed": "8",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "aub-w-h6",
  "event": "W35 Barueri",
  "seed": "2",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "lmu-w-p4",
  "event": "W35 Barueri",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ore-w-h7",
  "event": "W35 Barueri",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ore-w-p2",
  "event": "W35 Barueri",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "okst-w-p1",
  "event": "W15 Brasov",
  "seed": "3",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "bay-w-h13",
  "event": "W50 Oldenzaal",
  "seed": "4",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ala-w-h1",
  "event": "W50 Oldenzaal",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "usc-w-h12",
  "event": "W50 Oldenzaal",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uga-w-h7",
  "event": "Abierto GNP Seguros - Monterrey",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "pepp-w-h4",
  "event": "Abierto GNP Seguros - Monterrey",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "fla-w-n3",
  "event": "Philly Open - Philadelphia",
  "seed": null,
  "entry": "LL",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "okst-w-h10",
  "event": "Philly Open - Philadelphia",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "okst-w-h7",
  "event": "Philly Open - Philadelphia",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "unc-w-h2",
  "event": "Philly Open - Philadelphia",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ucla-w-h6",
  "event": "Philly Open - Philadelphia",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uga-w-h6",
  "event": "Philly Open - Philadelphia",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tamu-p5",
  "event": "Philly Open - Philadelphia",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "aub-w-h7",
  "event": "Philly Open - Philadelphia",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "unc-w-p4",
  "event": "Philly Open - Philadelphia",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tenn-w-h4",
  "event": "W75 Bytom",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ou-w-h13",
  "event": "W75 Bytom",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ala-w-h8",
  "event": "W75 Bytom",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "uva-w-h6",
  "event": "W75 Bytom",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "ncst-w-h5",
  "event": "W75 Bytom",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "miss-w-h1",
  "event": "W75 Bytom",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "ala-p10",
  "event": "W35 Trieste",
  "seed": null,
  "entry": "SE",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "rice-w-h2",
  "event": "W35 Trieste",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ucf-w-h5",
  "event": "W35 Trieste",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tenn-w-h7",
  "event": "W35 Trieste",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "ncst-w-h11",
  "event": "W15 Tianjin",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "utah-w-h2",
  "event": "W15 Tianjin",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "pepp-w-h5",
  "event": "W75 Kursumlijska Banja",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "stan-m-h6",
  "event": "Manacor Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tcu-m-h8",
  "event": "Manacor Challenger",
  "seed": "6",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "uva-m-h4",
  "event": "Manacor Challenger",
  "seed": null,
  "entry": "ALT",
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ariz-m-fp226",
  "event": "Manacor Challenger",
  "seed": null,
  "entry": "CO",
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "usd-m-h8",
  "event": "Manacor Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "bay-m-h12",
  "event": "Manacor Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "tcu-m-h5",
  "event": "Manacor Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "neb-m-h9",
  "event": "Manacor Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "cal-m-h6",
  "event": "Manacor Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "bay-m-h11",
  "event": "Como Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ttu-m-h1",
  "event": "Como Challenger",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tex-m-n3",
  "event": "Como Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "tenn-m-h6",
  "event": "M25 Urayasu",
  "seed": "4",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "okst-m-h6",
  "event": "M25 Urayasu",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "unc-m-h2",
  "event": "M15 Buzau",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "unc-m-p1",
  "event": "M15 Buzau",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ore-m-p1",
  "event": "M15 Buzau",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tamu-m-h9",
  "event": "M15 Trelew",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "uga-m-p3",
  "event": "M15 Trelew",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "usf-m-p3",
  "event": "M15 Trelew",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "ala-m-h4",
  "event": "Plovdiv 3 Challenger",
  "seed": null,
  "entry": "ALT",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ttu-m-h2",
  "event": "Plovdiv 3 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "tamu-m-p6",
  "event": "Plovdiv 3 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "port-m-h5",
  "event": "Zhangjiagang Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "temple-m-n1",
  "event": "Zhangjiagang Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "ore-m-h2",
  "event": "Zhangjiagang Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "lou-m-h5",
  "event": "M25+H Bagneres-de-Bigorre",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "tcu-m-h2",
  "event": "M25+H Bagneres-de-Bigorre",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "scu-m-h2",
  "event": "M25+H Bagneres-de-Bigorre",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ark-m-h14",
  "event": "M25+H Bagneres-de-Bigorre",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "fla-m-p4",
  "event": "M25+H Bagneres-de-Bigorre",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "tamu-m-h7",
  "event": "M25+H Bagneres-de-Bigorre",
  "seed": null,
  "entry": "2WC",
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "fla-m-h11",
  "event": "Kingston 2 Challenger",
  "seed": "2",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "gt-m-h8",
  "event": "Kingston 2 Challenger",
  "seed": "6",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "mich-m-h5",
  "event": "Kingston 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "gt-m-h3",
  "event": "Kingston 2 Challenger",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ucla-m-h8",
  "event": "Kingston 2 Challenger",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "duke-m-h2",
  "event": "Kingston 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "unc-m-h8",
  "event": "Kingston 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "okst-m-h4",
  "event": "Kingston 2 Challenger",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "wich-m-fp92",
  "event": "Kingston 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "osu-m-p5",
  "event": "Kingston 2 Challenger",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tenn-m-h10",
  "event": "Kingston 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "pepp-m-p6",
  "event": "Kingston 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "sc-m-p1",
  "event": "Kingston 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "fla-m-p1",
  "event": "Kingston 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "clem-m-p9",
  "event": "Kingston 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "tulsa-m-h3",
  "event": "Kingston 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "usc-m-p3",
  "event": "M15 Kursumlijska Banja",
  "seed": "1",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "msu-m-h10",
  "event": "M15 Kursumlijska Banja",
  "seed": "8",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "miss-m-p2",
  "event": "M15 Kursumlijska Banja",
  "seed": "3",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "osu-m-p7",
  "event": "M15 Champaign",
  "seed": "5",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ark-m-p6",
  "event": "M15 Champaign",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "asu-m-p2",
  "event": "M15 Champaign",
  "seed": "8",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uga-m-h1",
  "event": "M15 Champaign",
  "seed": "1",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "asu-m-p10",
  "event": "M15 Champaign",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tamu-m-n1",
  "event": "M15 Champaign",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uk-m-p7",
  "event": "M15 Champaign",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "osu-m-p11",
  "event": "M15 Champaign",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "osu-m-fp278",
  "event": "M15 Champaign",
  "seed": "3",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "clem-m-p6",
  "event": "M15 Champaign",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ill-m-p8",
  "event": "M15 Champaign",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "aub-m-n1",
  "event": "M15 Champaign",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ill-m-p1",
  "event": "M15 Champaign",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uk-m-p2",
  "event": "M15 Champaign",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uk-m-p1",
  "event": "M15 Champaign",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ill-m-p6",
  "event": "M15 Champaign",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ill-m-p7",
  "event": "M15 Champaign",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "asu-m-p4",
  "event": "M15 Champaign",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tamu-m-h9",
  "event": "M15 Champaign",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "asu-m-fp38",
  "event": "M15 Champaign",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "clem-m-p7",
  "event": "M15 Champaign",
  "seed": "2",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uci-m-p9",
  "event": "M15 Champaign",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "prin-m-p5",
  "event": "M15 Champaign",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "tenn-m-p8",
  "event": "M15 Champaign",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "neb-m-h6",
  "event": "M15 Allershausen",
  "seed": "6",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ou-m-h5",
  "event": "M15 Allershausen",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "clem-m-fp162",
  "event": "M15 Vienna",
  "seed": "6",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "stan-m-h4",
  "event": "Winston-Salem Open - Winston-Salem",
  "seed": "4",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "fla-m-h9",
  "event": "Winston-Salem Open - Winston-Salem",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "wake-m-p5",
  "event": "Winston-Salem Open - Winston-Salem",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ore-m-h7",
  "event": "Winston-Salem Open - Winston-Salem",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "wake-m-fp302",
  "event": "Winston-Salem Open - Winston-Salem",
  "seed": null,
  "entry": "LL",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tex-m-p8",
  "event": "Winston-Salem Open - Winston-Salem",
  "seed": null,
  "entry": "LL",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tenn-m-h15",
  "event": "Winston-Salem Open - Winston-Salem",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ucla-m-h13",
  "event": "Winston-Salem Open - Winston-Salem",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "unc-m-h9",
  "event": "Winston-Salem Open - Winston-Salem",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "tcu-m-p6",
  "event": "Winston-Salem Open - Winston-Salem",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "wake-m-p4",
  "event": "Winston-Salem Open - Winston-Salem",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "ill-m-h3",
  "event": "Winston-Salem Open - Winston-Salem",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "ill-m-fp217",
  "event": "Winston-Salem Open - Winston-Salem",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "okst-m-h6",
  "event": "M15 Maanshan",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ore-m-h2",
  "event": "M15 Maanshan",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tulsa-m-p5",
  "event": "M15 Maanshan",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "cal-m-h7",
  "event": "M15 Maanshan",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "temple-m-n1",
  "event": "M15 Maanshan",
  "seed": "6",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ttu-m-h2",
  "event": "M25 Poznan",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tamu-m-h16",
  "event": "M25 Poznan",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ala-m-h4",
  "event": "M25 Maribor",
  "seed": "6",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "pur-m-p2",
  "event": "M25 Maribor",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "miss-m-h3",
  "event": "M15 Pecs",
  "seed": "4",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "harv-m-p5",
  "event": "M15 Pecs",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ariz-m-h1",
  "event": "M15 Pecs",
  "seed": "3",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "msst-m-p8",
  "event": "Augsburg Challenger",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "bay-m-h11",
  "event": "Augsburg Challenger",
  "seed": "3",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tamu-m-h7",
  "event": "Augsburg Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "mich-m-h4",
  "event": "M25 Lausanne",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uva-m-h6",
  "event": "M25 Lausanne",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "usd-m-p8",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "stan-m-h6",
  "event": "Roehampton 2 Challenger",
  "seed": "1",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tenn-m-h5",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ucla-m-h5",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uva-m-h4",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tenn-m-h7",
  "event": "Roehampton 2 Challenger",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ariz-m-fp226",
  "event": "Roehampton 2 Challenger",
  "seed": "8",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tcu-m-h5",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "aub-m-p1",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "bay-m-h12",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "neb-m-h9",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "usc-m-h3",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "tamu-m-h6",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "duke-m-h1",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "uk-m-h10",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "uk-m-h14",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "mem-m-h2",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "usc-m-h10",
  "event": "Roehampton 2 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "uga-m-h16",
  "event": "M25 Oviedo",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "duke-m-fp157",
  "event": "M25 Oviedo",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "msst-m-h4",
  "event": "M25 Oviedo",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "asu-m-p9",
  "event": "M25 Oviedo",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "cal-m-p9",
  "event": "M25 Oviedo",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "usd-m-p4",
  "event": "M25 Oldenzaal",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "pepp-m-h6",
  "event": "M25 Oldenzaal",
  "seed": "3",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "usd-m-h3",
  "event": "M25 Oldenzaal",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uga-m-p3",
  "event": "M15 Mar Del Plata",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "fsu-m-fp26",
  "event": "M15 Mar Del Plata",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "tenn-w-h9",
  "event": "W15 Lujan",
  "seed": "4",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ou-w-h9",
  "event": "W15 Lujan",
  "seed": "3",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ou-m-h5",
  "event": "M25 Meerbusch",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "usd-m-h3",
  "event": "M25 Meerbusch",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "mich-m-h4",
  "event": "M25 Meerbusch",
  "seed": "5",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "pepp-m-h6",
  "event": "M25 Meerbusch",
  "seed": "2",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "aub-w-h1",
  "event": "W15 Grodzisk Mazowiecki",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "uga-w-h2",
  "event": "W15 Grodzisk Mazowiecki",
  "seed": "6",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "uva-w-h6",
  "event": "W15 Grodzisk Mazowiecki",
  "seed": "2",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 }
];
