// GENERATED by scripts/build-draw-fixtures.mjs -- do not edit.
// Per-event draw state for this week: finished flag (the singleton
// final round has a result), our champion when one of ours won it, and
// per-player entry status (seed, main/quali, eliminated). Draws appear
// when made: quali ~Saturday, main ~Sun/Mon. asOf 2026-09-11.
export const drawEvents = globalThis.__BAGEL_REMOTE__?.["drawFixtures"]?.drawEvents ?? [
 {
  "event": "W15 Yeongwol",
  "tournamentId": 17270,
  "tour": "wta",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "isu-w-h3",
    "seed": "3",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "ATIK Antalya Open - Antalya",
  "tournamentId": 17252,
  "tour": "wta",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "bay-w-h13",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   }
  ]
 },
 {
  "event": "W15 Radom",
  "tournamentId": 17276,
  "tour": "wta",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "uva-w-h6",
    "seed": "1",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "uga-w-h2",
    "seed": "7",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "miss-w-h1",
    "seed": "2",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   }
  ]
 },
 {
  "event": "W15 Campulung",
  "tournamentId": 17273,
  "tour": "wta",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "okst-w-p1",
    "seed": "3",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "W15 Viserba di Rimini",
  "tournamentId": 17269,
  "tour": "wta",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "wash-w-h8",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tenn-w-h7",
    "seed": "6",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "lmu-w-h8",
    "seed": "2",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "rice-w-h2",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "okst-w-h2",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "W15 Pilar",
  "tournamentId": 17275,
  "tour": "wta",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "tenn-w-h9",
    "seed": "4",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "ou-w-h9",
    "seed": "3",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "tenn-p3",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   }
  ]
 },
 {
  "event": "W15 Dijon",
  "tournamentId": 17271,
  "tour": "wta",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "ncst-w-h5",
    "seed": "1",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ucf-w-h5",
    "seed": "3",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "W50 Evora",
  "tournamentId": 17265,
  "tour": "wta",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "lsu-p6",
    "seed": "1",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "tex-w-h5",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "uga-w-h6",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "unc-w-p2",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "neb-w-h7",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "okst-w-h7",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "aub-w-h7",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "msu-w-h16",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "cal-w-h2",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "asu-w-h8",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tex-w-h11",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "W15 Hurghada",
  "tournamentId": 17274,
  "tour": "wta",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "fsu-w-h5",
    "seed": "1",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "utah-w-h8",
    "seed": "7",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "lsu-p12",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "Kia Open - Barranquilla",
  "tournamentId": 17253,
  "tour": "wta",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "pur-w-h7",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "lsu-p8",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tenn-p6",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tamu-w-h5",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "W50 Guiyang",
  "tournamentId": 17266,
  "tour": "wta",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "ucla-w-h6",
    "seed": "8",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "wash-w-h7",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ncst-w-h11",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "Montreux Nestle Open - Montreux",
  "tournamentId": 17254,
  "tour": "wta",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "pepp-w-h5",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "usc-w-h12",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "W35 Reus",
  "tournamentId": 17267,
  "tour": "wta",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "ucla-w-p3",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "W15 Cap d'Agde",
  "tournamentId": 17247,
  "tour": "wta",
  "finished": true,
  "finalDate": "2026-09-05",
  "champion": null,
  "entries": [
   {
    "playerId": "tex-w-h11",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "wsu-w-h7",
    "seed": "4",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "W15 Grodzisk Mazowiecki",
  "tournamentId": 17242,
  "tour": "wta",
  "finished": true,
  "finalDate": "2026-09-06",
  "champion": null,
  "entries": [
   {
    "playerId": "uva-w-h6",
    "seed": "2",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "aub-w-h1",
    "seed": "7",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "uga-w-h2",
    "seed": "6",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "W15 Pecs",
  "tournamentId": 17244,
  "tour": "wta",
  "finished": true,
  "finalDate": "2026-09-06",
  "champion": null,
  "entries": [
   {
    "playerId": "ala-p10",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "Shanghai Challenger",
  "tournamentId": 22021,
  "tour": "atp",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "ncst-m-h11",
    "seed": "4",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "port-m-h5",
    "seed": null,
    "entry": "ALT",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ore-m-h2",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M25 Sapporo",
  "tournamentId": 22049,
  "tour": "atp",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "cal-m-h3",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "okst-m-h6",
    "seed": "7",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "ncst-m-h3",
    "seed": "5",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M15 Bali",
  "tournamentId": 22056,
  "tour": "atp",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "neb-m-h9",
    "seed": "1",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "stan-m-p5",
    "seed": null,
    "entry": "WC",
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "okst-m-h5",
    "seed": "6",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "fla-m-p8",
    "seed": "8",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ucd-m-h4",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "Istanbul Challenger",
  "tournamentId": 22024,
  "tour": "atp",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "uk-m-h14",
    "seed": null,
    "entry": "ALT",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "cal-m-h6",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "stan-m-h6",
    "seed": "7",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "ariz-m-fp226",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "bay-m-h12",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "usd-m-h8",
    "seed": "5",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "sc-m-p6",
    "seed": null,
    "entry": "WC",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "uga-m-p1",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tamu-m-p6",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "gt-m-h3",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M25 Plaisir",
  "tournamentId": 22045,
  "tour": "atp",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "wash-m-h10",
    "seed": "1",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "tcu-m-h2",
    "seed": null,
    "entry": "WC",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "stan-m-fp374",
    "seed": "3",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "ucla-m-h5",
    "seed": "2",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "pepp-m-h1",
    "seed": "4",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "fla-m-p4",
    "seed": "7",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ark-m-h14",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M25 Pozzuoli",
  "tournamentId": 22044,
  "tour": "atp",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "wake-m-h1",
    "seed": "7",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "wake-m-h3",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "tenn-m-h5",
    "seed": "2",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M25 Rabat",
  "tournamentId": 22046,
  "tour": "atp",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "uva-m-h6",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "tenn-m-h11",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "wake-m-h17",
    "seed": "4",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "lou-m-fp70",
    "seed": null,
    "entry": "WC",
    "inMain": true,
    "eliminated": false,
    "played": true
   }
  ]
 },
 {
  "event": "M15 Nonthaburi",
  "tournamentId": 22050,
  "tour": "atp",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "ou-m-h2",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "fla-m-p7",
    "seed": null,
    "entry": "WC",
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "Phan Thiet 3 Challenger",
  "tournamentId": 22025,
  "tour": "atp",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "ill-m-fp217",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "temple-m-n1",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "mich-m-p8",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ncst-m-fp370",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ill-m-h3",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "Genoa Challenger",
  "tournamentId": 22019,
  "tour": "atp",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "tex-m-n3",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   }
  ]
 },
 {
  "event": "M15 Budapest",
  "tournamentId": 22055,
  "tour": "atp",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "ark-m-p3",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tenn-m-n5",
    "seed": "5",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "asu-m-p2",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "unc-m-h2",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "Cassis Challenger",
  "tournamentId": 22023,
  "tour": "atp",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "tamu-m-h7",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "osu-m-h2",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "usc-m-h3",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "scu-m-h2",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M25 Gijon",
  "tournamentId": 22047,
  "tour": "atp",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "asu-m-p9",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "uga-m-h16",
    "seed": "4",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "cal-m-p9",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "Tulln Challenger",
  "tournamentId": 22022,
  "tour": "atp",
  "finished": false,
  "finalDate": null,
  "champion": null,
  "entries": [
   {
    "playerId": "bay-m-h11",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "ttu-m-h1",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M15 Kursumlijska Banja",
  "tournamentId": 22009,
  "tour": "atp",
  "finished": true,
  "finalDate": "2026-09-06",
  "champion": {
   "playerId": "usc-m-p3",
   "score": "6-7(3) 6-2 6-4",
   "date": "2026-09-06"
  },
  "entries": [
   {
    "playerId": "usc-m-p3",
    "seed": "1",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "miss-m-p2",
    "seed": "3",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "msu-m-h10",
    "seed": "8",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M25 Meerbusch",
  "tournamentId": 22004,
  "tour": "atp",
  "finished": true,
  "finalDate": "2026-09-06",
  "champion": null,
  "entries": [
   {
    "playerId": "pepp-m-h6",
    "seed": "2",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ou-m-h5",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "usd-m-h3",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "mich-m-h4",
    "seed": "5",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "Manacor Challenger",
  "tournamentId": 21942,
  "tour": "atp",
  "finished": true,
  "finalDate": "2026-09-06",
  "champion": null,
  "entries": [
   {
    "playerId": "uva-m-h4",
    "seed": null,
    "entry": "ALT",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tcu-m-h8",
    "seed": "6",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "stan-m-h6",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ariz-m-fp226",
    "seed": null,
    "entry": "CO",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "usd-m-h8",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "bay-m-h12",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tcu-m-h5",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "neb-m-h9",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "cal-m-h6",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M15 Szczawno",
  "tournamentId": 22017,
  "tour": "atp",
  "finished": true,
  "finalDate": "2026-09-06",
  "champion": {
   "playerId": "miss-m-h3",
   "score": "6-4 6-4",
   "date": "2026-09-06"
  },
  "entries": [
   {
    "playerId": "miss-m-h3",
    "seed": "2",
    "entry": null,
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "neb-m-h6",
    "seed": "5",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M15 Madrid",
  "tournamentId": 22008,
  "tour": "atp",
  "finished": true,
  "finalDate": "2026-09-06",
  "champion": null,
  "entries": [
   {
    "playerId": "cal-m-p9",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "duke-m-fp157",
    "seed": "3",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "msst-m-h4",
    "seed": "5",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "uga-m-h16",
    "seed": "4",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "asu-m-p9",
    "seed": null,
    "entry": "JR",
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M25 Urayasu",
  "tournamentId": 22005,
  "tour": "atp",
  "finished": true,
  "finalDate": "2026-09-06",
  "champion": null,
  "entries": [
   {
    "playerId": "tenn-m-h6",
    "seed": "4",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "okst-m-h6",
    "seed": "7",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M15 Bologna",
  "tournamentId": 22018,
  "tour": "atp",
  "finished": true,
  "finalDate": "2026-09-06",
  "champion": null,
  "entries": [
   {
    "playerId": "clem-m-fp162",
    "seed": "7",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M25+H Bagneres-de-Bigorre",
  "tournamentId": 22002,
  "tour": "atp",
  "finished": true,
  "finalDate": "2026-09-06",
  "champion": {
   "playerId": "tamu-m-h7",
   "score": "4-6 6-2 6-3",
   "date": "2026-09-06"
  },
  "entries": [
   {
    "playerId": "tamu-m-h7",
    "seed": null,
    "entry": "2WC",
    "inMain": true,
    "eliminated": false,
    "played": true
   },
   {
    "playerId": "lou-m-h5",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ark-m-h14",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tcu-m-h2",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "scu-m-h2",
    "seed": "7",
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "fla-m-p4",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M15 Trelew",
  "tournamentId": 22011,
  "tour": "atp",
  "finished": true,
  "finalDate": "2026-09-05",
  "champion": null,
  "entries": [
   {
    "playerId": "tamu-m-h9",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "uga-m-p3",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "usf-m-p3",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "Plovdiv 3 Challenger",
  "tournamentId": 21945,
  "tour": "atp",
  "finished": true,
  "finalDate": "2026-09-06",
  "champion": null,
  "entries": [
   {
    "playerId": "ala-m-h4",
    "seed": null,
    "entry": "ALT",
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ttu-m-h2",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "tamu-m-p6",
    "seed": null,
    "entry": null,
    "inMain": false,
    "eliminated": true,
    "played": true
   }
  ]
 },
 {
  "event": "M15 Buzau",
  "tournamentId": 22016,
  "tour": "atp",
  "finished": true,
  "finalDate": "2026-09-06",
  "champion": null,
  "entries": [
   {
    "playerId": "unc-m-h2",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "unc-m-p1",
    "seed": null,
    "entry": null,
    "inMain": true,
    "eliminated": true,
    "played": true
   },
   {
    "playerId": "ore-m-p1",
    "seed": null,
    "entry": "Q",
    "inMain": true,
    "eliminated": true,
    "played": true
   }
  ]
 }
];

// §244: champions from the trailing 14 days (ledger-backed, survives
// the Monday week reset)
export const recentChampions = globalThis.__BAGEL_REMOTE__?.["drawFixtures"]?.recentChampions ?? [
 {
  "key": "wta:17229",
  "playerId": "ucla-w-p3",
  "event": "W15 Torello",
  "score": "4-6 6-0 6-4",
  "date": "2026-08-30"
 },
 {
  "key": "wta:17228",
  "playerId": "lsu-p8",
  "event": "W35 Barueri",
  "score": "1-6 7-5 6-3",
  "date": "2026-08-30"
 },
 {
  "key": "atp:21997",
  "playerId": "osu-m-p7",
  "event": "M15 Champaign",
  "score": "6-2 7-6(6)",
  "date": "2026-08-30"
 },
 {
  "key": "atp:M15 Kursumlijska Banja",
  "playerId": "usc-m-p3",
  "event": "M15 Kursumlijska Banja",
  "score": "6-2 6-7(4) 6-3",
  "date": "2026-08-30",
  "source": "recovered from onTourWeek harvest (git 7b114868); draws probe had missed this event",
  "opponent": "Dmitry Popko"
 },
 {
  "key": "wta:17243",
  "playerId": "rice-w-h2",
  "event": "W15 Fiano Romano",
  "score": "6-1 7-5",
  "date": "2026-09-06"
 },
 {
  "key": "atp:22009",
  "playerId": "usc-m-p3",
  "event": "M15 Kursumlijska Banja",
  "score": "6-7(3) 6-2 6-4",
  "date": "2026-09-06"
 },
 {
  "key": "atp:22017",
  "playerId": "miss-m-h3",
  "event": "M15 Szczawno",
  "score": "6-4 6-4",
  "date": "2026-09-06"
 },
 {
  "key": "atp:Como Challenger",
  "playerId": "tex-m-n3",
  "event": "Como Challenger",
  "score": "6-3 7-6(5)",
  "date": "2026-09-06",
  "opponent": "Juan Pablo Varillas",
  "source": "onTourWeek results row"
 },
 {
  "key": "atp:21941",
  "playerId": "tex-m-n3",
  "event": "Como Challenger",
  "score": "6-3 7-6(5)",
  "date": "2026-09-06"
 },
 {
  "key": "atp:22002",
  "playerId": "tamu-m-h7",
  "event": "M25+H Bagneres-de-Bigorre",
  "score": "4-6 6-2 6-3",
  "date": "2026-09-06"
 }
];

// legacy flat view (§243 consumers)
export const drawFixtures = globalThis.__BAGEL_REMOTE__?.["drawFixtures"]?.drawFixtures ?? [
 {
  "playerId": "isu-w-h3",
  "event": "W15 Yeongwol",
  "seed": "3",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "bay-w-h13",
  "event": "ATIK Antalya Open - Antalya",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "uva-w-h6",
  "event": "W15 Radom",
  "seed": "1",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "uga-w-h2",
  "event": "W15 Radom",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "miss-w-h1",
  "event": "W15 Radom",
  "seed": "2",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "okst-w-p1",
  "event": "W15 Campulung",
  "seed": "3",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "wash-w-h8",
  "event": "W15 Viserba di Rimini",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tenn-w-h7",
  "event": "W15 Viserba di Rimini",
  "seed": "6",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "lmu-w-h8",
  "event": "W15 Viserba di Rimini",
  "seed": "2",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "rice-w-h2",
  "event": "W15 Viserba di Rimini",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "okst-w-h2",
  "event": "W15 Viserba di Rimini",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tenn-w-h9",
  "event": "W15 Pilar",
  "seed": "4",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ou-w-h9",
  "event": "W15 Pilar",
  "seed": "3",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "tenn-p3",
  "event": "W15 Pilar",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ncst-w-h5",
  "event": "W15 Dijon",
  "seed": "1",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ucf-w-h5",
  "event": "W15 Dijon",
  "seed": "3",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "lsu-p6",
  "event": "W50 Evora",
  "seed": "1",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "tex-w-h5",
  "event": "W50 Evora",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uga-w-h6",
  "event": "W50 Evora",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "unc-w-p2",
  "event": "W50 Evora",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "neb-w-h7",
  "event": "W50 Evora",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "okst-w-h7",
  "event": "W50 Evora",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "aub-w-h7",
  "event": "W50 Evora",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "msu-w-h16",
  "event": "W50 Evora",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "cal-w-h2",
  "event": "W50 Evora",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "asu-w-h8",
  "event": "W50 Evora",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "tex-w-h11",
  "event": "W50 Evora",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "fsu-w-h5",
  "event": "W15 Hurghada",
  "seed": "1",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "utah-w-h8",
  "event": "W15 Hurghada",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "lsu-p12",
  "event": "W15 Hurghada",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "pur-w-h7",
  "event": "Kia Open - Barranquilla",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "lsu-p8",
  "event": "Kia Open - Barranquilla",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tenn-p6",
  "event": "Kia Open - Barranquilla",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tamu-w-h5",
  "event": "Kia Open - Barranquilla",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ucla-w-h6",
  "event": "W50 Guiyang",
  "seed": "8",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "wash-w-h7",
  "event": "W50 Guiyang",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "ncst-w-h11",
  "event": "W50 Guiyang",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "pepp-w-h5",
  "event": "Montreux Nestle Open - Montreux",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "usc-w-h12",
  "event": "Montreux Nestle Open - Montreux",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "ucla-w-p3",
  "event": "W35 Reus",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "tex-w-h11",
  "event": "W15 Cap d'Agde",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "wsu-w-h7",
  "event": "W15 Cap d'Agde",
  "seed": "4",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uva-w-h6",
  "event": "W15 Grodzisk Mazowiecki",
  "seed": "2",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "aub-w-h1",
  "event": "W15 Grodzisk Mazowiecki",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uga-w-h2",
  "event": "W15 Grodzisk Mazowiecki",
  "seed": "6",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ala-p10",
  "event": "W15 Pecs",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ncst-m-h11",
  "event": "Shanghai Challenger",
  "seed": "4",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "port-m-h5",
  "event": "Shanghai Challenger",
  "seed": null,
  "entry": "ALT",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ore-m-h2",
  "event": "Shanghai Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "cal-m-h3",
  "event": "M25 Sapporo",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "okst-m-h6",
  "event": "M25 Sapporo",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ncst-m-h3",
  "event": "M25 Sapporo",
  "seed": "5",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "neb-m-h9",
  "event": "M15 Bali",
  "seed": "1",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "stan-m-p5",
  "event": "M15 Bali",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "okst-m-h5",
  "event": "M15 Bali",
  "seed": "6",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "fla-m-p8",
  "event": "M15 Bali",
  "seed": "8",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ucd-m-h4",
  "event": "M15 Bali",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "uk-m-h14",
  "event": "Istanbul Challenger",
  "seed": null,
  "entry": "ALT",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "cal-m-h6",
  "event": "Istanbul Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "stan-m-h6",
  "event": "Istanbul Challenger",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ariz-m-fp226",
  "event": "Istanbul Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "bay-m-h12",
  "event": "Istanbul Challenger",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "usd-m-h8",
  "event": "Istanbul Challenger",
  "seed": "5",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "sc-m-p6",
  "event": "Istanbul Challenger",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uga-m-p1",
  "event": "Istanbul Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "tamu-m-p6",
  "event": "Istanbul Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "gt-m-h3",
  "event": "Istanbul Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "wash-m-h10",
  "event": "M25 Plaisir",
  "seed": "1",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "tcu-m-h2",
  "event": "M25 Plaisir",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "stan-m-fp374",
  "event": "M25 Plaisir",
  "seed": "3",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ucla-m-h5",
  "event": "M25 Plaisir",
  "seed": "2",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "pepp-m-h1",
  "event": "M25 Plaisir",
  "seed": "4",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "fla-m-p4",
  "event": "M25 Plaisir",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ark-m-h14",
  "event": "M25 Plaisir",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "wake-m-h1",
  "event": "M25 Pozzuoli",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "wake-m-h3",
  "event": "M25 Pozzuoli",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "tenn-m-h5",
  "event": "M25 Pozzuoli",
  "seed": "2",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uva-m-h6",
  "event": "M25 Rabat",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "tenn-m-h11",
  "event": "M25 Rabat",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "wake-m-h17",
  "event": "M25 Rabat",
  "seed": "4",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "lou-m-fp70",
  "event": "M25 Rabat",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ou-m-h2",
  "event": "M15 Nonthaburi",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "fla-m-p7",
  "event": "M15 Nonthaburi",
  "seed": null,
  "entry": "WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ill-m-fp217",
  "event": "Phan Thiet 3 Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "temple-m-n1",
  "event": "Phan Thiet 3 Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "mich-m-p8",
  "event": "Phan Thiet 3 Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ncst-m-fp370",
  "event": "Phan Thiet 3 Challenger",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ill-m-h3",
  "event": "Phan Thiet 3 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "tex-m-n3",
  "event": "Genoa Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ark-m-p3",
  "event": "M15 Budapest",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tenn-m-n5",
  "event": "M15 Budapest",
  "seed": "5",
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "asu-m-p2",
  "event": "M15 Budapest",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "unc-m-h2",
  "event": "M15 Budapest",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tamu-m-h7",
  "event": "Cassis Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "osu-m-h2",
  "event": "Cassis Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "usc-m-h3",
  "event": "Cassis Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "scu-m-h2",
  "event": "Cassis Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "asu-m-p9",
  "event": "M25 Gijon",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uga-m-h16",
  "event": "M25 Gijon",
  "seed": "4",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "cal-m-p9",
  "event": "M25 Gijon",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "bay-m-h11",
  "event": "Tulln Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": true
 },
 {
  "playerId": "ttu-m-h1",
  "event": "Tulln Challenger",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "usc-m-p3",
  "event": "M15 Kursumlijska Banja",
  "seed": "1",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "miss-m-p2",
  "event": "M15 Kursumlijska Banja",
  "seed": "3",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "msu-m-h10",
  "event": "M15 Kursumlijska Banja",
  "seed": "8",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "pepp-m-h6",
  "event": "M25 Meerbusch",
  "seed": "2",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ou-m-h5",
  "event": "M25 Meerbusch",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "usd-m-h3",
  "event": "M25 Meerbusch",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "mich-m-h4",
  "event": "M25 Meerbusch",
  "seed": "5",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uva-m-h4",
  "event": "Manacor Challenger",
  "seed": null,
  "entry": "ALT",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tcu-m-h8",
  "event": "Manacor Challenger",
  "seed": "6",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "stan-m-h6",
  "event": "Manacor Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ariz-m-fp226",
  "event": "Manacor Challenger",
  "seed": null,
  "entry": "CO",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "usd-m-h8",
  "event": "Manacor Challenger",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "bay-m-h12",
  "event": "Manacor Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "tcu-m-h5",
  "event": "Manacor Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "neb-m-h9",
  "event": "Manacor Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "cal-m-h6",
  "event": "Manacor Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "miss-m-h3",
  "event": "M15 Szczawno",
  "seed": "2",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "neb-m-h6",
  "event": "M15 Szczawno",
  "seed": "5",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "cal-m-p9",
  "event": "M15 Madrid",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "duke-m-fp157",
  "event": "M15 Madrid",
  "seed": "3",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "msst-m-h4",
  "event": "M15 Madrid",
  "seed": "5",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uga-m-h16",
  "event": "M15 Madrid",
  "seed": "4",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "asu-m-p9",
  "event": "M15 Madrid",
  "seed": null,
  "entry": "JR",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tenn-m-h6",
  "event": "M25 Urayasu",
  "seed": "4",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "okst-m-h6",
  "event": "M25 Urayasu",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "clem-m-fp162",
  "event": "M15 Bologna",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tamu-m-h7",
  "event": "M25+H Bagneres-de-Bigorre",
  "seed": null,
  "entry": "2WC",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "lou-m-h5",
  "event": "M25+H Bagneres-de-Bigorre",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ark-m-h14",
  "event": "M25+H Bagneres-de-Bigorre",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tcu-m-h2",
  "event": "M25+H Bagneres-de-Bigorre",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "scu-m-h2",
  "event": "M25+H Bagneres-de-Bigorre",
  "seed": "7",
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "fla-m-p4",
  "event": "M25+H Bagneres-de-Bigorre",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "tamu-m-h9",
  "event": "M15 Trelew",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "uga-m-p3",
  "event": "M15 Trelew",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "usf-m-p3",
  "event": "M15 Trelew",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "ala-m-h4",
  "event": "Plovdiv 3 Challenger",
  "seed": null,
  "entry": "ALT",
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ttu-m-h2",
  "event": "Plovdiv 3 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "tamu-m-p6",
  "event": "Plovdiv 3 Challenger",
  "seed": null,
  "entry": null,
  "inMain": false,
  "hasUnplayed": false
 },
 {
  "playerId": "unc-m-h2",
  "event": "M15 Buzau",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "unc-m-p1",
  "event": "M15 Buzau",
  "seed": null,
  "entry": null,
  "inMain": true,
  "hasUnplayed": false
 },
 {
  "playerId": "ore-m-p1",
  "event": "M15 Buzau",
  "seed": null,
  "entry": "Q",
  "inMain": true,
  "hasUnplayed": false
 }
];
