// GENERATED by scripts/fetch-ita-rankings.mjs (§200) -- DO NOT EDIT.
// The COMPLETE newest NATIONAL ITA lists per gender/discipline, every
// ranked player included -- rows carry pid/teamId when the player maps
// into the app, null otherwise (rendered unlinked, never guessed).
export const itaRankedLists = globalThis.__BAGEL_REMOTE__?.["itaRankedLists"]?.itaRankedLists ?? {
 "singles": {
  "women": {
   "listId": "2026-27_d1_women_singles_p2_v1",
   "listDate": "2026-08-25",
   "rows": [
    {
     "rank": 1,
     "name": "Lucciana Perez",
     "school": "Texas A&M University",
     "teamId": "tamu-w",
     "pid": "tamu-p5"
    },
    {
     "rank": 2,
     "name": "Carmen Andreea Herea",
     "school": "University of Texas at Austin",
     "teamId": "tex-w",
     "pid": null
    },
    {
     "rank": 3,
     "name": "Luciana Perry",
     "school": "Ohio State",
     "teamId": "osu-w",
     "pid": "osu-w-p9"
    },
    {
     "rank": 4,
     "name": "Teah Chavez",
     "school": "Ohio State",
     "teamId": "osu-w",
     "pid": "osu-w-p3"
    },
    {
     "rank": 5,
     "name": "Aysegul Mert",
     "school": "University Of Georgia",
     "teamId": "uga-w",
     "pid": "uga-p7"
    },
    {
     "rank": 6,
     "name": "Piper Charney",
     "school": "University of Michigan",
     "teamId": "mich-w",
     "pid": "mich-w-p3"
    },
    {
     "rank": 7,
     "name": "Irina Balus",
     "school": "Duke",
     "teamId": "duke-w",
     "pid": "duke-w-p2"
    },
    {
     "rank": 8,
     "name": "Cadence Brace",
     "school": "Louisiana State University",
     "teamId": "lsu-w",
     "pid": "lsu-p8"
    },
    {
     "rank": 9,
     "name": "Evialina Laskevich",
     "school": "University of Oklahoma",
     "teamId": "ou-w",
     "pid": "ou-p4"
    },
    {
     "rank": 10,
     "name": "Mia Slama",
     "school": "NC State",
     "teamId": "ncst-w",
     "pid": "ncst-w-p7"
    },
    {
     "rank": 11,
     "name": "Jana Hossam Salah",
     "school": "University Of Florida",
     "teamId": "fla-w",
     "pid": "fla-w-n1"
    },
    {
     "rank": 12,
     "name": "Amelie Van Impe",
     "school": "SMU",
     "teamId": "smu-w",
     "pid": "smu-w-p9"
    },
    {
     "rank": 13,
     "name": "Mayu Crossley",
     "school": "UCLA",
     "teamId": "ucla-w",
     "pid": "ucla-w-p7"
    },
    {
     "rank": 14,
     "name": "Valeria Ray",
     "school": "Vanderbilt",
     "teamId": "van-w",
     "pid": "van-p5"
    },
    {
     "rank": 15,
     "name": "Emilija Tverijonaite",
     "school": "Arizona State",
     "teamId": "asu-w",
     "pid": "asu-w-p4"
    },
    {
     "rank": 16,
     "name": "Anastasiia Grechkina",
     "school": "Pepperdine",
     "teamId": "pepp-w",
     "pid": "pepp-w-p2"
    },
    {
     "rank": 17,
     "name": "Valery Gynina",
     "school": "University Of Florida",
     "teamId": "fla-w",
     "pid": "fla-p3"
    },
    {
     "rank": 18,
     "name": "Valerie Glozman",
     "school": "Stanford",
     "teamId": "stan-w",
     "pid": "stan-w-p1"
    },
    {
     "rank": 19,
     "name": "Monika Ekstrand",
     "school": "Stanford",
     "teamId": "stan-w",
     "pid": "stan-w-p4"
    },
    {
     "rank": 20,
     "name": "Ziva Falkner",
     "school": "Pepperdine",
     "teamId": "pepp-w",
     "pid": "pepp-w-p1"
    },
    {
     "rank": 21,
     "name": "Tatum Evans",
     "school": "UNC Chapel Hill",
     "teamId": "unc-w",
     "pid": "unc-w-p3"
    },
    {
     "rank": 22,
     "name": "Edda Mamedova",
     "school": "University of Oklahoma",
     "teamId": "ou-w",
     "pid": "ou-p5"
    },
    {
     "rank": 23,
     "name": "Kaitlyn Carnicella",
     "school": "University of South Carolina, Columbia",
     "teamId": "sc-w",
     "pid": "sc-p4"
    },
    {
     "rank": 24,
     "name": "Helena Buchwald",
     "school": "University of South Carolina, Columbia",
     "teamId": "sc-w",
     "pid": "sc-p3"
    },
    {
     "rank": 25,
     "name": "Sonja Zhiyenbayeva",
     "school": "Pepperdine",
     "teamId": "pepp-w",
     "pid": "pepp-w-p7"
    },
    {
     "rank": 26,
     "name": "Rose Marie Nijkamp",
     "school": "University of Texas at Austin",
     "teamId": "tex-w",
     "pid": "tex-w-n1"
    },
    {
     "rank": 27,
     "name": "Deniz Dilek",
     "school": "University Of Georgia",
     "teamId": "uga-w",
     "pid": "uga-p2"
    },
    {
     "rank": 28,
     "name": "Johanne Svendsen",
     "school": "University Of California, Berkeley",
     "teamId": "cal-w",
     "pid": "cal-w-p8"
    },
    {
     "rank": 29,
     "name": "Alyssa Ahn",
     "school": "Stanford",
     "teamId": "stan-w",
     "pid": "stan-w-p3"
    },
    {
     "rank": 30,
     "name": "Gabia Paskauskas",
     "school": "University Of Florida",
     "teamId": "fla-w",
     "pid": "fla-p7"
    },
    {
     "rank": 31,
     "name": "Aspen Schuman",
     "school": "Duke",
     "teamId": "duke-w",
     "pid": "duke-w-p6"
    },
    {
     "rank": 32,
     "name": "Vivian Yang",
     "school": "University of Virginia",
     "teamId": "uva-w",
     "pid": "uva-w-p8"
    },
    {
     "rank": 33,
     "name": "Lavinia Tanasie",
     "school": "NC State",
     "teamId": "ncst-w",
     "pid": "ncst-w-p9"
    },
    {
     "rank": 34,
     "name": "Ashton Bowers",
     "school": "Auburn",
     "teamId": "aub-w",
     "pid": "aub-p2"
    },
    {
     "rank": 35,
     "name": "Eszter Meri",
     "school": "University of Texas at Austin",
     "teamId": "tex-w",
     "pid": "tex-p9"
    },
    {
     "rank": 36,
     "name": "Ekaterina Ivanova",
     "school": "University Of Wisconsin, Madison",
     "teamId": "wisc-w",
     "pid": "wisc-w-p3"
    },
    {
     "rank": 37,
     "name": "Sophia Cisse-Ignatiev",
     "school": "Ohio State",
     "teamId": "osu-w",
     "pid": "osu-w-p4"
    },
    {
     "rank": 38,
     "name": "Anastasiia Gureva",
     "school": "University Of Georgia",
     "teamId": "uga-w",
     "pid": "uga-p5"
    },
    {
     "rank": 39,
     "name": "Nao Nishino",
     "school": "Ohio State",
     "teamId": "osu-w",
     "pid": "osu-w-p6"
    },
    {
     "rank": 40,
     "name": "Rinon Okuwaki",
     "school": "University Of Tennessee, Knoxville",
     "teamId": "tenn-w",
     "pid": "tenn-w-n3"
    },
    {
     "rank": 41,
     "name": "Ella McDonald",
     "school": "Louisiana State University",
     "teamId": "lsu-w",
     "pid": "lsu-p1"
    },
    {
     "rank": 42,
     "name": "Kyoka Kubo",
     "school": "University of Kansas",
     "teamId": "ku-w",
     "pid": "ku-w-p6"
    },
    {
     "rank": 43,
     "name": "Sophie Llewellyn",
     "school": "SMU",
     "teamId": "smu-w",
     "pid": "smu-w-p5"
    },
    {
     "rank": 44,
     "name": "Mia Mack",
     "school": "University Of Iowa",
     "teamId": "iowa-w",
     "pid": "iowa-w-p3"
    },
    {
     "rank": 45,
     "name": "Ava Esposito",
     "school": "Auburn",
     "teamId": "aub-w",
     "pid": "aub-p4"
    },
    {
     "rank": 46,
     "name": "Bianca Molnar",
     "school": "University of Notre Dame",
     "teamId": "nd-w",
     "pid": "nd-w-p10"
    },
    {
     "rank": 47,
     "name": "Raquel Caballero Chica",
     "school": "TCU",
     "teamId": "tcu-w",
     "pid": "tcu-w-p1"
    },
    {
     "rank": 48,
     "name": "Katie Rolls",
     "school": "University of Virginia",
     "teamId": "uva-w",
     "pid": "uva-w-p7"
    },
    {
     "rank": 49,
     "name": "Kristina Paskauskas",
     "school": "Texas A&M University",
     "teamId": "tamu-w",
     "pid": "tamu-w-n1"
    },
    {
     "rank": 50,
     "name": "Reese Miller",
     "school": "University of Michigan",
     "teamId": "mich-w",
     "pid": "mich-w-p7"
    },
    {
     "rank": 51,
     "name": "Mao Mushika",
     "school": "University Of California, Berkeley",
     "teamId": "cal-w",
     "pid": "cal-w-p6"
    },
    {
     "rank": 52,
     "name": "Gian Octa",
     "school": "Boston College",
     "teamId": "bc-w",
     "pid": "bc-w-p6"
    },
    {
     "rank": 53,
     "name": "Zuzanna Kubacha",
     "school": "Baylor University",
     "teamId": "bay-w",
     "pid": "bay-w-p4"
    },
    {
     "rank": 54,
     "name": "Emma Dong",
     "school": "University Of Georgia",
     "teamId": "uga-w",
     "pid": "uga-p3"
    },
    {
     "rank": 55,
     "name": "Stephanie Yakoff",
     "school": "Harvard",
     "teamId": "harv-w",
     "pid": "harv-w-p11"
    },
    {
     "rank": 56,
     "name": "Julia Zhu",
     "school": "University of Kentucky",
     "teamId": "uk-w",
     "pid": "uk-p10"
    },
    {
     "rank": 57,
     "name": "Margot Phanthala",
     "school": "Columbia",
     "teamId": "colum-w",
     "pid": null
    },
    {
     "rank": 58,
     "name": "Liv Hovde",
     "school": "Duke",
     "teamId": "duke-w",
     "pid": "duke-w-p3"
    },
    {
     "rank": 59,
     "name": "Eugenia Zozaya Menendez",
     "school": "University of Virginia",
     "teamId": "uva-w",
     "pid": null
    },
    {
     "rank": 60,
     "name": "Lexington Reed",
     "school": "Texas A&M University",
     "teamId": "tamu-w",
     "pid": "tamu-p8"
    },
    {
     "rank": 61,
     "name": "Grace Levelston",
     "school": "Southern California",
     "teamId": null,
     "pid": null
    },
    {
     "rank": 62,
     "name": "Eva Shaw",
     "school": "Florida State",
     "teamId": "fsu-w",
     "pid": "fsu-w-p9"
    },
    {
     "rank": 63,
     "name": "Addison Lanton",
     "school": "Louisiana State University",
     "teamId": "lsu-w",
     "pid": "lsu-p4"
    },
    {
     "rank": 64,
     "name": "Emily Sartz -Lunde",
     "school": "University of Michigan",
     "teamId": "mich-w",
     "pid": "mich-w-fp400"
    },
    {
     "rank": 65,
     "name": "Emma Kamper",
     "school": "Auburn",
     "teamId": "aub-w",
     "pid": "aub-p6"
    },
    {
     "rank": 66,
     "name": "Maria de la Paz Alberto",
     "school": "Iowa State",
     "teamId": "isu-w",
     "pid": "isu-w-fp358"
    },
    {
     "rank": 67,
     "name": "Isabelle Lacy",
     "school": "University of Virginia",
     "teamId": "uva-w",
     "pid": "uva-w-p4"
    },
    {
     "rank": 68,
     "name": "Lucie Pawlak",
     "school": "University Of Florida",
     "teamId": "fla-w",
     "pid": "fla-p8"
    },
    {
     "rank": 69,
     "name": "Kira Matushkina",
     "school": "TCU",
     "teamId": "tcu-w",
     "pid": "tcu-w-p6"
    },
    {
     "rank": 70,
     "name": "Chantal Sauvant",
     "school": "Pepperdine",
     "teamId": "pepp-w",
     "pid": "pepp-w-p6"
    },
    {
     "rank": 71,
     "name": "Oliwia Orlinska",
     "school": "University of Maryland, College Park",
     "teamId": "umd-w",
     "pid": "umd-w-p9"
    },
    {
     "rank": 72,
     "name": "Olivia Lincer",
     "school": "Texas A&M University",
     "teamId": "tamu-w",
     "pid": "tamu-w-n2"
    },
    {
     "rank": 73,
     "name": "Alice Ferlito",
     "school": "Princeton",
     "teamId": "prin-w",
     "pid": "prin-w-p4"
    },
    {
     "rank": 74,
     "name": "Hannah Read",
     "school": "University of San Diego",
     "teamId": "usd-w",
     "pid": "usd-w-p7"
    },
    {
     "rank": 75,
     "name": "Elizabeth Ionescu",
     "school": "University of Texas at Austin",
     "teamId": "tex-w",
     "pid": "tex-p6"
    },
    {
     "rank": 76,
     "name": "Olivia Benton",
     "school": "Boston College",
     "teamId": "bc-w",
     "pid": "bc-w-p2"
    },
    {
     "rank": 77,
     "name": "Jantje Tilbuerger",
     "school": "University Of Central Florida",
     "teamId": "ucf-w",
     "pid": "ucf-w-p9"
    },
    {
     "rank": 78,
     "name": "Merna Refaat",
     "school": "Auburn",
     "teamId": "aub-w",
     "pid": "aub-p10"
    },
    {
     "rank": 79,
     "name": "Nina Vargova",
     "school": "Duke",
     "teamId": "duke-w",
     "pid": "duke-w-n1"
    },
    {
     "rank": 80,
     "name": "Linea Bajraliu",
     "school": "University Of Georgia",
     "teamId": "uga-w",
     "pid": "uga-w-n3"
    },
    {
     "rank": 81,
     "name": "Mimi Xu",
     "school": "Duke",
     "teamId": "duke-w",
     "pid": "duke-w-n2"
    },
    {
     "rank": 82,
     "name": "Brooke Black",
     "school": "University Of Florida",
     "teamId": "fla-w",
     "pid": "fla-p1"
    },
    {
     "rank": 83,
     "name": "Duru Soke",
     "school": "Pepperdine",
     "teamId": "pepp-w",
     "pid": "pepp-w-p5"
    },
    {
     "rank": 84,
     "name": "Reina Goto",
     "school": "University of Oklahoma",
     "teamId": "ou-w",
     "pid": "ou-w-n3"
    },
    {
     "rank": 85,
     "name": "Alexis Nguyen",
     "school": "UNC Chapel Hill",
     "teamId": "unc-w",
     "pid": "unc-w-n1"
    },
    {
     "rank": 86,
     "name": "Carolina Kuhl",
     "school": "Louisiana State University",
     "teamId": "lsu-w",
     "pid": "lsu-p5"
    },
    {
     "rank": 87,
     "name": "Alexis Blokhina",
     "school": "Stanford",
     "teamId": "stan-w",
     "pid": "stan-w-p7"
    },
    {
     "rank": 88,
     "name": "Lucia Peyre",
     "school": "Oklahoma State University",
     "teamId": "okst-w",
     "pid": "okst-w-p6"
    },
    {
     "rank": 89,
     "name": "Krisha Mahendran",
     "school": "Southern California",
     "teamId": null,
     "pid": null
    },
    {
     "rank": 90,
     "name": "Aishi Das",
     "school": "Auburn",
     "teamId": "aub-w",
     "pid": "aub-p3"
    },
    {
     "rank": 91,
     "name": "Chloe Noel",
     "school": "University of Oklahoma",
     "teamId": "ou-w",
     "pid": "ou-p7"
    },
    {
     "rank": 92,
     "name": "Yara Bartashevich",
     "school": "Auburn",
     "teamId": "aub-w",
     "pid": "aub-p1"
    },
    {
     "rank": 93,
     "name": "Divna Ratkovic",
     "school": "Rice",
     "teamId": "rice-w",
     "pid": "rice-w-p8"
    },
    {
     "rank": 94,
     "name": "Joanna Kennedy",
     "school": "Florida State",
     "teamId": "fsu-w",
     "pid": "fsu-w-p6"
    },
    {
     "rank": 95,
     "name": "Nicole Khirin",
     "school": "UNC Chapel Hill",
     "teamId": "unc-w",
     "pid": "unc-w-n3"
    },
    {
     "rank": 96,
     "name": "Emma Ghirardato",
     "school": "University of Maryland, College Park",
     "teamId": "umd-w",
     "pid": "umd-w-p5"
    },
    {
     "rank": 97,
     "name": "Maya Iyengar",
     "school": "Auburn",
     "teamId": "aub-w",
     "pid": "aub-w-n1"
    },
    {
     "rank": 98,
     "name": "Allegra Korpanec Davies",
     "school": "University Of Florida",
     "teamId": "fla-w",
     "pid": "fla-w-n2"
    },
    {
     "rank": 99,
     "name": "Valerie Shue",
     "school": "Texas Tech",
     "teamId": "ttu-w",
     "pid": "ttu-w-p7"
    },
    {
     "rank": 100,
     "name": "Melisa Ercan",
     "school": "Tulsa",
     "teamId": "tulsa-w",
     "pid": null
    },
    {
     "rank": 101,
     "name": "Aya El Aouni",
     "school": "Louisiana State University",
     "teamId": "lsu-w",
     "pid": "lsu-w-n2"
    },
    {
     "rank": 102,
     "name": "Kate Fakih",
     "school": "UCLA",
     "teamId": "ucla-w",
     "pid": "ucla-w-p9"
    },
    {
     "rank": 103,
     "name": "Alian Zack",
     "school": "Baylor University",
     "teamId": "bay-w",
     "pid": "bay-w-p8"
    },
    {
     "rank": 104,
     "name": "Christasha McNeil",
     "school": "University of Texas at Austin",
     "teamId": "tex-w",
     "pid": "tex-p8"
    },
    {
     "rank": 105,
     "name": "Ekaterina Maklakova",
     "school": "University of Oklahoma",
     "teamId": "ou-w",
     "pid": "ou-w-n2"
    },
    {
     "rank": 106,
     "name": "Artemis Aslanisvili",
     "school": "Vanderbilt",
     "teamId": "van-w",
     "pid": "van-w-n1"
    },
    {
     "rank": 107,
     "name": "Leonie Moeller",
     "school": "Memphis",
     "teamId": "mem-w",
     "pid": "mem-w-p5"
    },
    {
     "rank": 108,
     "name": "Zoie Epps",
     "school": "University of Oklahoma",
     "teamId": "ou-w",
     "pid": "ou-w-n1"
    },
    {
     "rank": 109,
     "name": "Salakthip Ounmang",
     "school": "University of Oklahoma",
     "teamId": "ou-w",
     "pid": null
    },
    {
     "rank": 110,
     "name": "Peyton Capuano",
     "school": "Dartmouth College",
     "teamId": "dart-w",
     "pid": "dart-w-p1"
    },
    {
     "rank": 111,
     "name": "Arianna Zucchini",
     "school": "University of Texas at Austin",
     "teamId": "tex-w",
     "pid": "tex-w-n2"
    },
    {
     "rank": 112,
     "name": "Shannon Lam",
     "school": "University of Virginia",
     "teamId": "uva-w",
     "pid": "uva-w-p5"
    },
    {
     "rank": 113,
     "name": "Ranah Akua Stoiber",
     "school": "University Of Georgia",
     "teamId": "uga-w",
     "pid": "uga-w-n5"
    },
    {
     "rank": 114,
     "name": "Gloriana Nahum",
     "school": "University of Oklahoma",
     "teamId": "ou-w",
     "pid": "ou-p6"
    },
    {
     "rank": 115,
     "name": "Audrey Spencer",
     "school": "Ohio State",
     "teamId": "osu-w",
     "pid": "osu-w-p10"
    },
    {
     "rank": 116,
     "name": "Olivia Traynor",
     "school": "University of Michigan",
     "teamId": "mich-w",
     "pid": "mich-w-n2"
    },
    {
     "rank": 117,
     "name": "Xin Tong Wang",
     "school": "Wichita State",
     "teamId": "wich-w",
     "pid": "wich-w-p8"
    },
    {
     "rank": 118,
     "name": "Vilma Krebs Hyllested",
     "school": "University of San Diego",
     "teamId": "usd-w",
     "pid": "usd-w-p3"
    },
    {
     "rank": 119,
     "name": "Tianmei Wang",
     "school": "Stanford",
     "teamId": "stan-w",
     "pid": "stan-w-p6"
    },
    {
     "rank": 120,
     "name": "Daniela Piani",
     "school": "University of South Carolina, Columbia",
     "teamId": "sc-w",
     "pid": "sc-p9"
    },
    {
     "rank": 121,
     "name": "Sankavi Gownder",
     "school": "Wake Forest",
     "teamId": "wake-w",
     "pid": "wake-w-p4"
    },
    {
     "rank": 122,
     "name": "Ruby Cooling",
     "school": "Texas A&M University",
     "teamId": "tamu-w",
     "pid": "tamu-w-n3"
    },
    {
     "rank": 123,
     "name": "Katerina Shabashkevich",
     "school": "Stanford",
     "teamId": "stan-w",
     "pid": "stan-w-p9"
    },
    {
     "rank": 124,
     "name": "Veronika Kliuch",
     "school": "Oklahoma State University",
     "teamId": "okst-w",
     "pid": "okst-w-p4"
    },
    {
     "rank": 125,
     "name": "Isabella Kruger",
     "school": "Auburn",
     "teamId": "aub-w",
     "pid": "aub-p7"
    }
   ]
  },
  "men": {
   "listId": "2026-27_d1_men_singles_p2_v2",
   "listDate": "2026-08-25",
   "rows": [
    {
     "rank": 1,
     "name": "Dylan Dietrich",
     "school": "University of Virginia",
     "teamId": "uva-m",
     "pid": "uva-m-p2"
    },
    {
     "rank": 2,
     "name": "Paul Inchauspe",
     "school": "Princeton",
     "teamId": "prin-m",
     "pid": "prin-m-p3"
    },
    {
     "rank": 3,
     "name": "Duncan Chan",
     "school": "TCU",
     "teamId": "tcu-m",
     "pid": "tcu-m-p3"
    },
    {
     "rank": 4,
     "name": "Max Dahlin",
     "school": "University of Michigan",
     "teamId": "mich-m",
     "pid": "mich-m-p6"
    },
    {
     "rank": 5,
     "name": "Devin Badenhorst",
     "school": "Baylor University",
     "teamId": "bay-m",
     "pid": "bay-m-p1"
    },
    {
     "rank": 6,
     "name": "Keegan Rice",
     "school": "University of Virginia",
     "teamId": "uva-m",
     "pid": "uva-m-p8"
    },
    {
     "rank": 7,
     "name": "Aidan Kim",
     "school": "Ohio State",
     "teamId": "osu-m",
     "pid": "osu-m-p5"
    },
    {
     "rank": 8,
     "name": "Theo Papamalamis",
     "school": "Texas A&M University",
     "teamId": "tamu-m",
     "pid": "tamu-m-p4"
    },
    {
     "rank": 9,
     "name": "Gabriel Debru",
     "school": "University of Texas at Austin",
     "teamId": "tex-m",
     "pid": "tex-m-n1"
    },
    {
     "rank": 10,
     "name": "Matthew Forbes",
     "school": "Ohio State",
     "teamId": "osu-m",
     "pid": "osu-m-p3"
    },
    {
     "rank": 11,
     "name": "Jakub Vrba",
     "school": "University Of Arkansas, Fayetteville",
     "teamId": "ark-m",
     "pid": "ark-m-p6"
    },
    {
     "rank": 12,
     "name": "Preston Stearns",
     "school": "Ohio State",
     "teamId": "osu-m",
     "pid": "osu-m-p11"
    },
    {
     "rank": 13,
     "name": "Mees Rottgering",
     "school": "Wake Forest",
     "teamId": "wake-m",
     "pid": "wake-m-p5"
    },
    {
     "rank": 14,
     "name": "Eli Stephenson",
     "school": "University of Kentucky",
     "teamId": "uk-m",
     "pid": "uk-m-p7"
    },
    {
     "rank": 15,
     "name": "Amirkhamza Nasridinov",
     "school": "Texas A&M University",
     "teamId": "tamu-m",
     "pid": "tamu-m-n6"
    },
    {
     "rank": 16,
     "name": "Rodrigo Fernandes",
     "school": "Cornell",
     "teamId": "corn-m",
     "pid": "corn-m-p3"
    },
    {
     "rank": 17,
     "name": "Erik Arutiunian",
     "school": "Louisiana State University",
     "teamId": "lsu-m",
     "pid": "lsu-m-p2"
    },
    {
     "rank": 18,
     "name": "Olaf Pieczkowski",
     "school": "Louisiana State University",
     "teamId": "lsu-m",
     "pid": "lsu-m-p1"
    },
    {
     "rank": 19,
     "name": "Luca Pow",
     "school": "Wake Forest",
     "teamId": "wake-m",
     "pid": "wake-m-p4"
    },
    {
     "rank": 20,
     "name": "Sebastian Eriksson",
     "school": "University of Texas at Austin",
     "teamId": "tex-m",
     "pid": "tex-m-p6"
    },
    {
     "rank": 21,
     "name": "Cooper Woestendick",
     "school": "TCU",
     "teamId": "tcu-m",
     "pid": "tcu-m-p9"
    },
    {
     "rank": 22,
     "name": "Emon van Loben Sels",
     "school": "UCLA",
     "teamId": "ucla-m",
     "pid": "ucla-m-p8"
    },
    {
     "rank": 23,
     "name": "Alexander Razeghi",
     "school": "Stanford",
     "teamId": "stan-m",
     "pid": "stan-m-fp53"
    },
    {
     "rank": 24,
     "name": "Viktor Markov",
     "school": "Clemson",
     "teamId": "clem-m",
     "pid": "clem-m-p5"
    },
    {
     "rank": 25,
     "name": "Rohan Murali",
     "school": "Harvard",
     "teamId": "harv-m",
     "pid": "harv-m-p9"
    },
    {
     "rank": 26,
     "name": "Romain Gales",
     "school": "Clemson",
     "teamId": "clem-m",
     "pid": "clem-m-p4"
    },
    {
     "rank": 27,
     "name": "Alex Okonkwo",
     "school": "Ohio State",
     "teamId": "osu-m",
     "pid": "osu-m-p8"
    },
    {
     "rank": 28,
     "name": "Connor Henry Van Schalkwyk",
     "school": "Baylor University",
     "teamId": "bay-m",
     "pid": "bay-m-fp67"
    },
    {
     "rank": 29,
     "name": "Spencer Johnson",
     "school": "UCLA",
     "teamId": "ucla-m",
     "pid": "ucla-m-p10"
    },
    {
     "rank": 30,
     "name": "Nicolas Arseneault",
     "school": "University of Kentucky",
     "teamId": "uk-m",
     "pid": "uk-m-p2"
    },
    {
     "rank": 31,
     "name": "Cooper Williams",
     "school": "Duke",
     "teamId": "duke-m",
     "pid": "duke-m-p8"
    },
    {
     "rank": 32,
     "name": "Andres Santamarta Roig",
     "school": "University of Virginia",
     "teamId": "uva-m",
     "pid": "uva-m-p9"
    },
    {
     "rank": 33,
     "name": "Jangjun Kim",
     "school": "University of Virginia",
     "teamId": "uva-m",
     "pid": "uva-m-p5"
    },
    {
     "rank": 34,
     "name": "Paul Barbier Gazeu",
     "school": "University of South Carolina, Columbia",
     "teamId": "sc-m",
     "pid": "sc-m-p3"
    },
    {
     "rank": 35,
     "name": "Petro Kuzmenok",
     "school": "Rice",
     "teamId": "rice-m",
     "pid": "rice-m-p4"
    },
    {
     "rank": 36,
     "name": "Oscar Lacides",
     "school": "University Of Tennessee, Knoxville",
     "teamId": "tenn-m",
     "pid": "tenn-m-n6"
    },
    {
     "rank": 37,
     "name": "Sasha Rozin",
     "school": "University Of Arizona",
     "teamId": "ariz-m",
     "pid": "ariz-m-fp225"
    },
    {
     "rank": 38,
     "name": "Fryderyk Lechno Wasiutynski",
     "school": "University Of California, Berkeley",
     "teamId": "cal-m",
     "pid": "cal-m-fp2"
    },
    {
     "rank": 39,
     "name": "Henry Jefferson",
     "school": "University Of Florida",
     "teamId": "fla-m",
     "pid": "fla-m-p5"
    },
    {
     "rank": 40,
     "name": "Nathan Trouve",
     "school": "Southern California",
     "teamId": null,
     "pid": null
    },
    {
     "rank": 41,
     "name": "Sean Daryabeigi",
     "school": "University of South Carolina, Columbia",
     "teamId": "sc-m",
     "pid": "sc-m-p4"
    },
    {
     "rank": 42,
     "name": "Orel Kimhi",
     "school": "University Of Tennessee, Knoxville",
     "teamId": "tenn-m",
     "pid": "tenn-m-n5"
    },
    {
     "rank": 43,
     "name": "Oliver Ojakaar",
     "school": "University of Texas at Austin",
     "teamId": "tex-m",
     "pid": "tex-m-p11"
    },
    {
     "rank": 44,
     "name": "Nathan Blokhin",
     "school": "Harvard",
     "teamId": "harv-m",
     "pid": "harv-m-p1"
    },
    {
     "rank": 45,
     "name": "Filip Gustafsson",
     "school": "University Of Arizona",
     "teamId": "ariz-m",
     "pid": "ariz-m-fp228"
    },
    {
     "rank": 46,
     "name": "Bor Artnak",
     "school": "Texas A&M University",
     "teamId": "tamu-m",
     "pid": "tamu-m-n4"
    },
    {
     "rank": 47,
     "name": "Maxwell Exsted",
     "school": "Southern California",
     "teamId": null,
     "pid": null
    },
    {
     "rank": 48,
     "name": "Pablo Martinez Gomez",
     "school": "Vanderbilt",
     "teamId": "van-m",
     "pid": "van-m-p5"
    },
    {
     "rank": 49,
     "name": "Rudy Quan",
     "school": "UCLA",
     "teamId": "ucla-m",
     "pid": "ucla-m-p4"
    },
    {
     "rank": 50,
     "name": "Matic Kriznik",
     "school": "University Of Alabama",
     "teamId": "ala-m",
     "pid": "ala-m-p6"
    },
    {
     "rank": 51,
     "name": "Nikita Filin",
     "school": "Ohio State",
     "teamId": "osu-m",
     "pid": "osu-m-p2"
    },
    {
     "rank": 52,
     "name": "Niccolo Baroni",
     "school": "Ole Miss",
     "teamId": "miss-m",
     "pid": "miss-m-n1"
    },
    {
     "rank": 53,
     "name": "Jack Loutit",
     "school": "University of Kentucky",
     "teamId": "uk-m",
     "pid": "uk-m-p5"
    },
    {
     "rank": 54,
     "name": "Vit Kalina",
     "school": "University Of Alabama",
     "teamId": "ala-m",
     "pid": "ala-m-p5"
    },
    {
     "rank": 55,
     "name": "Sam Landau",
     "school": "Indiana University",
     "teamId": "ind-m",
     "pid": "ind-m-p6"
    },
    {
     "rank": 56,
     "name": "Hudson Rivera",
     "school": "Stanford",
     "teamId": "stan-m",
     "pid": "stan-m-p3"
    },
    {
     "rank": 57,
     "name": "Alexander Frusina",
     "school": "Texas A&M University",
     "teamId": "tamu-m",
     "pid": "tamu-m-n1"
    },
    {
     "rank": 58,
     "name": "Bryce Nakashima",
     "school": "Ohio State",
     "teamId": "osu-m",
     "pid": "osu-m-p7"
    },
    {
     "rank": 59,
     "name": "Timofey Stepanov",
     "school": "University Of California, Berkeley",
     "teamId": "cal-m",
     "pid": "cal-m-p11"
    },
    {
     "rank": 60,
     "name": "Manvydas Balciunas",
     "school": "University of San Diego",
     "teamId": "usd-m",
     "pid": "usd-m-p1"
    },
    {
     "rank": 61,
     "name": "Bryan Hernandez Cortes",
     "school": "Mississippi State",
     "teamId": "msst-m",
     "pid": "msst-m-p3"
    },
    {
     "rank": 62,
     "name": "Johan Alexander Rodriguez Rodriguez",
     "school": "University of Oklahoma",
     "teamId": "ou-m",
     "pid": null
    },
    {
     "rank": 63,
     "name": "Nour Fathalla",
     "school": "Purdue",
     "teamId": "pur-m",
     "pid": "pur-m-p6"
    },
    {
     "rank": 64,
     "name": "Andrej Loncarevic",
     "school": "Louisiana State University",
     "teamId": "lsu-m",
     "pid": "lsu-m-p7"
    },
    {
     "rank": 65,
     "name": "Hoyoung Roh",
     "school": "Vanderbilt",
     "teamId": "van-m",
     "pid": "van-m-p8"
    },
    {
     "rank": 66,
     "name": "Jules Leroux",
     "school": "NC State",
     "teamId": "ncst-m",
     "pid": "ncst-m-p3"
    },
    {
     "rank": 67,
     "name": "Zoran Ludoski",
     "school": "University Of Arizona",
     "teamId": "ariz-m",
     "pid": "ariz-m-fp224"
    },
    {
     "rank": 68,
     "name": "Andrii Zimnokh",
     "school": "University Of Alabama",
     "teamId": "ala-m",
     "pid": "ala-m-p10"
    },
    {
     "rank": 69,
     "name": "Lasse Poertner",
     "school": "Pepperdine",
     "teamId": "pepp-m",
     "pid": "pepp-m-p4"
    },
    {
     "rank": 70,
     "name": "Abel Forger",
     "school": "University of Texas at Austin",
     "teamId": "tex-m",
     "pid": "tex-m-p7"
    },
    {
     "rank": 71,
     "name": "Aryan Shah",
     "school": "Wake Forest",
     "teamId": "wake-m",
     "pid": "wake-m-p6"
    },
    {
     "rank": 72,
     "name": "Aleksa Pisaric",
     "school": "Pepperdine",
     "teamId": "pepp-m",
     "pid": "pepp-m-p3"
    },
    {
     "rank": 73,
     "name": "Joaquin Guilleme",
     "school": "Wake Forest",
     "teamId": "wake-m",
     "pid": "wake-m-p1"
    },
    {
     "rank": 74,
     "name": "Zaid Mashni",
     "school": "University of Pennsylvania",
     "teamId": "penn-m",
     "pid": "penn-m-n2"
    },
    {
     "rank": 75,
     "name": "Azariah Rusher",
     "school": "Florida State",
     "teamId": "fsu-m",
     "pid": "fsu-m-p6"
    },
    {
     "rank": 76,
     "name": "Peter Benjamin Privara",
     "school": "Harvard",
     "teamId": "harv-m",
     "pid": "harv-m-fp291"
    },
    {
     "rank": 77,
     "name": "William Manning",
     "school": "NC State",
     "teamId": "ncst-m",
     "pid": "ncst-m-p4"
    },
    {
     "rank": 78,
     "name": "Luca Preda",
     "school": "University of Virginia",
     "teamId": "uva-m",
     "pid": "uva-m-p6"
    },
    {
     "rank": 79,
     "name": "Edward Winter",
     "school": "Pepperdine",
     "teamId": "pepp-m",
     "pid": "pepp-m-p6"
    },
    {
     "rank": 80,
     "name": "Roger Pascual Ferra",
     "school": "TCU",
     "teamId": "tcu-m",
     "pid": "tcu-m-fp30"
    },
    {
     "rank": 81,
     "name": "Luciano Emanuel Ambrogi",
     "school": "University of Oklahoma",
     "teamId": "ou-m",
     "pid": "ou-m-n4"
    },
    {
     "rank": 82,
     "name": "Daniil Ostapenkov",
     "school": "Louisiana State University",
     "teamId": "lsu-m",
     "pid": "lsu-m-n1"
    },
    {
     "rank": 83,
     "name": "Jamie Mackenzie",
     "school": "TCU",
     "teamId": "tcu-m",
     "pid": "tcu-m-p5"
    },
    {
     "rank": 84,
     "name": "Oliver Bonding",
     "school": "TCU",
     "teamId": "tcu-m",
     "pid": "tcu-m-p1"
    },
    {
     "rank": 85,
     "name": "Toby Kodat",
     "school": "NC State",
     "teamId": "ncst-m",
     "pid": "ncst-m-n1"
    },
    {
     "rank": 86,
     "name": "Kyle Kang",
     "school": "Stanford",
     "teamId": "stan-m",
     "pid": "stan-m-p2"
    },
    {
     "rank": 87,
     "name": "Bruno Kuzuhara",
     "school": "Clemson",
     "teamId": "clem-m",
     "pid": "clem-m-p9"
    },
    {
     "rank": 88,
     "name": "Tomasz Berkieta",
     "school": "University of Texas at Austin",
     "teamId": "tex-m",
     "pid": "tex-m-n2"
    },
    {
     "rank": 89,
     "name": "Noa Vukadin",
     "school": "Clemson",
     "teamId": "clem-m",
     "pid": "clem-m-p7"
    },
    {
     "rank": 90,
     "name": "Yannick Theodor Alexandrescou",
     "school": "Duke",
     "teamId": "duke-m",
     "pid": null
    },
    {
     "rank": 91,
     "name": "Igor Kudriashov",
     "school": "Ole Miss",
     "teamId": "miss-m",
     "pid": "miss-m-n3"
    },
    {
     "rank": 92,
     "name": "Simeon Stankovic",
     "school": "Princeton",
     "teamId": "prin-m",
     "pid": null
    },
    {
     "rank": 93,
     "name": "Albert Pedrico Kravtsov",
     "school": "TCU",
     "teamId": "tcu-m",
     "pid": "tcu-m-fp28"
    },
    {
     "rank": 94,
     "name": "Erik Schiessl",
     "school": "Baylor University",
     "teamId": "bay-m",
     "pid": "bay-m-p9"
    },
    {
     "rank": 95,
     "name": "Raphael Vaksmann",
     "school": "Mississippi State",
     "teamId": "msst-m",
     "pid": "msst-m-p9"
    },
    {
     "rank": 96,
     "name": "Denis Petak",
     "school": "Ohio State",
     "teamId": "osu-m",
     "pid": "osu-m-p10"
    },
    {
     "rank": 97,
     "name": "Lucas Marionneau",
     "school": "University of Texas at Austin",
     "teamId": "tex-m",
     "pid": "tex-m-p10"
    },
    {
     "rank": 98,
     "name": "Vincent Marysko",
     "school": "University of San Diego",
     "teamId": "usd-m",
     "pid": "usd-m-p5"
    },
    {
     "rank": 99,
     "name": "Michael Bassem Sobhy",
     "school": "Louisiana State University",
     "teamId": "lsu-m",
     "pid": "lsu-m-n2"
    },
    {
     "rank": 100,
     "name": "Cezar Gabriel Papoe",
     "school": "Cornell",
     "teamId": "corn-m",
     "pid": "corn-m-n2"
    },
    {
     "rank": 101,
     "name": "Julian Alonso",
     "school": "University Of Georgia",
     "teamId": "uga-m",
     "pid": "uga-m-n1"
    },
    {
     "rank": 102,
     "name": "Enzo Kohlmann",
     "school": "Louisiana State University",
     "teamId": "lsu-m",
     "pid": null
    },
    {
     "rank": 103,
     "name": "Clement Lemire",
     "school": "University Of Central Florida",
     "teamId": "ucf-m",
     "pid": "ucf-m-p5"
    },
    {
     "rank": 104,
     "name": "Dominick Mosejczuk",
     "school": "Wake Forest",
     "teamId": "wake-m",
     "pid": "wake-m-p3"
    },
    {
     "rank": 105,
     "name": "Charlie Robertson",
     "school": "University of South Carolina, Columbia",
     "teamId": "sc-m",
     "pid": "sc-m-n1"
    },
    {
     "rank": 106,
     "name": "Andrin Casanova",
     "school": "Southern California",
     "teamId": null,
     "pid": null
    },
    {
     "rank": 107,
     "name": "Gustavo Ribeiro de Almeida",
     "school": "Pepperdine",
     "teamId": "pepp-m",
     "pid": "pepp-m-p5"
    },
    {
     "rank": 108,
     "name": "Nicolas Oliveira",
     "school": "University Of Central Florida",
     "teamId": "ucf-m",
     "pid": "ucf-m-p7"
    },
    {
     "rank": 109,
     "name": "Ilyas Fahim",
     "school": "Virginia Tech",
     "teamId": "vt-m",
     "pid": "vt-m-p1"
    },
    {
     "rank": 110,
     "name": "Mikael Arseneault",
     "school": "University of Kentucky",
     "teamId": "uk-m",
     "pid": "uk-m-p1"
    },
    {
     "rank": 111,
     "name": "Maximus Dussault",
     "school": "TCU",
     "teamId": "tcu-m",
     "pid": "tcu-m-p4"
    },
    {
     "rank": 112,
     "name": "Kacper Szymkowiak",
     "school": "Wake Forest",
     "teamId": "wake-m",
     "pid": "wake-m-p8"
    },
    {
     "rank": 113,
     "name": "Duje Markovina",
     "school": "Auburn",
     "teamId": "aub-m",
     "pid": "aub-m-n3"
    },
    {
     "rank": 114,
     "name": "Jeremy Jin",
     "school": "University Of Florida",
     "teamId": "fla-m",
     "pid": "fla-m-p6"
    },
    {
     "rank": 115,
     "name": "Daniel Uta",
     "school": "University of Oklahoma",
     "teamId": "ou-m",
     "pid": "ou-m-n3"
    },
    {
     "rank": 116,
     "name": "Johan Oscar Lien",
     "school": "University of Kentucky",
     "teamId": "uk-m",
     "pid": "uk-m-n4"
    },
    {
     "rank": 117,
     "name": "Matisse Farzam",
     "school": "Clemson",
     "teamId": "clem-m",
     "pid": "clem-m-p3"
    },
    {
     "rank": 118,
     "name": "Alaa Trifi",
     "school": "University Of Florida",
     "teamId": "fla-m",
     "pid": "fla-m-n1"
    },
    {
     "rank": 119,
     "name": "Jonas Kucera",
     "school": "University of Notre Dame",
     "teamId": "nd-m",
     "pid": "nd-m-p1"
    },
    {
     "rank": 120,
     "name": "Bernardo Munk Mesa",
     "school": "University Of California, Berkeley",
     "teamId": "cal-m",
     "pid": "cal-m-p9"
    },
    {
     "rank": 121,
     "name": "Asahi Harazaki",
     "school": "University of Oklahoma",
     "teamId": "ou-m",
     "pid": "ou-m-p2"
    },
    {
     "rank": 122,
     "name": "Georgi Georgiev",
     "school": "SMU",
     "teamId": "smu-m",
     "pid": "smu-m-p6"
    },
    {
     "rank": 123,
     "name": "Niels Ratiu",
     "school": "UNC Chapel Hill",
     "teamId": "unc-m",
     "pid": "unc-m-p7"
    },
    {
     "rank": 124,
     "name": "Victor Lilov",
     "school": "Ohio State",
     "teamId": "osu-m",
     "pid": "osu-m-p6"
    },
    {
     "rank": 125,
     "name": "Wissam Abderrahman",
     "school": "University Of Central Florida",
     "teamId": "ucf-m",
     "pid": "ucf-m-p1"
    }
   ]
  }
 },
 "doubles": {
  "men": {
   "listId": "2026-27_d1_men_doubles_p1_v3",
   "listDate": "2026-08-25",
   "rows": [
    {
     "rank": 1,
     "names": [
      "Michael Bassem Sobhy",
      "Daniil Ostapenkov"
     ],
     "school": "Louisiana State University",
     "teamId": "lsu-m",
     "pids": [
      "lsu-m-n2",
      "lsu-m-n1"
     ]
    },
    {
     "rank": 2,
     "names": [
      "Luciano Emanuel Ambrogi",
      "Johan Alexander Rodriguez Rodriguez"
     ],
     "school": "University of Oklahoma",
     "teamId": "ou-m",
     "pids": [
      "ou-m-n4",
      null
     ]
    },
    {
     "rank": 3,
     "names": [
      "Nikita Filin",
      "Brandon Carpico"
     ],
     "school": "Ohio State",
     "teamId": "osu-m",
     "pids": [
      "osu-m-p2",
      "osu-m-p1"
     ]
    },
    {
     "rank": 4,
     "names": [
      "Mees Rottgering",
      "Kacper Szymkowiak"
     ],
     "school": "Wake Forest",
     "teamId": "wake-m",
     "pids": [
      "wake-m-p5",
      "wake-m-p8"
     ]
    },
    {
     "rank": 5,
     "names": [
      "Oliver Ojakaar",
      "Tomasz Berkieta"
     ],
     "school": "University of Texas at Austin",
     "teamId": "tex-m",
     "pids": [
      "tex-m-p11",
      "tex-m-n2"
     ]
    },
    {
     "rank": 6,
     "names": [
      "Cooper Woestendick",
      "Albert Pedrico Kravtsov"
     ],
     "school": "TCU",
     "teamId": "tcu-m",
     "pids": [
      "tcu-m-p9",
      "tcu-m-fp28"
     ]
    },
    {
     "rank": 7,
     "names": [
      "Romain Gales",
      "Bruno Kuzuhara"
     ],
     "school": "Clemson",
     "teamId": "clem-m",
     "pids": [
      "clem-m-p4",
      "clem-m-p9"
     ]
    },
    {
     "rank": 8,
     "names": [
      "Luca Pow",
      "Aryan Shah"
     ],
     "school": "Wake Forest",
     "teamId": "wake-m",
     "pids": [
      "wake-m-p4",
      "wake-m-p6"
     ]
    },
    {
     "rank": 9,
     "names": [
      "Mikael Arseneault",
      "Nicolas Arseneault"
     ],
     "school": "University of Kentucky",
     "teamId": "uk-m",
     "pids": [
      "uk-m-p1",
      "uk-m-p2"
     ]
    },
    {
     "rank": 10,
     "names": [
      "Alexander Razeghi",
      "Nathan Barki"
     ],
     "school": "Stanford",
     "teamId": "stan-m",
     "pids": [
      "stan-m-fp53",
      "stan-m-p5"
     ]
    },
    {
     "rank": 11,
     "names": [
      "Lucas Marionneau",
      "Gabriel Debru"
     ],
     "school": "University of Texas at Austin",
     "teamId": "tex-m",
     "pids": [
      "tex-m-p10",
      "tex-m-n1"
     ]
    },
    {
     "rank": 12,
     "names": [
      "Paul Barbier Gazeu",
      "Charlie Robertson"
     ],
     "school": "University of South Carolina, Columbia",
     "teamId": "sc-m",
     "pids": [
      "sc-m-p3",
      "sc-m-n1"
     ]
    },
    {
     "rank": 13,
     "names": [
      "Spencer Johnson",
      "Emon van Loben Sels"
     ],
     "school": "UCLA",
     "teamId": "ucla-m",
     "pids": [
      "ucla-m-p10",
      "ucla-m-p8"
     ]
    },
    {
     "rank": 14,
     "names": [
      "Connor Henry Van Schalkwyk",
      "Erik Schiessl"
     ],
     "school": "Baylor University",
     "teamId": "bay-m",
     "pids": [
      "bay-m-fp67",
      "bay-m-p9"
     ]
    },
    {
     "rank": 15,
     "names": [
      "Aidan Kim",
      "Bryce Nakashima"
     ],
     "school": "Ohio State",
     "teamId": "osu-m",
     "pids": [
      "osu-m-p5",
      "osu-m-p7"
     ]
    },
    {
     "rank": 16,
     "names": [
      "Oscar Lacides",
      "Orel Kimhi"
     ],
     "school": "University Of Tennessee, Knoxville",
     "teamId": "tenn-m",
     "pids": [
      "tenn-m-n6",
      "tenn-m-n5"
     ]
    },
    {
     "rank": 17,
     "names": [
      "Jack Loutit",
      "Eli Stephenson"
     ],
     "school": "University of Kentucky",
     "teamId": "uk-m",
     "pids": [
      "uk-m-p5",
      "uk-m-p7"
     ]
    },
    {
     "rank": 18,
     "names": [
      "Toby Kodat",
      "Charlie Camus"
     ],
     "school": "NC State",
     "teamId": "ncst-m",
     "pids": [
      "ncst-m-n1",
      "ncst-m-p2"
     ]
    },
    {
     "rank": 19,
     "names": [
      "Aleksa Pisaric",
      "Lasse Poertner"
     ],
     "school": "Pepperdine",
     "teamId": "pepp-m",
     "pids": [
      "pepp-m-p3",
      "pepp-m-p4"
     ]
    },
    {
     "rank": 20,
     "names": [
      "Abel Forger",
      "Mariano Dedura-Palomero"
     ],
     "school": "University of Texas at Austin",
     "teamId": "tex-m",
     "pids": [
      "tex-m-p7",
      "tex-m-p5"
     ]
    },
    {
     "rank": 21,
     "names": [
      "Nicholas Godsick",
      "Hudson Rivera"
     ],
     "school": "Stanford",
     "teamId": "stan-m",
     "pids": [
      "stan-m-fp423",
      "stan-m-p3"
     ]
    },
    {
     "rank": 22,
     "names": [
      "Moritz Kudernatsch",
      "Pietro Pampanin"
     ],
     "school": "Ole Miss",
     "teamId": "miss-m",
     "pids": [
      "miss-m-n2",
      "miss-m-p7"
     ]
    },
    {
     "rank": 23,
     "names": [
      "Photos Photiades",
      "Gustavo Ribeiro de Almeida"
     ],
     "school": "Pepperdine",
     "teamId": "pepp-m",
     "pids": [
      "pepp-m-p2",
      "pepp-m-p5"
     ]
    },
    {
     "rank": 24,
     "names": [
      "Andrew Delgado",
      "Noah Johnston"
     ],
     "school": "University Of Georgia",
     "teamId": "uga-m",
     "pids": [
      "uga-m-n2",
      "uga-m-p6"
     ]
    },
    {
     "rank": 25,
     "names": [
      "Erik Arutiunian",
      "Andrej Loncarevic"
     ],
     "school": "Louisiana State University",
     "teamId": "lsu-m",
     "pids": [
      "lsu-m-p2",
      "lsu-m-p7"
     ]
    },
    {
     "rank": 26,
     "names": [
      "Edward Winter",
      "David Fix"
     ],
     "school": "Pepperdine",
     "teamId": "pepp-m",
     "pids": [
      "pepp-m-p6",
      "pepp-m-p1"
     ]
    },
    {
     "rank": 27,
     "names": [
      "William Manning",
      "Jules Leroux"
     ],
     "school": "NC State",
     "teamId": "ncst-m",
     "pids": [
      "ncst-m-p4",
      "ncst-m-p3"
     ]
    },
    {
     "rank": 28,
     "names": [
      "Adrien Berrut",
      "Lambert Ruland"
     ],
     "school": "University of San Diego",
     "teamId": "usd-m",
     "pids": [
      "usd-m-p3",
      "usd-m-p7"
     ]
    },
    {
     "rank": 29,
     "names": [
      "Andres Santamarta Roig",
      "Jangjun Kim"
     ],
     "school": "University of Virginia",
     "teamId": "uva-m",
     "pids": [
      "uva-m-p9",
      "uva-m-p5"
     ]
    },
    {
     "rank": 30,
     "names": [
      "Pablo Martinez Gomez",
      "Hoyoung Roh"
     ],
     "school": "Vanderbilt",
     "teamId": "van-m",
     "pids": [
      "van-m-p5",
      "van-m-p8"
     ]
    },
    {
     "rank": 31,
     "names": [
      "Alexander Frusina",
      "Markus Molder"
     ],
     "school": "Texas A&M University",
     "teamId": "tamu-m",
     "pids": [
      "tamu-m-n1",
      "tamu-m-p9"
     ]
    },
    {
     "rank": 32,
     "names": [
      "Niels Ratiu",
      "Chris Xu"
     ],
     "school": "UNC Chapel Hill",
     "teamId": "unc-m",
     "pids": [
      "unc-m-p7",
      "unc-m-p10"
     ]
    },
    {
     "rank": 33,
     "names": [
      "Tyler Bowers",
      "Freddy Blaydes"
     ],
     "school": "Auburn",
     "teamId": "aub-m",
     "pids": [
      "aub-m-n1",
      "aub-m-p2"
     ]
    },
    {
     "rank": 34,
     "names": [
      "Max Dahlin",
      "Evan Burnett"
     ],
     "school": "University of Michigan",
     "teamId": "mich-m",
     "pids": [
      "mich-m-p6",
      "mich-m-p4"
     ]
    },
    {
     "rank": 35,
     "names": [
      "Duncan Chan",
      "Jamie Mackenzie"
     ],
     "school": "TCU",
     "teamId": "tcu-m",
     "pids": [
      "tcu-m-p3",
      "tcu-m-p5"
     ]
    },
    {
     "rank": 36,
     "names": [
      "Henrik Bladelius",
      "Marko Mesarovic"
     ],
     "school": "Clemson",
     "teamId": "clem-m",
     "pids": [
      "clem-m-p1",
      "clem-m-p6"
     ]
    },
    {
     "rank": 37,
     "names": [
      "Matthew Forbes",
      "Alex Okonkwo"
     ],
     "school": "Ohio State",
     "teamId": "osu-m",
     "pids": [
      "osu-m-p3",
      "osu-m-p8"
     ]
    },
    {
     "rank": 38,
     "names": [
      "Noa Vukadin",
      "Viktor Markov"
     ],
     "school": "Clemson",
     "teamId": "clem-m",
     "pids": [
      "clem-m-p7",
      "clem-m-p5"
     ]
    },
    {
     "rank": 39,
     "names": [
      "Paul Inchauspe",
      "Landon Ardila"
     ],
     "school": "Princeton",
     "teamId": "prin-m",
     "pids": [
      "prin-m-p3",
      "prin-m-p1"
     ]
    },
    {
     "rank": 40,
     "names": [
      "Asahi Harazaki",
      "Alejandro Melero"
     ],
     "school": "University of Oklahoma",
     "teamId": "ou-m",
     "pids": [
      "ou-m-p2",
      "ou-m-p3"
     ]
    },
    {
     "rank": 41,
     "names": [
      "Henry Jefferson",
      "Ty Host"
     ],
     "school": "University Of Florida",
     "teamId": "fla-m",
     "pids": [
      "fla-m-p5",
      "fla-m-n2"
     ]
    },
    {
     "rank": 42,
     "names": [
      "Jakub Vrba",
      "Ben Weintraub"
     ],
     "school": "University Of Arkansas, Fayetteville",
     "teamId": "ark-m",
     "pids": [
      "ark-m-p6",
      "ark-m-p3"
     ]
    },
    {
     "rank": 43,
     "names": [
      "David Bakonyi",
      "Zachary Viiala"
     ],
     "school": "University of Illinois at Urbana-Champaign",
     "teamId": "ill-m",
     "pids": [
      "ill-m-p1",
      "ill-m-fp219"
     ]
    },
    {
     "rank": 44,
     "names": [
      "Denis Petak",
      "Ilija Palavestra"
     ],
     "school": "Ohio State",
     "teamId": "osu-m",
     "pids": [
      "osu-m-p10",
      "osu-m-p9"
     ]
    },
    {
     "rank": 45,
     "names": [
      "Keegan Rice",
      "Luca Preda"
     ],
     "school": "University of Virginia",
     "teamId": "uva-m",
     "pids": [
      "uva-m-p8",
      "uva-m-p6"
     ]
    },
    {
     "rank": 46,
     "names": [
      "Vit Kalina",
      "Andrii Zimnokh"
     ],
     "school": "University Of Alabama",
     "teamId": "ala-m",
     "pids": [
      "ala-m-p5",
      "ala-m-p10"
     ]
    },
    {
     "rank": 47,
     "names": [
      "Nicolas Kobelt",
      "Sydney Zick"
     ],
     "school": "Oklahoma State University",
     "teamId": "okst-m",
     "pids": [
      "okst-m-p5",
      "okst-m-p10"
     ]
    },
    {
     "rank": 48,
     "names": [
      "Sasha Rozin",
      "Glib Sekachov"
     ],
     "school": "University Of Arizona",
     "teamId": "ariz-m",
     "pids": [
      "ariz-m-fp225",
      "ariz-m-fp222"
     ]
    },
    {
     "rank": 49,
     "names": [
      "Maxwell Exsted",
      "Nathan Trouve"
     ],
     "school": "Southern California",
     "teamId": null,
     "pids": [
      null,
      null
     ]
    },
    {
     "rank": 50,
     "names": [
      "Seydina Andre",
      "Filip Apltauer"
     ],
     "school": "Florida State",
     "teamId": "fsu-m",
     "pids": [
      "fsu-m-n2",
      null
     ]
    },
    {
     "rank": 51,
     "names": [
      "Alex Fuchs",
      "Preston Stearns"
     ],
     "school": "Ohio State",
     "teamId": "osu-m",
     "pids": [
      "osu-m-p4",
      "osu-m-p11"
     ]
    },
    {
     "rank": 52,
     "names": [
      "Sean Daryabeigi",
      "Max Stenzer"
     ],
     "school": "University of South Carolina, Columbia",
     "teamId": "sc-m",
     "pids": [
      "sc-m-p4",
      "sc-m-p7"
     ]
    },
    {
     "rank": 53,
     "names": [
      "Theo Papamalamis",
      "Lathan Skrobarcek"
     ],
     "school": "Texas A&M University",
     "teamId": "tamu-m",
     "pids": [
      "tamu-m-p4",
      "tamu-m-p11"
     ]
    },
    {
     "rank": 54,
     "names": [
      "Andrea Meduri",
      "Leonardo Cattaneo"
     ],
     "school": "University Of California, Berkeley",
     "teamId": "cal-m",
     "pids": [
      "cal-m-p8",
      "cal-m-p3"
     ]
    },
    {
     "rank": 55,
     "names": [
      "Wissam Abderrahman",
      "Mohammad Alkotop"
     ],
     "school": "University Of Central Florida",
     "teamId": "ucf-m",
     "pids": [
      "ucf-m-p1",
      "ucf-m-p2"
     ]
    },
    {
     "rank": 56,
     "names": [
      "Timofey Stepanov",
      "Alex Aney"
     ],
     "school": "University Of California, Berkeley",
     "teamId": "cal-m",
     "pids": [
      "cal-m-p11",
      "cal-m-p1"
     ]
    },
    {
     "rank": 57,
     "names": [
      "Rodrigo Fernandes",
      "Eric Verdes"
     ],
     "school": "Cornell",
     "teamId": "corn-m",
     "pids": [
      "corn-m-p3",
      "corn-m-p8"
     ]
    },
    {
     "rank": 58,
     "names": [
      "Igor Kudriashov",
      "Kai Milburn"
     ],
     "school": "Ole Miss",
     "teamId": "miss-m",
     "pids": [
      "miss-m-n3",
      "miss-m-p6"
     ]
    },
    {
     "rank": 59,
     "names": [
      "Luis Llorens Saracho",
      "Peter Nad"
     ],
     "school": "University of Notre Dame",
     "teamId": "nd-m",
     "pids": [
      "nd-m-p7",
      "nd-m-p6"
     ]
    },
    {
     "rank": 60,
     "names": [
      "Thomas Nicholas Gadecki",
      "Hank Trondson"
     ],
     "school": "Oklahoma State University",
     "teamId": "okst-m",
     "pids": [
      "okst-m-fp203",
      "okst-m-p9"
     ]
    },
    {
     "rank": 61,
     "names": [
      "Mikail Alimli",
      "Gabor Hornung"
     ],
     "school": "Florida State",
     "teamId": "fsu-m",
     "pids": [
      "fsu-m-n3",
      "fsu-m-p3"
     ]
    },
    {
     "rank": 62,
     "names": [
      "Julian Alonso",
      "Maxime Dubouch"
     ],
     "school": "University Of Georgia",
     "teamId": "uga-m",
     "pids": [
      "uga-m-n1",
      "uga-m-n3"
     ]
    },
    {
     "rank": 63,
     "names": [
      "Manvydas Balciunas",
      "Vincent Marysko"
     ],
     "school": "University of San Diego",
     "teamId": "usd-m",
     "pids": [
      "usd-m-p1",
      "usd-m-p5"
     ]
    },
    {
     "rank": 64,
     "names": [
      "Kevin Edengren",
      "Andreas Timini"
     ],
     "school": "University Of Florida",
     "teamId": "fla-m",
     "pids": [
      "fla-m-p3",
      "fla-m-p10"
     ]
    },
    {
     "rank": 65,
     "names": [
      "Jan Klimas",
      "Nikola Djosic"
     ],
     "school": "Arizona State",
     "teamId": "asu-m",
     "pids": [
      "asu-m-p6",
      "asu-m-p10"
     ]
    },
    {
     "rank": 66,
     "names": [
      "Khololwam Montsi",
      "Amirkhamza Nasridinov"
     ],
     "school": "Texas A&M University",
     "teamId": "tamu-m",
     "pids": [
      "tamu-m-n3",
      "tamu-m-n6"
     ]
    },
    {
     "rank": 67,
     "names": [
      "Rushil Khosla",
      "Rethin Pranav Senthil Kumar"
     ],
     "school": "Cornell",
     "teamId": "corn-m",
     "pids": [
      "corn-m-p5",
      "corn-m-p7"
     ]
    },
    {
     "rank": 68,
     "names": [
      "Haydar Cem Gokpinar",
      "Ian Bracks"
     ],
     "school": "Oklahoma State University",
     "teamId": "okst-m",
     "pids": [
      "okst-m-fp206",
      "okst-m-p1"
     ]
    },
    {
     "rank": 69,
     "names": [
      "Enzo Kohlmann",
      "Nikolas Stoot"
     ],
     "school": "Louisiana State University",
     "teamId": "lsu-m",
     "pids": [
      null,
      "lsu-m-n3"
     ]
    },
    {
     "rank": 70,
     "names": [
      "Oliver Bonding",
      "Maximus Dussault"
     ],
     "school": "TCU",
     "teamId": "tcu-m",
     "pids": [
      "tcu-m-p1",
      "tcu-m-p4"
     ]
    },
    {
     "rank": 71,
     "names": [
      "Duje Markovina",
      "Alvaro Jimenez Roman"
     ],
     "school": "Auburn",
     "teamId": "aub-m",
     "pids": [
      "aub-m-n3",
      "aub-m-n5"
     ]
    },
    {
     "rank": 72,
     "names": [
      "Petro Kuzmenok",
      "Tommy Czaplinski"
     ],
     "school": "Rice",
     "teamId": "rice-m",
     "pids": [
      "rice-m-p4",
      "rice-m-p2"
     ]
    },
    {
     "rank": 73,
     "names": [
      "Zoran Ludoski",
      "Tristan Berard"
     ],
     "school": "University Of Arizona",
     "teamId": "ariz-m",
     "pids": [
      "ariz-m-fp224",
      "ariz-m-n1"
     ]
    },
    {
     "rank": 74,
     "names": [
      "Rohan Murali",
      "Kolos Kincses"
     ],
     "school": "Harvard",
     "teamId": "harv-m",
     "pids": [
      "harv-m-p9",
      "harv-m-p5"
     ]
    },
    {
     "rank": 75,
     "names": [
      "Cole Stelse",
      "Alejandro Arcila"
     ],
     "school": "University Of Arizona",
     "teamId": "ariz-m",
     "pids": [
      "ariz-m-fp313",
      "ariz-m-fp227"
     ]
    },
    {
     "rank": 76,
     "names": [
      "Azariah Rusher",
      "Justin Lyons"
     ],
     "school": "Florida State",
     "teamId": "fsu-m",
     "pids": [
      "fsu-m-p6",
      "fsu-m-p5"
     ]
    },
    {
     "rank": 77,
     "names": [
      "Jakub Kroslak",
      "Rafael Segado Esteve"
     ],
     "school": "Miami (Florida)",
     "teamId": null,
     "pids": [
      null,
      null
     ]
    },
    {
     "rank": 78,
     "names": [
      "Devin Badenhorst",
      "Calvin Baierl"
     ],
     "school": "Baylor University",
     "teamId": "bay-m",
     "pids": [
      "bay-m-p1",
      "bay-m-p2"
     ]
    },
    {
     "rank": 79,
     "names": [
      "Georgi Georgiev",
      "Vikas Deo"
     ],
     "school": "SMU",
     "teamId": "smu-m",
     "pids": [
      "smu-m-p6",
      "smu-m-p3"
     ]
    },
    {
     "rank": 80,
     "names": [
      "Brendan Boland",
      "Connor Smillie"
     ],
     "school": "University Of Arkansas, Fayetteville",
     "teamId": "ark-m",
     "pids": [
      "ark-m-p7",
      "ark-m-p9"
     ]
    },
    {
     "rank": 81,
     "names": [
      "Roy Horovitz",
      "Stiles Brockett"
     ],
     "school": "University of Virginia",
     "teamId": "uva-m",
     "pids": [
      "uva-m-p3",
      "uva-m-p1"
     ]
    },
    {
     "rank": 82,
     "names": [
      "Aaron Sandler",
      "Zaid Mashni"
     ],
     "school": "University of Pennsylvania",
     "teamId": "penn-m",
     "pids": [
      "penn-m-p8",
      "penn-m-n2"
     ]
    },
    {
     "rank": 83,
     "names": [
      "Benjamin Martin",
      "Yannic Nittmann"
     ],
     "school": "Memphis",
     "teamId": "mem-m",
     "pids": [
      "mem-m-p5",
      "mem-m-p7"
     ]
    },
    {
     "rank": 84,
     "names": [
      "Sam Landau",
      "Braeden Gelletich"
     ],
     "school": "Indiana University",
     "teamId": "ind-m",
     "pids": [
      "ind-m-p6",
      "ind-m-p5"
     ]
    },
    {
     "rank": 85,
     "names": [
      "Miguel Avendano Cadena",
      "Marcos Castro Fabra"
     ],
     "school": "UC Santa Barbara",
     "teamId": "ucsb-m",
     "pids": [
      "ucsb-m-fp183",
      "ucsb-m-p4"
     ]
    },
    {
     "rank": 86,
     "names": [
      "Niksa Arsic",
      "Thiago Guglieri"
     ],
     "school": "Texas Tech",
     "teamId": "ttu-m",
     "pids": [
      "ttu-m-p1",
      "ttu-m-p3"
     ]
    },
    {
     "rank": 87,
     "names": [
      "Thanaphat Boosarawongse",
      "Aditya Govila"
     ],
     "school": "Columbia",
     "teamId": "colum-m",
     "pids": [
      "colum-m-p1",
      "colum-m-p4"
     ]
    },
    {
     "rank": 88,
     "names": [
      "Vojtech Vales",
      "Shaurya Bharadwaj"
     ],
     "school": "University of Pennsylvania",
     "teamId": "penn-m",
     "pids": [
      "penn-m-p10",
      "penn-m-p3"
     ]
    },
    {
     "rank": 89,
     "names": [
      "Blake Hilsen",
      "Eyal Shumilov"
     ],
     "school": "Virginia Tech",
     "teamId": "vt-m",
     "pids": [
      "vt-m-p2",
      "vt-m-p4"
     ]
    },
    {
     "rank": 90,
     "names": [
      "Kyle McNally",
      "Sturle Skigelstrand"
     ],
     "school": "Dayton",
     "teamId": null,
     "pids": [
      null,
      null
     ]
    }
   ]
  },
  "women": {
   "listId": "2026-27_d1_women_doubles_p2_v5",
   "listDate": "2026-08-25",
   "rows": [
    {
     "rank": 1,
     "names": [
      "Mimi Xu",
      "Nina Vargova"
     ],
     "school": "Duke",
     "teamId": "duke-w",
     "pids": [
      "duke-w-n2",
      "duke-w-n1"
     ]
    },
    {
     "rank": 2,
     "names": [
      "Roisin Gilheany",
      "Victoria Osuigwe"
     ],
     "school": "NC State",
     "teamId": "ncst-w",
     "pids": [
      "ncst-w-p5",
      "ncst-w-p6"
     ]
    },
    {
     "rank": 3,
     "names": [
      "Luciana Perry",
      "Flora Johnson"
     ],
     "school": "Ohio State",
     "teamId": "osu-w",
     "pids": [
      "osu-w-p9",
      "osu-w-p5"
     ]
    },
    {
     "rank": 4,
     "names": [
      "Ziva Falkner",
      "Sonja Zhiyenbayeva"
     ],
     "school": "Pepperdine",
     "teamId": "pepp-w",
     "pids": [
      "pepp-w-p1",
      "pepp-w-p7"
     ]
    },
    {
     "rank": 5,
     "names": [
      "Alexia Jacobs",
      "Anna-Marie Weissheim"
     ],
     "school": "University of Washington",
     "teamId": "wash-w",
     "pids": [
      "wash-w-p1",
      "wash-w-fp107"
     ]
    },
    {
     "rank": 6,
     "names": [
      "Valery Gynina",
      "Brooke Black"
     ],
     "school": "University Of Florida",
     "teamId": "fla-w",
     "pids": [
      "fla-p3",
      "fla-p1"
     ]
    },
    {
     "rank": 7,
     "names": [
      "Ashton Bowers",
      "Ava Esposito"
     ],
     "school": "Auburn",
     "teamId": "aub-w",
     "pids": [
      "aub-p2",
      "aub-p4"
     ]
    },
    {
     "rank": 8,
     "names": [
      "Susanna Maltby",
      "Maddy Zampardo"
     ],
     "school": "UNC Chapel Hill",
     "teamId": "unc-w",
     "pids": [
      "unc-w-p8",
      "unc-w-p11"
     ]
    },
    {
     "rank": 9,
     "names": [
      "Merna Refaat",
      "Emma Kamper"
     ],
     "school": "Auburn",
     "teamId": "aub-w",
     "pids": [
      "aub-p10",
      "aub-p6"
     ]
    },
    {
     "rank": 10,
     "names": [
      "Lily Fairclough",
      "Imogen Haddad"
     ],
     "school": "Southern California",
     "teamId": null,
     "pids": [
      null,
      null
     ]
    },
    {
     "rank": 11,
     "names": [
      "Lucciana Perez",
      "Olivia Lincer"
     ],
     "school": "Texas A&M University",
     "teamId": "tamu-w",
     "pids": [
      "tamu-p5",
      "tamu-w-n2"
     ]
    },
    {
     "rank": 12,
     "names": [
      "Emma Dong",
      "Bella Payne"
     ],
     "school": "University Of Georgia",
     "teamId": "uga-w",
     "pids": [
      "uga-p3",
      "uga-w-n1"
     ]
    },
    {
     "rank": 13,
     "names": [
      "Amelie Van Impe",
      "Caroline McGinley"
     ],
     "school": "SMU",
     "teamId": "smu-w",
     "pids": [
      "smu-w-p9",
      "smu-w-p6"
     ]
    },
    {
     "rank": 14,
     "names": [
      "Alanis Hamilton",
      "Anna Frey"
     ],
     "school": "UNC Chapel Hill",
     "teamId": "unc-w",
     "pids": [
      "unc-w-p5",
      "unc-w-p4"
     ]
    },
    {
     "rank": 15,
     "names": [
      "Tatum Evans",
      "Nicole Khirin"
     ],
     "school": "UNC Chapel Hill",
     "teamId": "unc-w",
     "pids": [
      "unc-w-p3",
      "unc-w-n3"
     ]
    },
    {
     "rank": 16,
     "names": [
      "Mia Slama",
      "Lavinia Tanasie"
     ],
     "school": "NC State",
     "teamId": "ncst-w",
     "pids": [
      "ncst-w-p7",
      "ncst-w-p9"
     ]
    },
    {
     "rank": 17,
     "names": [
      "Rose Marie Nijkamp",
      "Carmen Andreea Herea"
     ],
     "school": "University of Texas at Austin",
     "teamId": "tex-w",
     "pids": [
      "tex-w-n1",
      null
     ]
    },
    {
     "rank": 18,
     "names": [
      "Aspen Schuman",
      "Liv Hovde"
     ],
     "school": "Duke",
     "teamId": "duke-w",
     "pids": [
      "duke-w-p6",
      "duke-w-p3"
     ]
    },
    {
     "rank": 19,
     "names": [
      "Deniz Dilek",
      "Aysegul Mert"
     ],
     "school": "University Of Georgia",
     "teamId": "uga-w",
     "pids": [
      "uga-p2",
      "uga-p7"
     ]
    },
    {
     "rank": 20,
     "names": [
      "Elizabeth Ionescu",
      "Christasha McNeil"
     ],
     "school": "University of Texas at Austin",
     "teamId": "tex-w",
     "pids": [
      "tex-p6",
      "tex-p8"
     ]
    },
    {
     "rank": 21,
     "names": [
      "Valerie Glozman",
      "Alexis Blokhina"
     ],
     "school": "Stanford",
     "teamId": "stan-w",
     "pids": [
      "stan-w-p1",
      "stan-w-p7"
     ]
    },
    {
     "rank": 22,
     "names": [
      "Evialina Laskevich",
      "Ekaterina Maklakova"
     ],
     "school": "University of Oklahoma",
     "teamId": "ou-w",
     "pids": [
      "ou-p4",
      "ou-w-n2"
     ]
    },
    {
     "rank": 23,
     "names": [
      "Jasmine Conway",
      "Ariana Anazagasty-Pursoo"
     ],
     "school": "NC State",
     "teamId": "ncst-w",
     "pids": [
      "ncst-w-p3",
      "ncst-w-p1"
     ]
    },
    {
     "rank": 24,
     "names": [
      "Anastasiia Gureva",
      "Patricija Paukstyte"
     ],
     "school": "University Of Georgia",
     "teamId": "uga-w",
     "pids": [
      "uga-p5",
      "uga-p9"
     ]
    },
    {
     "rank": 25,
     "names": [
      "Lucie Urbanova",
      "Ekaterina Ivanova"
     ],
     "school": "University Of Wisconsin, Madison",
     "teamId": "wisc-w",
     "pids": [
      "wisc-w-p8",
      "wisc-w-p3"
     ]
    },
    {
     "rank": 26,
     "names": [
      "Nikola Daubnerova",
      "Lucie Pawlak"
     ],
     "school": "University Of Florida",
     "teamId": "fla-w",
     "pids": [
      "fla-p2",
      "fla-p8"
     ]
    },
    {
     "rank": 27,
     "names": [
      "Cadence Brace",
      "Ella McDonald"
     ],
     "school": "Louisiana State University",
     "teamId": "lsu-w",
     "pids": [
      "lsu-p8",
      "lsu-p1"
     ]
    },
    {
     "rank": 28,
     "names": [
      "Sophia Cisse-Ignatiev",
      "Audrey Spencer"
     ],
     "school": "Ohio State",
     "teamId": "osu-w",
     "pids": [
      "osu-w-p4",
      "osu-w-p10"
     ]
    },
    {
     "rank": 29,
     "names": [
      "Valeria Ray",
      "Sophia Webster"
     ],
     "school": "Vanderbilt",
     "teamId": "van-w",
     "pids": [
      "van-p5",
      "van-p8"
     ]
    },
    {
     "rank": 30,
     "names": [
      "Yara Bartashevich",
      "Isabella Kruger"
     ],
     "school": "Auburn",
     "teamId": "aub-w",
     "pids": [
      "aub-p1",
      "aub-p7"
     ]
    },
    {
     "rank": 31,
     "names": [
      "Chantal Sauvant",
      "Anastasiia Grechkina"
     ],
     "school": "Pepperdine",
     "teamId": "pepp-w",
     "pids": [
      "pepp-w-p6",
      "pepp-w-p2"
     ]
    },
    {
     "rank": 32,
     "names": [
      "Helena Buchwald",
      "Daniela Piani"
     ],
     "school": "University of South Carolina, Columbia",
     "teamId": "sc-w",
     "pids": [
      "sc-p3",
      "sc-p9"
     ]
    },
    {
     "rank": 33,
     "names": [
      "Martina Genis Salas",
      "Katie Rolls"
     ],
     "school": "University of Virginia",
     "teamId": "uva-w",
     "pids": [
      "uva-w-p2",
      "uva-w-p7"
     ]
    },
    {
     "rank": 34,
     "names": [
      "Lexington Reed",
      "Kristina Paskauskas"
     ],
     "school": "Texas A&M University",
     "teamId": "tamu-w",
     "pids": [
      "tamu-p8",
      "tamu-w-n1"
     ]
    },
    {
     "rank": 35,
     "names": [
      "Jessica Bernales",
      "Kate Fakih"
     ],
     "school": "UCLA",
     "teamId": "ucla-w",
     "pids": [
      null,
      "ucla-w-p9"
     ]
    },
    {
     "rank": 36,
     "names": [
      "Vivian Yang",
      "Alyssa James"
     ],
     "school": "University of Virginia",
     "teamId": "uva-w",
     "pids": [
      "uva-w-p8",
      "uva-w-p3"
     ]
    },
    {
     "rank": 37,
     "names": [
      "Duru Soke",
      "Shihomi Li Xuan Leong"
     ],
     "school": "Pepperdine",
     "teamId": "pepp-w",
     "pids": [
      "pepp-w-p5",
      "pepp-w-fp121"
     ]
    },
    {
     "rank": 38,
     "names": [
      "Sara Suchankova",
      "Candela Yecora"
     ],
     "school": "Clemson",
     "teamId": "clem-w",
     "pids": [
      "clem-w-n1",
      "clem-w-p5"
     ]
    },
    {
     "rank": 39,
     "names": [
      "Sara Shumate",
      "Gloriana Nahum"
     ],
     "school": "University of Oklahoma",
     "teamId": "ou-w",
     "pids": [
      "ou-w-n4",
      "ou-p6"
     ]
    },
    {
     "rank": 40,
     "names": [
      "Zoie Epps",
      "Salakthip Ounmang"
     ],
     "school": "University of Oklahoma",
     "teamId": "ou-w",
     "pids": [
      "ou-w-n1",
      null
     ]
    },
    {
     "rank": 41,
     "names": [
      "Reese Miller",
      "Piper Charney"
     ],
     "school": "University of Michigan",
     "teamId": "mich-w",
     "pids": [
      "mich-w-p7",
      "mich-w-p3"
     ]
    },
    {
     "rank": 42,
     "names": [
      "Zuzanna Kubacha",
      "Kenna Erickson"
     ],
     "school": "Baylor University",
     "teamId": "bay-w",
     "pids": [
      "bay-w-p4",
      "bay-w-p2"
     ]
    },
    {
     "rank": 43,
     "names": [
      "Kavya Karra",
      "Stephanie Yakoff"
     ],
     "school": "Harvard",
     "teamId": "harv-w",
     "pids": [
      "harv-w-p3",
      "harv-w-p11"
     ]
    },
    {
     "rank": 44,
     "names": [
      "Alessia Cau",
      "Nao Nishino"
     ],
     "school": "Ohio State",
     "teamId": "osu-w",
     "pids": [
      "osu-w-p2",
      "osu-w-p6"
     ]
    },
    {
     "rank": 45,
     "names": [
      "Olivia Center",
      "Ahmani Guichard"
     ],
     "school": "UCLA",
     "teamId": "ucla-w",
     "pids": [
      "ucla-w-p8",
      "ucla-w-p5"
     ]
    },
    {
     "rank": 46,
     "names": [
      "Addison Lanton",
      "Dora Miskovic"
     ],
     "school": "Louisiana State University",
     "teamId": "lsu-w",
     "pids": [
      "lsu-p4",
      "lsu-w-n3"
     ]
    },
    {
     "rank": 47,
     "names": [
      "Josie Usereau",
      "Maria Garcia"
     ],
     "school": "University Of Arizona",
     "teamId": "ariz-w",
     "pids": [
      "ariz-w-p9",
      "ariz-w-p2"
     ]
    },
    {
     "rank": 48,
     "names": [
      "Katrin Pavkova",
      "Panna Bartha"
     ],
     "school": "Florida Atlantic",
     "teamId": "fau-w",
     "pids": [
      "fau-w-p5",
      "fau-w-p2"
     ]
    },
    {
     "rank": 49,
     "names": [
      "Vilma Krebs Hyllested",
      "Maria Shmakova"
     ],
     "school": "University of San Diego",
     "teamId": "usd-w",
     "pids": [
      "usd-w-p3",
      "usd-w-p8"
     ]
    },
    {
     "rank": 50,
     "names": [
      "Xin Tong Wang",
      "Giorgia Roselli"
     ],
     "school": "Wichita State",
     "teamId": "wich-w",
     "pids": [
      "wich-w-p8",
      "wich-w-p5"
     ]
    },
    {
     "rank": 51,
     "names": [
      "Irina Balus",
      "Shavit Kimchi"
     ],
     "school": "Duke",
     "teamId": "duke-w",
     "pids": [
      "duke-w-p2",
      "duke-w-p4"
     ]
    },
    {
     "rank": 52,
     "names": [
      "Shannon Lam",
      "Eugenia Zozaya Menendez"
     ],
     "school": "University of Virginia",
     "teamId": "uva-w",
     "pids": [
      "uva-w-p5",
      null
     ]
    },
    {
     "rank": 53,
     "names": [
      "Joanna Kennedy",
      "Amelia Bissett"
     ],
     "school": "Florida State",
     "teamId": "fsu-w",
     "pids": [
      "fsu-w-p6",
      "fsu-w-n1"
     ]
    },
    {
     "rank": 54,
     "names": [
      "Kaitlyn Carnicella",
      "Anna Bella Bianca Bergqvist Larsson"
     ],
     "school": "University of South Carolina, Columbia",
     "teamId": "sc-w",
     "pids": [
      "sc-p4",
      null
     ]
    },
    {
     "rank": 55,
     "names": [
      "Francesca Mattioli",
      "Rinon Okuwaki"
     ],
     "school": "University Of Tennessee, Knoxville",
     "teamId": "tenn-w",
     "pids": [
      "tenn-p5",
      "tenn-w-n3"
     ]
    },
    {
     "rank": 56,
     "names": [
      "Andrea Nova",
      "Riley Crowder"
     ],
     "school": "Ole Miss",
     "teamId": "miss-w",
     "pids": [
      "miss-p6",
      "miss-p2"
     ]
    },
    {
     "rank": 57,
     "names": [
      "Jantje Tilbuerger",
      "Marina Gatell"
     ],
     "school": "University Of Central Florida",
     "teamId": "ucf-w",
     "pids": [
      "ucf-w-p9",
      "ucf-w-p3"
     ]
    },
    {
     "rank": 58,
     "names": [
      "Mathilde Ngijol Carre",
      "Salma Drugdova"
     ],
     "school": "University of Texas at Austin",
     "teamId": "tex-w",
     "pids": [
      null,
      "tex-p4"
     ]
    },
    {
     "rank": 59,
     "names": [
      "Kira Matushkina",
      "Cayetana Gay"
     ],
     "school": "TCU",
     "teamId": "tcu-w",
     "pids": [
      "tcu-w-p6",
      "tcu-w-p5"
     ]
    },
    {
     "rank": 60,
     "names": [
      "Bianca Molnar",
      "Gabriella Rawles"
     ],
     "school": "University of Notre Dame",
     "teamId": "nd-w",
     "pids": [
      "nd-w-p10",
      "nd-w-p5"
     ]
    },
    {
     "rank": 61,
     "names": [
      "Claire An",
      "Eleana Yu"
     ],
     "school": "Duke",
     "teamId": "duke-w",
     "pids": [
      "duke-w-p1",
      "duke-w-p7"
     ]
    },
    {
     "rank": 62,
     "names": [
      "Katie Spencer",
      "Conley Raidt"
     ],
     "school": "University of Nebraska-Lincoln",
     "teamId": "neb-w",
     "pids": [
      "neb-w-p9",
      "neb-w-p7"
     ]
    },
    {
     "rank": 63,
     "names": [
      "Karolina Kozakova",
      "Jermine Sherif"
     ],
     "school": "University of Washington",
     "teamId": "wash-w",
     "pids": [
      "wash-w-p3",
      "wash-w-p7"
     ]
    },
    {
     "rank": 64,
     "names": [
      "Alice Soulie",
      "Alice Battesti"
     ],
     "school": "Ole Miss",
     "teamId": "miss-w",
     "pids": [
      "miss-p7",
      "miss-p1"
     ]
    },
    {
     "rank": 65,
     "names": [
      "Capucine Jauffret",
      "Allegra Korpanec Davies"
     ],
     "school": "University Of Florida",
     "teamId": "fla-w",
     "pids": [
      "fla-w-n3",
      "fla-w-n2"
     ]
    },
    {
     "rank": 66,
     "names": [
      "Ema Kovacevic",
      "Oliwia Orlinska"
     ],
     "school": "University of Maryland, College Park",
     "teamId": "umd-w",
     "pids": [
      "umd-w-p7",
      "umd-w-p9"
     ]
    },
    {
     "rank": 67,
     "names": [
      "Johanne Svendsen",
      "Mao Mushika"
     ],
     "school": "University Of California, Berkeley",
     "teamId": "cal-w",
     "pids": [
      "cal-w-p8",
      "cal-w-p6"
     ]
    },
    {
     "rank": 68,
     "names": [
      "Maeve Thornton",
      "Stefani Webb"
     ],
     "school": "University Of Tennessee, Knoxville",
     "teamId": "tenn-w",
     "pids": [
      "tenn-p8",
      "tenn-w-n5"
     ]
    },
    {
     "rank": 69,
     "names": [
      "Teah Chavez",
      "Hephzibah Oluwadare"
     ],
     "school": "Ohio State",
     "teamId": "osu-w",
     "pids": [
      "osu-w-p3",
      "osu-w-p7"
     ]
    },
    {
     "rank": 70,
     "names": [
      "Martyna Ostrzygalo",
      "Sophia Christodoulou"
     ],
     "school": "University Of Arizona",
     "teamId": "ariz-w",
     "pids": [
      "ariz-w-p6",
      "ariz-w-n2"
     ]
    },
    {
     "rank": 71,
     "names": [
      "Emilija Tverijonaite",
      "Lily Taylor"
     ],
     "school": "Arizona State",
     "teamId": "asu-w",
     "pids": [
      "asu-w-p4",
      "asu-w-p2"
     ]
    },
    {
     "rank": 72,
     "names": [
      "Ruby Cooling",
      "Arina Bulatova"
     ],
     "school": "Texas A&M University",
     "teamId": "tamu-w",
     "pids": [
      "tamu-w-n3",
      "tamu-w-n8"
     ]
    },
    {
     "rank": 73,
     "names": [
      "Peyton Capuano",
      "Michela Moore"
     ],
     "school": "Dartmouth College",
     "teamId": "dart-w",
     "pids": [
      "dart-w-p1",
      "dart-w-p9"
     ]
    },
    {
     "rank": 74,
     "names": [
      "Tola Glowacka",
      "Isabella Camacho"
     ],
     "school": "Boston College",
     "teamId": "bc-w",
     "pids": [
      "bc-w-p5",
      "bc-w-fp140"
     ]
    },
    {
     "rank": 75,
     "names": [
      "Daniela Borruel",
      "Kiara Zabkova"
     ],
     "school": "Southern California",
     "teamId": null,
     "pids": [
      null,
      null
     ]
    },
    {
     "rank": 76,
     "names": [
      "Ellison Reynoldson",
      "Kaede Usui"
     ],
     "school": "University Of Wisconsin, Madison",
     "teamId": "wisc-w",
     "pids": [
      "wisc-w-p6",
      "wisc-w-p9"
     ]
    },
    {
     "rank": 77,
     "names": [
      "Amy Lee",
      "Kenzie Nguyen"
     ],
     "school": "Columbia",
     "teamId": "colum-w",
     "pids": [
      null,
      null
     ]
    },
    {
     "rank": 78,
     "names": [
      "Naomi Xu",
      "Nika Hurkacz"
     ],
     "school": "University Of California, Berkeley",
     "teamId": "cal-w",
     "pids": [
      "cal-w-p9",
      "cal-w-p4"
     ]
    },
    {
     "rank": 79,
     "names": [
      "Michaela Laki",
      "Dominika Podhajecka"
     ],
     "school": "Miami (Florida)",
     "teamId": null,
     "pids": [
      null,
      null
     ]
    },
    {
     "rank": 80,
     "names": [
      "Zdena Safarova",
      "Tereza Polakova"
     ],
     "school": "Boise State",
     "teamId": null,
     "pids": [
      null,
      null
     ]
    },
    {
     "rank": 81,
     "names": [
      "Alyssa Ahn",
      "Tianmei Wang"
     ],
     "school": "Stanford",
     "teamId": "stan-w",
     "pids": [
      "stan-w-p3",
      "stan-w-p6"
     ]
    },
    {
     "rank": 82,
     "names": [
      "Kaya Moe",
      "Aishi Das"
     ],
     "school": "Auburn",
     "teamId": "aub-w",
     "pids": [
      "aub-p8",
      "aub-p3"
     ]
    },
    {
     "rank": 83,
     "names": [
      "Mia Yamakita",
      "Trinetra Vijayakumar"
     ],
     "school": "Vanderbilt",
     "teamId": "van-w",
     "pids": [
      "van-p9",
      "van-p7"
     ]
    },
    {
     "rank": 84,
     "names": [
      "Emma Ghirardato",
      "Diya Challa"
     ],
     "school": "University of Maryland, College Park",
     "teamId": "umd-w",
     "pids": [
      "umd-w-p5",
      "umd-w-p2"
     ]
    },
    {
     "rank": 85,
     "names": [
      "Marelie Raath",
      "Neena Feldman"
     ],
     "school": "Northwestern",
     "teamId": "nw-w",
     "pids": [
      "nw-w-p6",
      "nw-w-p2"
     ]
    },
    {
     "rank": 86,
     "names": [
      "Hi'ilani Williams",
      "Alessandra Teodosescu"
     ],
     "school": "Indiana University",
     "teamId": "ind-w",
     "pids": [
      "ind-w-p10",
      "ind-w-p8"
     ]
    },
    {
     "rank": 87,
     "names": [
      "Malak El Allami",
      "Margot Phanthala"
     ],
     "school": "Columbia",
     "teamId": "colum-w",
     "pids": [
      "colum-w-p2",
      null
     ]
    },
    {
     "rank": 88,
     "names": [
      "Tess Bucher",
      "Alice Xu"
     ],
     "school": "University of Illinois at Urbana-Champaign",
     "teamId": "ill-w",
     "pids": [
      "ill-w-p1",
      "ill-w-p10"
     ]
    },
    {
     "rank": 89,
     "names": [
      "Reese Sager",
      "Asuncion Jadue"
     ],
     "school": "University of Kentucky",
     "teamId": "uk-w",
     "pids": [
      "uk-p9",
      "uk-p3"
     ]
    },
    {
     "rank": 90,
     "names": [
      "Erica Jessel",
      "Aely Arai"
     ],
     "school": "Northwestern",
     "teamId": "nw-w",
     "pids": [
      "nw-w-p3",
      null
     ]
    }
   ]
  }
 }
};
