// GENERATED by scripts/build-pro-history.mjs (§360) -- do not edit.
// Events with a match inside 16 days; rides the §222 remote
// feed and merges over the baked §355 shards at render.
export const recentAsOf = globalThis.__BAGEL_REMOTE__?.["recentProEvents"]?.recentAsOf ?? "2026-09-14";
export const recentProEvents = globalThis.__BAGEL_REMOTE__?.["recentProEvents"]?.recentProEvents ?? {
 "ariz-m-fp226": [
  {
   "key": "22024",
   "name": "Istanbul Challenger",
   "date": "2026-09-07",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "1293147",
     "date": "2026-09-08",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Michele Ribecai",
     "score": "2-6 6-4 6-4"
    },
    {
     "id": "1293131",
     "date": "2026-09-10",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Samir Hamza Reguig",
     "score": "6-2 6-1"
    },
    {
     "id": "12474024",
     "date": "2026-09-11",
     "roundId": 9,
     "round": "QF",
     "won": true,
     "opponent": "Yanki Erel",
     "score": "3-6 6-4 6-3"
    },
    {
     "id": "44622756",
     "date": "2026-09-12",
     "roundId": 10,
     "round": "SF",
     "won": true,
     "opponent": "Maks Kasnikowski",
     "score": "7-6(4) 6-4"
    },
    {
     "id": "83763680",
     "date": "2026-09-13",
     "roundId": 12,
     "round": "Final",
     "won": false,
     "opponent": "Max Basing",
     "score": "6-3 1-6 6-0"
    }
   ],
   "reached": "Final",
   "reachedTone": "amber"
  },
  {
   "key": "21942",
   "name": "Manacor Challenger",
   "date": "2026-08-31",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "1286586",
     "date": "2026-09-02",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Matheus Pucinelli De Almeida",
     "score": "7-6(2) 6-3"
    },
    {
     "id": "1286601",
     "date": "2026-09-03",
     "roundId": 5,
     "round": "Second",
     "won": false,
     "opponent": "Billy Harris",
     "score": "7-5 6-4"
    }
   ],
   "reached": "Second",
   "reachedTone": "neutral"
  }
 ],
 "ark-m-p3": [
  {
   "key": "22055",
   "name": "M15 Budapest",
   "date": "2026-09-07",
   "surface": "Clay",
   "tier": "ITF",
   "matches": [
    {
     "id": "1294039",
     "date": "2026-09-06",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Jiang Yi Qing",
     "score": "6-1 6-2"
    },
    {
     "id": "1294038",
     "date": "2026-09-07",
     "roundId": 2,
     "round": "Q2",
     "won": true,
     "opponent": "Ivan Biletic",
     "score": "3-6 6-1 11-9"
    },
    {
     "id": "1294029",
     "date": "2026-09-08",
     "roundId": 3,
     "round": "Q3",
     "won": true,
     "opponent": "Radovan Michalik",
     "score": "6-2 6-3"
    },
    {
     "id": "1294030",
     "date": "2026-09-09",
     "roundId": 4,
     "round": "First",
     "won": false,
     "opponent": "Lilian Marmousez",
     "score": "6-1 3-6 6-1"
    }
   ],
   "reached": "First",
   "reachedTone": "neutral"
  }
 ],
 "ark-m-p6": [
  {
   "key": "21997",
   "name": "M15 Champaign",
   "date": "2026-08-24",
   "surface": "Hard",
   "tier": "ITF",
   "matches": [
    {
     "id": "1291082",
     "date": "2026-08-24",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Alex Fuchs",
     "score": "6-4 6-4"
    },
    {
     "id": "1291093",
     "date": "2026-08-25",
     "roundId": 3,
     "round": "Q3",
     "won": true,
     "opponent": "Nicholas Mekhael",
     "score": "6-2 6-1"
    },
    {
     "id": "1291063",
     "date": "2026-08-26",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Alexander Frusina",
     "score": "6-3 6-4"
    },
    {
     "id": "1291055",
     "date": "2026-08-27",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Ryan Colby",
     "score": "4-6 7-6(4) 7-5"
    },
    {
     "id": "1291056",
     "date": "2026-08-28",
     "roundId": 9,
     "round": "QF",
     "won": true,
     "opponent": "Ofek Shimanov",
     "score": "0-6 7-6(5) 6-2"
    },
    {
     "id": "1291050",
     "date": "2026-08-29",
     "roundId": 10,
     "round": "SF",
     "won": true,
     "opponent": "Oliver Okonkwo",
     "score": "3-6 6-3 7-5"
    },
    {
     "id": "1291080",
     "date": "2026-08-30",
     "roundId": 12,
     "round": "Final",
     "won": false,
     "opponent": "Bryce Nakashima",
     "score": "6-2 7-6(6)"
    }
   ],
   "reached": "Final",
   "reachedTone": "amber"
  }
 ],
 "asu-m-p2": [
  {
   "key": "22055",
   "name": "M15 Budapest",
   "date": "2026-09-07",
   "surface": "Clay",
   "tier": "ITF",
   "matches": [
    {
     "id": "1294036",
     "date": "2026-09-09",
     "roundId": 4,
     "round": "First",
     "won": false,
     "opponent": "Heorhii Shylov",
     "score": "6-1 3-6 6-2"
    }
   ],
   "reached": "First",
   "reachedTone": "neutral"
  }
 ],
 "cal-m-p9": [
  {
   "key": "22047",
   "name": "M25 Gijon",
   "date": "2026-09-07",
   "surface": "Clay",
   "tier": "ITF",
   "matches": [
    {
     "id": "1293460",
     "date": "2026-09-08",
     "roundId": 4,
     "round": "First",
     "won": false,
     "opponent": "Mario Arce Fernandez",
     "score": "3-6 6-0 7-6(2)"
    }
   ],
   "reached": "First",
   "reachedTone": "neutral"
  },
  {
   "key": "22008",
   "name": "M15 Madrid",
   "date": "2026-08-31",
   "surface": "Clay",
   "tier": "ITF",
   "matches": [
    {
     "id": "1291937",
     "date": "2026-09-02",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Carles Cordoba",
     "score": "4-6 6-2 5-2 ret."
    },
    {
     "id": "1291956",
     "date": "2026-09-03",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Juan Ignacio Gallego",
     "score": "6-7(4) 6-2 6-3"
    },
    {
     "id": "1291929",
     "date": "2026-09-04",
     "roundId": 9,
     "round": "QF",
     "won": false,
     "opponent": "Ryan Nijboer",
     "score": "6-2 4-6 6-1"
    }
   ],
   "reached": "QF",
   "reachedTone": "neutral"
  }
 ],
 "duke-w-n2": [
  {
   "key": "16745",
   "name": "Guadalajara Open Akron - Guadalajara",
   "date": "2026-09-14",
   "surface": "Hard",
   "tier": "Tour",
   "matches": [
    {
     "id": "48706222",
     "date": "2026-09-12",
     "roundId": 1,
     "round": "Q1",
     "won": false,
     "opponent": "Caroline Dolehide",
     "score": "6-0 6-4"
    }
   ],
   "reached": "Q1",
   "reachedTone": "neutral"
  }
 ],
 "lsu-m-n1": [
  {
   "key": "22027",
   "name": "Tiburon Challenger",
   "date": "2026-09-14",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "99140479",
     "date": "2026-09-13",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Gus Grumet",
     "score": "6-2 6-2"
    }
   ],
   "reached": "Q1",
   "reachedTone": "neutral"
  }
 ],
 "lsu-m-p2": [
  {
   "key": "22027",
   "name": "Tiburon Challenger",
   "date": "2026-09-14",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "90753266",
     "date": "2026-09-13",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Nicholas Godsick",
     "score": "6-3 6-1"
    }
   ],
   "reached": "Q1",
   "reachedTone": "neutral"
  }
 ],
 "lsu-p8": [
  {
   "key": "16746",
   "name": "SP Open - Sao Paulo",
   "date": "2026-09-14",
   "surface": "Hard",
   "tier": "Tour",
   "matches": [
    {
     "id": "53612592",
     "date": "2026-09-12",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Ana Candiotto",
     "score": "6-3 6-4"
    },
    {
     "id": "84272008",
     "date": "2026-09-13",
     "roundId": 3,
     "round": "Q3",
     "won": true,
     "opponent": "Hayu Kinoshita",
     "score": "7-5 7-6(9)"
    }
   ],
   "reached": "Q3",
   "reachedTone": "neutral"
  },
  {
   "key": "17253",
   "name": "Kia Open - Barranquilla",
   "date": "2026-09-07",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "904624",
     "date": "2026-09-08",
     "roundId": 4,
     "round": "First",
     "won": false,
     "opponent": "Sara Sorribes Tormo",
     "score": "6-2 4-6 6-4"
    }
   ],
   "reached": "First",
   "reachedTone": "neutral"
  },
  {
   "key": "17228",
   "name": "W35 Barueri",
   "date": "2026-08-24",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "902795",
     "date": "2026-08-26",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Julia Konishi Camargo Silva",
     "score": "6-2 6-2"
    },
    {
     "id": "902792",
     "date": "2026-08-27",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Maria Navarro Oliva",
     "score": "6-1 6-1"
    },
    {
     "id": "902800",
     "date": "2026-08-28",
     "roundId": 9,
     "round": "QF",
     "won": true,
     "opponent": "Ana Candiotto",
     "score": "6-3 6-4"
    },
    {
     "id": "902827",
     "date": "2026-08-29",
     "roundId": 10,
     "round": "SF",
     "won": true,
     "opponent": "Nauhany Vitoria Leme Da Silva",
     "score": "6-3 7-6(2)"
    },
    {
     "id": "902813",
     "date": "2026-08-30",
     "roundId": 12,
     "round": "Final",
     "won": true,
     "opponent": "Lan Mi",
     "score": "1-6 7-5 6-3"
    }
   ],
   "reached": "Title",
   "reachedTone": "gold"
  }
 ],
 "miss-m-p2": [
  {
   "key": "22030",
   "name": "Biella Challenger",
   "date": "2026-09-14",
   "surface": "Clay",
   "tier": "Challenger",
   "matches": [
    {
     "id": "78171971",
     "date": "2026-09-13",
     "roundId": 1,
     "round": "Q1",
     "won": false,
     "opponent": "Giuseppe La Vela",
     "score": "6-1 6-3"
    }
   ],
   "reached": "Q1",
   "reachedTone": "neutral"
  },
  {
   "key": "22009",
   "name": "M15 Kursumlijska Banja",
   "date": "2026-08-31",
   "surface": "Clay",
   "tier": "ITF",
   "matches": [
    {
     "id": "1292033",
     "date": "2026-09-02",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Marko Nikolic",
     "score": "6-4 6-4"
    },
    {
     "id": "1292082",
     "date": "2026-09-03",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Richard Lacis",
     "score": "6-3 6-3"
    },
    {
     "id": "1292010",
     "date": "2026-09-04",
     "roundId": 9,
     "round": "QF",
     "won": false,
     "opponent": "Alexandre Aubriot",
     "score": "6-3 1-6 6-0"
    }
   ],
   "reached": "QF",
   "reachedTone": "neutral"
  }
 ],
 "msu-m-p1": [
  {
   "key": "22054",
   "name": "M15 Monastir",
   "date": "2026-09-07",
   "surface": "Hard",
   "tier": "ITF",
   "matches": [
    {
     "id": "1293949",
     "date": "2026-09-09",
     "roundId": 4,
     "round": "First",
     "won": false,
     "opponent": "James Connel",
     "score": "6-3 6-4"
    }
   ],
   "reached": "First",
   "reachedTone": "neutral"
  }
 ],
 "ncst-m-fp370": [
  {
   "key": "22031",
   "name": "Phan Thiet 4 Challenger",
   "date": "2026-09-14",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "69784534",
     "date": "2026-09-13",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Yuta Kawahashi",
     "score": "6-3 4-0 ret."
    },
    {
     "id": "104731874",
     "date": "2026-09-14",
     "roundId": 3,
     "round": "Q3",
     "won": true,
     "opponent": "Dong Ju Kim",
     "score": "6-4 6-3"
    }
   ],
   "reached": "Q3",
   "reachedTone": "neutral"
  },
  {
   "key": "22025",
   "name": "Phan Thiet 3 Challenger",
   "date": "2026-09-07",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "1293177",
     "date": "2026-09-06",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Takuya Kumasaka",
     "score": "6-4 6-2"
    },
    {
     "id": "1293190",
     "date": "2026-09-07",
     "roundId": 3,
     "round": "Q3",
     "won": true,
     "opponent": "Ethan Cook",
     "score": "6-3 6-2"
    },
    {
     "id": "1293170",
     "date": "2026-09-08",
     "roundId": 4,
     "round": "First",
     "won": false,
     "opponent": "Koki Matsuda",
     "score": "7-5 7-6(4)"
    }
   ],
   "reached": "First",
   "reachedTone": "neutral"
  }
 ],
 "okst-w-p1": [
  {
   "key": "17273",
   "name": "W15 Campulung",
   "date": "2026-09-07",
   "surface": "Clay",
   "tier": "ITF",
   "matches": [
    {
     "id": "905121",
     "date": "2026-09-09",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Noemi La Cagnina",
     "score": "6-1 6-2"
    },
    {
     "id": "905124",
     "date": "2026-09-10",
     "roundId": 5,
     "round": "Second",
     "won": false,
     "opponent": "Cristiana Nicoleta Todoni",
     "score": "6-4 6-3"
    }
   ],
   "reached": "Second",
   "reachedTone": "neutral"
  },
  {
   "key": "17238",
   "name": "W15 Brasov",
   "date": "2026-08-31",
   "surface": "Clay",
   "tier": "ITF",
   "matches": [
    {
     "id": "903563",
     "date": "2026-09-02",
     "roundId": 4,
     "round": "First",
     "won": false,
     "opponent": "Ioana Maria Sandru",
     "score": "0-6 6-4 6-3"
    }
   ],
   "reached": "First",
   "reachedTone": "neutral"
  }
 ],
 "ore-m-p1": [
  {
   "key": "22016",
   "name": "M15 Buzau",
   "date": "2026-08-31",
   "surface": "Clay",
   "tier": "ITF",
   "matches": [
    {
     "id": "1292669",
     "date": "2026-08-30",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Riccardo Pasetto",
     "score": "6-0 6-0"
    },
    {
     "id": "1292665",
     "date": "2026-08-31",
     "roundId": 3,
     "round": "Q3",
     "won": true,
     "opponent": "Evan Galea",
     "score": "6-0 6-2"
    },
    {
     "id": "1292636",
     "date": "2026-09-01",
     "roundId": 4,
     "round": "First",
     "won": false,
     "opponent": "Sebastian Gima",
     "score": "7-5 6-0"
    }
   ],
   "reached": "First",
   "reachedTone": "neutral"
  },
  {
   "key": "21996",
   "name": "M15 Bucharest",
   "date": "2026-08-24",
   "surface": "Clay",
   "tier": "ITF",
   "matches": [
    {
     "id": "1290940",
     "date": "2026-08-23",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Stephanos Schinas",
     "score": "6-3 6-0"
    },
    {
     "id": "1290949",
     "date": "2026-08-24",
     "roundId": 2,
     "round": "Q2",
     "won": true,
     "opponent": "Stefan Cizelj-Zivkovic",
     "score": "6-2 6-1"
    },
    {
     "id": "1290958",
     "date": "2026-08-25",
     "roundId": 3,
     "round": "Q3",
     "won": true,
     "opponent": "Mircea Mortasifu",
     "score": "6-1 6-0"
    },
    {
     "id": "1290997",
     "date": "2026-08-26",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Andrei Corneliu Gadoiu",
     "score": "6-1 6-2"
    },
    {
     "id": "1290965",
     "date": "2026-08-27",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Nicolas Robert",
     "score": "6-4 6-1"
    },
    {
     "id": "1290974",
     "date": "2026-08-28",
     "roundId": 9,
     "round": "QF",
     "won": true,
     "opponent": "Robert Guna",
     "score": "7-6(3) 0-6 6-3"
    },
    {
     "id": "1290957",
     "date": "2026-08-29",
     "roundId": 10,
     "round": "SF",
     "won": false,
     "opponent": "Radu David Turcanu",
     "score": "6-3 7-5"
    }
   ],
   "reached": "SF",
   "reachedTone": "green"
  }
 ],
 "osu-m-p11": [
  {
   "key": "21997",
   "name": "M15 Champaign",
   "date": "2026-08-24",
   "surface": "Hard",
   "tier": "ITF",
   "matches": [
    {
     "id": "1291087",
     "date": "2026-08-24",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Emmanuel Alex",
     "score": "6-3 6-2"
    },
    {
     "id": "1291091",
     "date": "2026-08-25",
     "roundId": 3,
     "round": "Q3",
     "won": true,
     "opponent": "Jon Gamble",
     "score": "6-4 7-5"
    },
    {
     "id": "1291053",
     "date": "2026-08-26",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Noa Vukadin",
     "score": "6-1 6-2"
    },
    {
     "id": "1290306",
     "date": "2026-08-27",
     "roundId": 5,
     "round": "Second",
     "won": false,
     "opponent": "Joshua Peck",
     "score": "7-6(4) 6-3"
    },
    {
     "id": "1291043",
     "date": "2026-08-27",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Joshua Peck",
     "score": "7-6(4) 6-3"
    },
    {
     "id": "1291069",
     "date": "2026-08-28",
     "roundId": 9,
     "round": "QF",
     "won": true,
     "opponent": "Marko Mesarovic",
     "score": "7-6(6) 6-3"
    },
    {
     "id": "1291059",
     "date": "2026-08-29",
     "roundId": 10,
     "round": "SF",
     "won": false,
     "opponent": "Bryce Nakashima",
     "score": "6-2 7-6(5)"
    }
   ],
   "reached": "SF",
   "reachedTone": "green"
  }
 ],
 "osu-m-p7": [
  {
   "key": "22027",
   "name": "Tiburon Challenger",
   "date": "2026-09-14",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "97742641",
     "date": "2026-09-13",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Kaylan Bigun",
     "score": "7-5 6-0"
    }
   ],
   "reached": "Q1",
   "reachedTone": "neutral"
  },
  {
   "key": "21997",
   "name": "M15 Champaign",
   "date": "2026-08-24",
   "surface": "Hard",
   "tier": "ITF",
   "matches": [
    {
     "id": "1291051",
     "date": "2026-08-26",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Rocco Piatti",
     "score": "6-3 7-5"
    },
    {
     "id": "1291047",
     "date": "2026-08-27",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Tyler Bowers",
     "score": "6-3 6-2"
    },
    {
     "id": "1291049",
     "date": "2026-08-28",
     "roundId": 9,
     "round": "QF",
     "won": true,
     "opponent": "Jack Anthrop",
     "score": "6-3 6-4"
    },
    {
     "id": "1291059",
     "date": "2026-08-29",
     "roundId": 10,
     "round": "SF",
     "won": true,
     "opponent": "Preston Stearns",
     "score": "6-2 7-6(5)"
    },
    {
     "id": "1291080",
     "date": "2026-08-30",
     "roundId": 12,
     "round": "Final",
     "won": true,
     "opponent": "Jakub Vrba",
     "score": "6-2 7-6(6)"
    }
   ],
   "reached": "Title",
   "reachedTone": "gold"
  }
 ],
 "sc-m-p6": [
  {
   "key": "22024",
   "name": "Istanbul Challenger",
   "date": "2026-09-07",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "1293145",
     "date": "2026-09-08",
     "roundId": 4,
     "round": "First",
     "won": false,
     "opponent": "Max Basing",
     "score": "6-1 6-0"
    }
   ],
   "reached": "First",
   "reachedTone": "neutral"
  }
 ],
 "stan-m-fp374": [
  {
   "key": "22045",
   "name": "M25 Plaisir",
   "date": "2026-09-07",
   "surface": "I.hard",
   "tier": "ITF",
   "matches": [
    {
     "id": "1293287",
     "date": "2026-09-09",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Alexandre Reco",
     "score": "6-4 6-3"
    },
    {
     "id": "1293278",
     "date": "2026-09-10",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Karl Friberg",
     "score": "6-3 6-4"
    },
    {
     "id": "16667241",
     "date": "2026-09-11",
     "roundId": 9,
     "round": "QF",
     "won": true,
     "opponent": "Toby Martin",
     "score": "6-3 6-4"
    },
    {
     "id": "57203704",
     "date": "2026-09-12",
     "roundId": 10,
     "round": "SF",
     "won": true,
     "opponent": "Patrick Zahraj",
     "score": "7-5 6-3"
    },
    {
     "id": "111720859",
     "date": "2026-09-13",
     "roundId": 12,
     "round": "Final",
     "won": false,
     "opponent": "Clement Chidekh",
     "score": "7-6(5) 6-1"
    }
   ],
   "reached": "Final",
   "reachedTone": "amber"
  }
 ],
 "stan-m-fp423": [
  {
   "key": "22027",
   "name": "Tiburon Challenger",
   "date": "2026-09-14",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "90753266",
     "date": "2026-09-13",
     "roundId": 1,
     "round": "Q1",
     "won": false,
     "opponent": "Erik Arutiunian",
     "score": "6-3 6-1"
    }
   ],
   "reached": "Q1",
   "reachedTone": "neutral"
  }
 ],
 "stan-m-p5": [
  {
   "key": "22056",
   "name": "M15 Bali",
   "date": "2026-09-07",
   "surface": "Hard",
   "tier": "ITF",
   "matches": [
    {
     "id": "1294123",
     "date": "2026-09-08",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Kai-I Wang",
     "score": "6-2 6-2"
    },
    {
     "id": "1294117",
     "date": "2026-09-10",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Anton Shepp",
     "score": "6-4 6-3"
    },
    {
     "id": "8282120",
     "date": "2026-09-11",
     "roundId": 9,
     "round": "QF",
     "won": true,
     "opponent": "Isaac Becroft",
     "score": "6-4 2-6 7-6(4)"
    },
    {
     "id": "41828167",
     "date": "2026-09-12",
     "roundId": 10,
     "round": "SF",
     "won": false,
     "opponent": "Alexander Chang",
     "score": "3-6 6-1 6-4"
    }
   ],
   "reached": "SF",
   "reachedTone": "green"
  },
  {
   "key": "22006",
   "name": "M15 Bali",
   "date": "2026-08-31",
   "surface": "Hard",
   "tier": "ITF",
   "matches": [
    {
     "id": "1291766",
     "date": "2026-09-01",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Pablo Perez Ramos",
     "score": "6-2 2-6 6-4"
    },
    {
     "id": "1291756",
     "date": "2026-09-03",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Anthony Susanto",
     "score": "7-5 ret."
    },
    {
     "id": "1291776",
     "date": "2026-09-04",
     "roundId": 9,
     "round": "QF",
     "won": false,
     "opponent": "Karan Singh",
     "score": "6-1 6-4"
    }
   ],
   "reached": "QF",
   "reachedTone": "neutral"
  }
 ],
 "tenn-m-n5": [
  {
   "key": "22055",
   "name": "M15 Budapest",
   "date": "2026-09-07",
   "surface": "Clay",
   "tier": "ITF",
   "matches": [
    {
     "id": "1294053",
     "date": "2026-09-09",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Matei Todoran",
     "score": "6-3 1-6 6-1"
    },
    {
     "id": "1294021",
     "date": "2026-09-10",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Rafael Kis Balazs",
     "score": "6-2 6-4"
    },
    {
     "id": "50215180",
     "date": "2026-09-11",
     "roundId": 9,
     "round": "QF",
     "won": false,
     "opponent": "Lilian Marmousez",
     "score": "6-1 6-3"
    }
   ],
   "reached": "QF",
   "reachedTone": "neutral"
  }
 ],
 "tenn-p3": [
  {
   "key": "17275",
   "name": "W15 Pilar",
   "date": "2026-09-07",
   "surface": "Clay",
   "tier": "ITF",
   "matches": [
    {
     "id": "905247",
     "date": "2026-09-08",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Maria Navarro Oliva",
     "score": "6-4 6-0"
    },
    {
     "id": "905265",
     "date": "2026-09-10",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Michela Castro Zunino",
     "score": "6-2 6-1"
    },
    {
     "id": "20528903",
     "date": "2026-09-11",
     "roundId": 9,
     "round": "QF",
     "won": false,
     "opponent": "Lourdes Ayala",
     "score": "6-0 6-3"
    }
   ],
   "reached": "QF",
   "reachedTone": "neutral"
  }
 ],
 "tenn-p6": [
  {
   "key": "16745",
   "name": "Guadalajara Open Akron - Guadalajara",
   "date": "2026-09-14",
   "surface": "Hard",
   "tier": "Tour",
   "matches": [
    {
     "id": "47479645",
     "date": "2026-09-12",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Alexandra Panova",
     "score": "6-2 6-4"
    },
    {
     "id": "79367522",
     "date": "2026-09-13",
     "roundId": 3,
     "round": "Q3",
     "won": false,
     "opponent": "Carole Monnet",
     "score": "7-6(6) 6-7(4) 6-2"
    }
   ],
   "reached": "Q3",
   "reachedTone": "neutral"
  },
  {
   "key": "17253",
   "name": "Kia Open - Barranquilla",
   "date": "2026-09-07",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "904618",
     "date": "2026-09-07",
     "roundId": 4,
     "round": "First",
     "won": false,
     "opponent": "Varvara Lepchenko",
     "score": "7-6(1) 6-1"
    }
   ],
   "reached": "First",
   "reachedTone": "neutral"
  }
 ],
 "tex-m-n3": [
  {
   "key": "22019",
   "name": "Genoa Challenger",
   "date": "2026-09-07",
   "surface": "Clay",
   "tier": "Challenger",
   "matches": [
    {
     "id": "1292841",
     "date": "2026-09-08",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Franco Agamenone",
     "score": "6-3 4-0 ret."
    },
    {
     "id": "1292842",
     "date": "2026-09-10",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Hugo Dellien",
     "score": "5-3 ret."
    },
    {
     "id": "25053236",
     "date": "2026-09-11",
     "roundId": 9,
     "round": "QF",
     "won": true,
     "opponent": "Enrico Dalla Valle",
     "score": "6-7(4) 6-2 7-6(5)"
    },
    {
     "id": "61396863",
     "date": "2026-09-12",
     "roundId": 10,
     "round": "SF",
     "won": false,
     "opponent": "Thiago Seyboth Wild",
     "score": "7-5 4-6 6-2"
    }
   ],
   "reached": "SF",
   "reachedTone": "green"
  },
  {
   "key": "21941",
   "name": "Como Challenger",
   "date": "2026-08-31",
   "surface": "Clay",
   "tier": "Challenger",
   "matches": [
    {
     "id": "1286535",
     "date": "2026-08-31",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Mili Poljicak",
     "score": "6-2 6-3"
    },
    {
     "id": "1286549",
     "date": "2026-09-02",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Henry Bernet",
     "score": "6-7(1) 7-6(3) 7-5"
    },
    {
     "id": "1286545",
     "date": "2026-09-04",
     "roundId": 9,
     "round": "QF",
     "won": true,
     "opponent": "Max Schoenhaus",
     "score": "2-6 7-6(1) 6-3"
    },
    {
     "id": "1286506",
     "date": "2026-09-05",
     "roundId": 10,
     "round": "SF",
     "won": true,
     "opponent": "Johan Nikles",
     "score": "6-3 6-0"
    },
    {
     "id": "1286502",
     "date": "2026-09-06",
     "roundId": 12,
     "round": "Final",
     "won": true,
     "opponent": "Juan Pablo Varillas",
     "score": "6-3 7-6(5)"
    }
   ],
   "reached": "Title",
   "reachedTone": "gold"
  }
 ],
 "uga-m-p3": [
  {
   "key": "22011",
   "name": "M15 Trelew",
   "date": "2026-08-31",
   "surface": "I.hard",
   "tier": "ITF",
   "matches": [
    {
     "id": "1292175",
     "date": "2026-09-01",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Jackson Ross",
     "score": "6-2 6-3"
    },
    {
     "id": "87718741",
     "date": "2026-09-02",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Jackson Ross",
     "score": "6-2 6-3"
    },
    {
     "id": "1292179",
     "date": "2026-09-02",
     "roundId": 5,
     "round": "Second",
     "won": false,
     "opponent": "Julian Cundom",
     "score": "2-6 6-4 7-6(4)"
    }
   ],
   "reached": "Second",
   "reachedTone": "neutral"
  }
 ],
 "usc-m-p3": [
  {
   "key": "22009",
   "name": "M15 Kursumlijska Banja",
   "date": "2026-08-31",
   "surface": "Clay",
   "tier": "ITF",
   "matches": [
    {
     "id": "1292020",
     "date": "2026-09-02",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Maxim Khorozov",
     "score": "6-1 6-1"
    },
    {
     "id": "1292006",
     "date": "2026-09-03",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Alessandro Bellifemine",
     "score": "6-3 6-2"
    },
    {
     "id": "1292025",
     "date": "2026-09-04",
     "roundId": 9,
     "round": "QF",
     "won": true,
     "opponent": "Antoni Fabre",
     "score": "6-7(8) 6-4 6-4"
    },
    {
     "id": "1292038",
     "date": "2026-09-05",
     "roundId": 10,
     "round": "SF",
     "won": true,
     "opponent": "Nikita Bilozertsev",
     "score": "6-1 6-2"
    },
    {
     "id": "1292000",
     "date": "2026-09-06",
     "roundId": 12,
     "round": "Final",
     "won": true,
     "opponent": "Dmitry Popko",
     "score": "6-7(3) 6-2 6-4"
    }
   ],
   "reached": "Title",
   "reachedTone": "gold"
  },
  {
   "key": "21991",
   "name": "M15 Kursumlijska Banja",
   "date": "2026-08-24",
   "surface": "Clay",
   "tier": "ITF",
   "matches": [
    {
     "id": "1290482",
     "date": "2026-08-26",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Maties Torres Ramis",
     "score": "6-2 6-0"
    },
    {
     "id": "1290478",
     "date": "2026-08-27",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Mario Arce Fernandez",
     "score": "6-2 6-4"
    },
    {
     "id": "1290461",
     "date": "2026-08-28",
     "roundId": 9,
     "round": "QF",
     "won": true,
     "opponent": "George Lazarov",
     "score": "6-3 7-6(2)"
    },
    {
     "id": "1290468",
     "date": "2026-08-29",
     "roundId": 10,
     "round": "SF",
     "won": true,
     "opponent": "Andrea Motta",
     "score": "6-2 6-3"
    },
    {
     "id": "1290441",
     "date": "2026-08-30",
     "roundId": 12,
     "round": "Final",
     "won": true,
     "opponent": "Dmitry Popko",
     "score": "6-2 6-7(4) 6-3"
    }
   ],
   "reached": "Title",
   "reachedTone": "gold"
  }
 ],
 "usf-m-p3": [
  {
   "key": "22011",
   "name": "M15 Trelew",
   "date": "2026-08-31",
   "surface": "I.hard",
   "tier": "ITF",
   "matches": [
    {
     "id": "1292198",
     "date": "2026-08-30",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Tadeo Meneo",
     "score": "6-4 6-2"
    },
    {
     "id": "1292171",
     "date": "2026-08-31",
     "roundId": 3,
     "round": "Q3",
     "won": false,
     "opponent": "Giovanni Branchetti",
     "score": "6-3 6-4"
    }
   ],
   "reached": "Q3",
   "reachedTone": "neutral"
  }
 ],
 "wash-w-p7": [
  {
   "key": "17249",
   "name": "W15 Hurghada",
   "date": "2026-08-31",
   "surface": "Hard",
   "tier": "ITF",
   "matches": [
    {
     "id": "904421",
     "date": "2026-09-02",
     "roundId": 4,
     "round": "First",
     "won": false,
     "opponent": "Elina Nepliy",
     "score": "7-5 6-3"
    }
   ],
   "reached": "First",
   "reachedTone": "neutral"
  }
 ]
};
