// GENERATED by scripts/build-pro-history.mjs (§360) -- do not edit.
// Events with a match inside 16 days; rides the §222 remote
// feed and merges over the baked §355 shards at render.
export const recentAsOf = globalThis.__BAGEL_REMOTE__?.["recentProEvents"]?.recentAsOf ?? "2026-09-22";
export const recentProEvents = globalThis.__BAGEL_REMOTE__?.["recentProEvents"]?.recentProEvents ?? {
 "ariz-m-fp226": [
  {
   "key": "22024",
   "name": "Istanbul Challenger",
   "date": "2026-09-07",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "1293212",
     "date": "2026-09-08",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Michele Ribecai",
     "score": "2-6 6-4 6-4"
    },
    {
     "id": "1293193",
     "date": "2026-09-10",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Samir Hamza Reguig",
     "score": "6-2 6-1"
    },
    {
     "id": "1293188",
     "date": "2026-09-11",
     "roundId": 9,
     "round": "QF",
     "won": true,
     "opponent": "Yanki Erel",
     "score": "3-6 6-4 6-3"
    },
    {
     "id": "1293202",
     "date": "2026-09-12",
     "roundId": 10,
     "round": "SF",
     "won": true,
     "opponent": "Maks Kasnikowski",
     "score": "7-6(4) 6-4"
    },
    {
     "id": "1293206",
     "date": "2026-09-13",
     "roundId": 12,
     "round": "Final",
     "won": false,
     "opponent": "Max Basing",
     "score": "6-3 1-6 6-0"
    }
   ],
   "reached": "Final",
   "reachedTone": "amber"
  }
 ],
 "ark-m-p3": [
  {
   "key": "22055",
   "name": "M15 Budapest",
   "date": "2026-09-07",
   "surface": "Clay",
   "tier": "ITF",
   "matches": [
    {
     "id": "1294568",
     "date": "2026-09-06",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Jiang Yi Qing",
     "score": "6-1 6-2"
    },
    {
     "id": "1294566",
     "date": "2026-09-07",
     "roundId": 2,
     "round": "Q2",
     "won": true,
     "opponent": "Ivan Biletic",
     "score": "3-6 6-1 11-9"
    },
    {
     "id": "1294556",
     "date": "2026-09-08",
     "roundId": 3,
     "round": "Q3",
     "won": true,
     "opponent": "Radovan Michalik",
     "score": "6-2 6-3"
    },
    {
     "id": "1294557",
     "date": "2026-09-09",
     "roundId": 4,
     "round": "First",
     "won": false,
     "opponent": "Lilian Marmousez",
     "score": "6-1 3-6 6-1"
    }
   ],
   "reached": "First",
   "reachedTone": "neutral"
  }
 ],
 "ark-m-p6": [
  {
   "key": "22035",
   "name": "San Diego 2 Challenger",
   "date": "2026-09-21",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "92208690",
     "date": "2026-09-20",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Blaise Bicknell",
     "score": "6-3 3-1 ret."
    },
    {
     "id": "125775701",
     "date": "2026-09-21",
     "roundId": 3,
     "round": "Q3",
     "won": false,
     "opponent": "Spencer Johnson",
     "score": "6-2 6-4"
    }
   ],
   "reached": "Q3",
   "reachedTone": "neutral"
  }
 ],
 "asu-m-p2": [
  {
   "key": "22055",
   "name": "M15 Budapest",
   "date": "2026-09-07",
   "surface": "Clay",
   "tier": "ITF",
   "matches": [
    {
     "id": "1294564",
     "date": "2026-09-09",
     "roundId": 4,
     "round": "First",
     "won": false,
     "opponent": "Heorhii Shylov",
     "score": "6-1 3-6 6-2"
    }
   ],
   "reached": "First",
   "reachedTone": "neutral"
  }
 ],
 "aub-m-p1": [
  {
   "key": "22066",
   "name": "M15 Monastir",
   "date": "2026-09-14",
   "surface": "Hard",
   "tier": "ITF",
   "matches": [
    {
     "id": "1295375",
     "date": "2026-09-16",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Ammar Elamin",
     "score": "6-2 6-2"
    },
    {
     "id": "1295382",
     "date": "2026-09-17",
     "roundId": 5,
     "round": "Second",
     "won": false,
     "opponent": "Mohamed Nazim Makhlouf",
     "score": "7-5 0-6 6-4"
    }
   ],
   "reached": "Second",
   "reachedTone": "neutral"
  }
 ],
 "cal-m-p9": [
  {
   "key": "22047",
   "name": "M25 Gijon",
   "date": "2026-09-07",
   "surface": "Clay",
   "tier": "ITF",
   "matches": [
    {
     "id": "1293889",
     "date": "2026-09-08",
     "roundId": 4,
     "round": "First",
     "won": false,
     "opponent": "Mario Arce Fernandez",
     "score": "3-6 6-0 7-6(2)"
    }
   ],
   "reached": "First",
   "reachedTone": "neutral"
  }
 ],
 "duke-w-n2": [
  {
   "key": "16745",
   "name": "Guadalajara Open Akron - Guadalajara",
   "date": "2026-09-14",
   "surface": "Hard",
   "tier": "Tour",
   "matches": [
    {
     "id": "871491",
     "date": "2026-09-12",
     "roundId": 1,
     "round": "Q1",
     "won": false,
     "opponent": "Caroline Dolehide",
     "score": "6-0 6-4"
    }
   ],
   "reached": "Q1",
   "reachedTone": "neutral"
  }
 ],
 "lsu-m-n1": [
  {
   "key": "22035",
   "name": "San Diego 2 Challenger",
   "date": "2026-09-21",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "95005997",
     "date": "2026-09-20",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Quinn Vandecasteele",
     "score": "7-5 4-6 6-3"
    },
    {
     "id": "127174494",
     "date": "2026-09-21",
     "roundId": 3,
     "round": "Q3",
     "won": false,
     "opponent": "Timo Legout",
     "score": "6-3 6-1"
    }
   ],
   "reached": "Q3",
   "reachedTone": "neutral"
  },
  {
   "key": "22027",
   "name": "Tiburon Challenger",
   "date": "2026-09-14",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "1293390",
     "date": "2026-09-13",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Gus Grumet",
     "score": "6-2 6-2"
    },
    {
     "id": "1293374",
     "date": "2026-09-14",
     "roundId": 3,
     "round": "Q3",
     "won": false,
     "opponent": "Timo Legout",
     "score": "6-3 6-4"
    }
   ],
   "reached": "Q3",
   "reachedTone": "neutral"
  }
 ],
 "lsu-m-p2": [
  {
   "key": "22035",
   "name": "San Diego 2 Challenger",
   "date": "2026-09-21",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "90809981",
     "date": "2026-09-20",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Luca Staeheli",
     "score": "6-4 6-4"
    },
    {
     "id": "128573290",
     "date": "2026-09-21",
     "roundId": 3,
     "round": "Q3",
     "won": true,
     "opponent": "Andrew Fenty",
     "score": "6-3 6-3"
    }
   ],
   "reached": "Q3",
   "reachedTone": "neutral"
  },
  {
   "key": "22027",
   "name": "Tiburon Challenger",
   "date": "2026-09-14",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "1293381",
     "date": "2026-09-13",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Nicholas Godsick",
     "score": "6-3 6-1"
    },
    {
     "id": "1293389",
     "date": "2026-09-14",
     "roundId": 3,
     "round": "Q3",
     "won": true,
     "opponent": "Spencer Johnson",
     "score": "7-6(4) 7-6(6)"
    },
    {
     "id": "1293376",
     "date": "2026-09-15",
     "roundId": 4,
     "round": "First",
     "won": false,
     "opponent": "Braden Shick",
     "score": "6-3 6-4"
    }
   ],
   "reached": "First",
   "reachedTone": "neutral"
  }
 ],
 "lsu-p8": [
  {
   "key": "16746",
   "name": "SP Open - Sao Paulo",
   "date": "2026-09-14",
   "surface": "Hard",
   "tier": "Tour",
   "matches": [
    {
     "id": "871534",
     "date": "2026-09-12",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Ana Candiotto",
     "score": "6-3 6-4"
    },
    {
     "id": "871539",
     "date": "2026-09-13",
     "roundId": 3,
     "round": "Q3",
     "won": true,
     "opponent": "Hayu Kinoshita",
     "score": "7-5 7-6(9)"
    },
    {
     "id": "871535",
     "date": "2026-09-16",
     "roundId": 4,
     "round": "First",
     "won": false,
     "opponent": "Solana Sierra",
     "score": "6-4 3-6 6-1"
    }
   ],
   "reached": "First",
   "reachedTone": "neutral"
  },
  {
   "key": "17253",
   "name": "Kia Open - Barranquilla",
   "date": "2026-09-07",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "904735",
     "date": "2026-09-08",
     "roundId": 4,
     "round": "First",
     "won": false,
     "opponent": "Sara Sorribes Tormo",
     "score": "6-2 4-6 6-4"
    }
   ],
   "reached": "First",
   "reachedTone": "neutral"
  }
 ],
 "mich-m-p6": [
  {
   "key": "22131",
   "name": "Davis Cup, Group I, 1R, TPE-SWE 3-2",
   "date": "2026-09-14",
   "surface": "I.hard",
   "tier": "Davis/Fed Cup",
   "matches": [
    {
     "id": "86616341",
     "date": "2026-09-20",
     "roundId": 17,
     "round": "Rubber 5",
     "won": false,
     "opponent": "Tung-Lin Wu",
     "score": "6-4 6-4"
    }
   ],
   "reached": "Rubber 5",
   "reachedTone": "neutral"
  }
 ],
 "miss-m-p2": [
  {
   "key": "22036",
   "name": "Genoa 2 Challenger",
   "date": "2026-09-21",
   "surface": "Clay",
   "tier": "Challenger",
   "matches": [
    {
     "id": "85215269",
     "date": "2026-09-20",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Niccolo Ciavarella",
     "score": "6-2 7-6(3)"
    },
    {
     "id": "118782160",
     "date": "2026-09-21",
     "roundId": 3,
     "round": "Q3",
     "won": true,
     "opponent": "Lorenzo Rottoli",
     "score": "6-3 6-3"
    }
   ],
   "reached": "Q3",
   "reachedTone": "neutral"
  },
  {
   "key": "22030",
   "name": "Biella Challenger",
   "date": "2026-09-14",
   "surface": "Clay",
   "tier": "Challenger",
   "matches": [
    {
     "id": "1293526",
     "date": "2026-09-13",
     "roundId": 1,
     "round": "Q1",
     "won": false,
     "opponent": "Giuseppe La Vela",
     "score": "6-1 6-3"
    }
   ],
   "reached": "Q1",
   "reachedTone": "neutral"
  }
 ],
 "msu-m-p1": [
  {
   "key": "22054",
   "name": "M15 Monastir",
   "date": "2026-09-07",
   "surface": "Hard",
   "tier": "ITF",
   "matches": [
    {
     "id": "1294464",
     "date": "2026-09-09",
     "roundId": 4,
     "round": "First",
     "won": false,
     "opponent": "James Connel",
     "score": "6-3 6-4"
    }
   ],
   "reached": "First",
   "reachedTone": "neutral"
  }
 ],
 "ncst-m-fp370": [
  {
   "key": "22031",
   "name": "Phan Thiet 4 Challenger",
   "date": "2026-09-14",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "1293572",
     "date": "2026-09-13",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Yuta Kawahashi",
     "score": "6-3 4-0 ret."
    },
    {
     "id": "1293579",
     "date": "2026-09-14",
     "roundId": 3,
     "round": "Q3",
     "won": true,
     "opponent": "Dong Ju Kim",
     "score": "6-4 6-3"
    },
    {
     "id": "1293585",
     "date": "2026-09-15",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Dominik Palan",
     "score": "5-7 6-2 7-5"
    },
    {
     "id": "1293569",
     "date": "2026-09-17",
     "roundId": 5,
     "round": "Second",
     "won": false,
     "opponent": "Florent Bax",
     "score": "6-3 7-6(3)"
    }
   ],
   "reached": "Second",
   "reachedTone": "neutral"
  },
  {
   "key": "22025",
   "name": "Phan Thiet 3 Challenger",
   "date": "2026-09-07",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "1293251",
     "date": "2026-09-06",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Takuya Kumasaka",
     "score": "6-4 6-2"
    },
    {
     "id": "1293266",
     "date": "2026-09-07",
     "roundId": 3,
     "round": "Q3",
     "won": true,
     "opponent": "Ethan Cook",
     "score": "6-3 6-2"
    },
    {
     "id": "1293242",
     "date": "2026-09-08",
     "roundId": 4,
     "round": "First",
     "won": false,
     "opponent": "Koki Matsuda",
     "score": "7-5 7-6(4)"
    }
   ],
   "reached": "First",
   "reachedTone": "neutral"
  }
 ],
 "okst-w-p1": [
  {
   "key": "17273",
   "name": "W15 Campulung",
   "date": "2026-09-07",
   "surface": "Clay",
   "tier": "ITF",
   "matches": [
    {
     "id": "905441",
     "date": "2026-09-09",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Noemi La Cagnina",
     "score": "6-1 6-2"
    },
    {
     "id": "905444",
     "date": "2026-09-10",
     "roundId": 5,
     "round": "Second",
     "won": false,
     "opponent": "Cristiana Nicoleta Todoni",
     "score": "6-4 6-3"
    }
   ],
   "reached": "Second",
   "reachedTone": "neutral"
  }
 ],
 "osu-m-p7": [
  {
   "key": "22027",
   "name": "Tiburon Challenger",
   "date": "2026-09-14",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "1293382",
     "date": "2026-09-13",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Kaylan Bigun",
     "score": "7-5 6-0"
    },
    {
     "id": "1293365",
     "date": "2026-09-14",
     "roundId": 3,
     "round": "Q3",
     "won": true,
     "opponent": "Quinn Vandecasteele",
     "score": "6-2 6-4"
    },
    {
     "id": "1293359",
     "date": "2026-09-15",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Andre Ilagan",
     "score": "7-5 6-7(4) 7-6(3)"
    },
    {
     "id": "1293368",
     "date": "2026-09-17",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Timo Legout",
     "score": "7-6(6) 6-2"
    },
    {
     "id": "23670287",
     "date": "2026-09-18",
     "roundId": 9,
     "round": "QF",
     "won": false,
     "opponent": "Darwin Blanch",
     "score": "6-3 6-3"
    }
   ],
   "reached": "QF",
   "reachedTone": "neutral"
  }
 ],
 "ou-m-n4": [
  {
   "key": "22027",
   "name": "Tiburon Challenger",
   "date": "2026-09-14",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "1293369",
     "date": "2026-09-14",
     "roundId": 4,
     "round": "First",
     "won": false,
     "opponent": "Jeff Wolf",
     "score": "6-2 6-0"
    }
   ],
   "reached": "First",
   "reachedTone": "neutral"
  }
 ],
 "ou-m-p5": [
  {
   "key": "22123",
   "name": "Davis Cup, Group I, 1R, NED-COL 4-0",
   "date": "2026-09-14",
   "surface": "I.hard",
   "tier": "Davis/Fed Cup",
   "matches": [
    {
     "id": "53045046",
     "date": "2026-09-18",
     "roundId": 13,
     "round": "Rubber 1",
     "won": false,
     "opponent": "Botic Van De Zandschulp",
     "score": "4-6 6-1 7-5"
    }
   ],
   "reached": "Rubber 1",
   "reachedTone": "neutral"
  }
 ],
 "pepp-m-p6": [
  {
   "key": "22035",
   "name": "San Diego 2 Challenger",
   "date": "2026-09-21",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "132769715",
     "date": "2026-09-21",
     "roundId": 4,
     "round": "First",
     "won": false,
     "opponent": "Keegan Smith",
     "score": "6-3 4-6 6-2"
    }
   ],
   "reached": "First",
   "reachedTone": "neutral"
  },
  {
   "key": "22027",
   "name": "Tiburon Challenger",
   "date": "2026-09-14",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "1293372",
     "date": "2026-09-15",
     "roundId": 4,
     "round": "First",
     "won": false,
     "opponent": "Tristan Boyer",
     "score": "6-2 6-4"
    }
   ],
   "reached": "First",
   "reachedTone": "neutral"
  }
 ],
 "sc-m-p6": [
  {
   "key": "22024",
   "name": "Istanbul Challenger",
   "date": "2026-09-07",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "1293210",
     "date": "2026-09-08",
     "roundId": 4,
     "round": "First",
     "won": false,
     "opponent": "Max Basing",
     "score": "6-1 6-0"
    }
   ],
   "reached": "First",
   "reachedTone": "neutral"
  }
 ],
 "stan-m-fp374": [
  {
   "key": "22062",
   "name": "M25 Nevers",
   "date": "2026-09-14",
   "surface": "I.hard",
   "tier": "ITF",
   "matches": [
    {
     "id": "1295114",
     "date": "2026-09-16",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Noah Boutleux",
     "score": "6-1 6-3"
    },
    {
     "id": "1295127",
     "date": "2026-09-17",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Robin Eldin",
     "score": "6-3 7-5"
    },
    {
     "id": "34861353",
     "date": "2026-09-18",
     "roundId": 9,
     "round": "QF",
     "won": true,
     "opponent": "Loann Massard",
     "score": "6-4 6-3"
    },
    {
     "id": "57240920",
     "date": "2026-09-19",
     "roundId": 10,
     "round": "SF",
     "won": true,
     "opponent": "Andreja Petrovic",
     "score": "5-7 6-1 6-4"
    },
    {
     "id": "90811531",
     "date": "2026-09-20",
     "roundId": 12,
     "round": "Final",
     "won": false,
     "opponent": "Aidan Mchugh",
     "score": "6-4 6-4"
    }
   ],
   "reached": "Final",
   "reachedTone": "amber"
  },
  {
   "key": "22045",
   "name": "M25 Plaisir",
   "date": "2026-09-07",
   "surface": "I.hard",
   "tier": "ITF",
   "matches": [
    {
     "id": "1293698",
     "date": "2026-09-09",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Alexandre Reco",
     "score": "6-4 6-3"
    },
    {
     "id": "1293688",
     "date": "2026-09-10",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Karl Friberg",
     "score": "6-3 6-4"
    },
    {
     "id": "1293684",
     "date": "2026-09-11",
     "roundId": 9,
     "round": "QF",
     "won": true,
     "opponent": "Toby Martin",
     "score": "6-3 6-4"
    },
    {
     "id": "1293697",
     "date": "2026-09-12",
     "roundId": 10,
     "round": "SF",
     "won": true,
     "opponent": "Patrick Zahraj",
     "score": "7-5 6-3"
    },
    {
     "id": "1293709",
     "date": "2026-09-13",
     "roundId": 12,
     "round": "Final",
     "won": false,
     "opponent": "Clement Chidekh",
     "score": "7-6(5) 6-1"
    }
   ],
   "reached": "Final",
   "reachedTone": "amber"
  }
 ],
 "stan-m-fp423": [
  {
   "key": "22027",
   "name": "Tiburon Challenger",
   "date": "2026-09-14",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "1293381",
     "date": "2026-09-13",
     "roundId": 1,
     "round": "Q1",
     "won": false,
     "opponent": "Erik Arutiunian",
     "score": "6-3 6-1"
    }
   ],
   "reached": "Q1",
   "reachedTone": "neutral"
  }
 ],
 "stan-m-p5": [
  {
   "key": "22056",
   "name": "M15 Bali",
   "date": "2026-09-07",
   "surface": "Hard",
   "tier": "ITF",
   "matches": [
    {
     "id": "1294659",
     "date": "2026-09-08",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Kai-I Wang",
     "score": "6-2 6-2"
    },
    {
     "id": "1294652",
     "date": "2026-09-10",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Anton Shepp",
     "score": "6-4 6-3"
    },
    {
     "id": "1294650",
     "date": "2026-09-11",
     "roundId": 9,
     "round": "QF",
     "won": true,
     "opponent": "Isaac Becroft",
     "score": "6-4 2-6 7-6(4)"
    },
    {
     "id": "1294661",
     "date": "2026-09-12",
     "roundId": 10,
     "round": "SF",
     "won": false,
     "opponent": "Alexander Chang",
     "score": "3-6 6-1 6-4"
    }
   ],
   "reached": "SF",
   "reachedTone": "green"
  }
 ],
 "tcu-m-fp30": [
  {
   "key": "22027",
   "name": "Tiburon Challenger",
   "date": "2026-09-14",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "1293347",
     "date": "2026-09-13",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Li Tu",
     "score": "6-4 6-4"
    },
    {
     "id": "1293378",
     "date": "2026-09-14",
     "roundId": 3,
     "round": "Q3",
     "won": false,
     "opponent": "Luca Staeheli",
     "score": "4-6 6-2 6-3"
    }
   ],
   "reached": "Q3",
   "reachedTone": "neutral"
  }
 ],
 "tenn-m-n5": [
  {
   "key": "22055",
   "name": "M15 Budapest",
   "date": "2026-09-07",
   "surface": "Clay",
   "tier": "ITF",
   "matches": [
    {
     "id": "1294582",
     "date": "2026-09-09",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Matei Todoran",
     "score": "6-3 1-6 6-1"
    },
    {
     "id": "1294544",
     "date": "2026-09-10",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Rafael Kis Balazs",
     "score": "6-2 6-4"
    },
    {
     "id": "1294552",
     "date": "2026-09-11",
     "roundId": 9,
     "round": "QF",
     "won": false,
     "opponent": "Lilian Marmousez",
     "score": "6-1 6-3"
    }
   ],
   "reached": "QF",
   "reachedTone": "neutral"
  }
 ],
 "tenn-p3": [
  {
   "key": "17283",
   "name": "W15 Sao Luis",
   "date": "2026-09-14",
   "surface": "Clay",
   "tier": "ITF",
   "matches": [
    {
     "id": "906134",
     "date": "2026-09-15",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Manuela Maia Citolino",
     "score": "6-0 6-1"
    },
    {
     "id": "906118",
     "date": "2026-09-17",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Alicia Reichel",
     "score": "6-0 6-1"
    },
    {
     "id": "19311219",
     "date": "2026-09-18",
     "roundId": 9,
     "round": "QF",
     "won": true,
     "opponent": "Beatriz Nahmias Melo Rodrigues",
     "score": "6-4 6-2"
    },
    {
     "id": "49988856",
     "date": "2026-09-19",
     "roundId": 10,
     "round": "SF",
     "won": true,
     "opponent": "Julia Konishi Camargo Silva",
     "score": "6-1 6-3"
    },
    {
     "id": "79439201",
     "date": "2026-09-20",
     "roundId": 12,
     "round": "Final",
     "won": true,
     "opponent": "Ava Catanzarite",
     "score": "6-1 6-1"
    }
   ],
   "reached": "Title",
   "reachedTone": "gold"
  },
  {
   "key": "17275",
   "name": "W15 Pilar",
   "date": "2026-09-07",
   "surface": "Clay",
   "tier": "ITF",
   "matches": [
    {
     "id": "905586",
     "date": "2026-09-08",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Maria Navarro Oliva",
     "score": "6-4 6-0"
    },
    {
     "id": "905610",
     "date": "2026-09-10",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Michela Castro Zunino",
     "score": "6-2 6-1"
    },
    {
     "id": "905594",
     "date": "2026-09-11",
     "roundId": 9,
     "round": "QF",
     "won": false,
     "opponent": "Lourdes Ayala",
     "score": "6-0 6-3"
    }
   ],
   "reached": "QF",
   "reachedTone": "neutral"
  }
 ],
 "tenn-p6": [
  {
   "key": "16745",
   "name": "Guadalajara Open Akron - Guadalajara",
   "date": "2026-09-14",
   "surface": "Hard",
   "tier": "Tour",
   "matches": [
    {
     "id": "871460",
     "date": "2026-09-12",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Alexandra Panova",
     "score": "6-2 6-4"
    },
    {
     "id": "871487",
     "date": "2026-09-13",
     "roundId": 3,
     "round": "Q3",
     "won": false,
     "opponent": "Carole Monnet",
     "score": "7-6(6) 6-7(4) 6-2"
    }
   ],
   "reached": "Q3",
   "reachedTone": "neutral"
  },
  {
   "key": "17253",
   "name": "Kia Open - Barranquilla",
   "date": "2026-09-07",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "904729",
     "date": "2026-09-07",
     "roundId": 4,
     "round": "First",
     "won": false,
     "opponent": "Varvara Lepchenko",
     "score": "7-6(1) 6-1"
    }
   ],
   "reached": "First",
   "reachedTone": "neutral"
  }
 ],
 "tex-m-n3": [
  {
   "key": "22118",
   "name": "Davis Cup, World Group, Q2, GER-CRO 3-1",
   "date": "2026-09-14",
   "surface": "I.hard",
   "tier": "Davis/Fed Cup",
   "matches": [
    {
     "id": "75425713",
     "date": "2026-09-19",
     "roundId": 13,
     "round": "Rubber 1",
     "won": false,
     "opponent": "Alexander Zverev",
     "score": "6-4 7-6(3)"
    }
   ],
   "reached": "Rubber 1",
   "reachedTone": "neutral"
  },
  {
   "key": "22019",
   "name": "Genoa Challenger",
   "date": "2026-09-07",
   "surface": "Clay",
   "tier": "Challenger",
   "matches": [
    {
     "id": "1292849",
     "date": "2026-09-08",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Franco Agamenone",
     "score": "6-3 4-0 ret."
    },
    {
     "id": "1292850",
     "date": "2026-09-10",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Hugo Dellien",
     "score": "5-3 ret."
    },
    {
     "id": "1292860",
     "date": "2026-09-11",
     "roundId": 9,
     "round": "QF",
     "won": true,
     "opponent": "Enrico Dalla Valle",
     "score": "6-7(4) 6-2 7-6(5)"
    },
    {
     "id": "1292895",
     "date": "2026-09-12",
     "roundId": 10,
     "round": "SF",
     "won": false,
     "opponent": "Thiago Seyboth Wild",
     "score": "7-5 4-6 6-2"
    }
   ],
   "reached": "SF",
   "reachedTone": "green"
  },
  {
   "key": "21941",
   "name": "Como Challenger",
   "date": "2026-08-31",
   "surface": "Clay",
   "tier": "Challenger",
   "matches": [
    {
     "id": "1286543",
     "date": "2026-08-31",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Mili Poljicak",
     "score": "6-2 6-3"
    },
    {
     "id": "1286557",
     "date": "2026-09-02",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Henry Bernet",
     "score": "6-7(1) 7-6(3) 7-5"
    },
    {
     "id": "1286553",
     "date": "2026-09-04",
     "roundId": 9,
     "round": "QF",
     "won": true,
     "opponent": "Max Schoenhaus",
     "score": "2-6 7-6(1) 6-3"
    },
    {
     "id": "1286514",
     "date": "2026-09-05",
     "roundId": 10,
     "round": "SF",
     "won": true,
     "opponent": "Johan Nikles",
     "score": "6-3 6-0"
    },
    {
     "id": "1286510",
     "date": "2026-09-06",
     "roundId": 12,
     "round": "Final",
     "won": true,
     "opponent": "Juan Pablo Varillas",
     "score": "6-3 7-6(5)"
    }
   ],
   "reached": "Title",
   "reachedTone": "gold"
  }
 ],
 "uga-p7": [
  {
   "key": "17260",
   "name": "Ankara Open - Ankara",
   "date": "2026-09-21",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "106430859",
     "date": "2026-09-21",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Isabella Shinikova",
     "score": "4-6 6-1 6-3"
    }
   ],
   "reached": "First",
   "reachedTone": "neutral"
  }
 ],
 "usc-m-p3": [
  {
   "key": "22009",
   "name": "M15 Kursumlijska Banja",
   "date": "2026-08-31",
   "surface": "Clay",
   "tier": "ITF",
   "matches": [
    {
     "id": "1292028",
     "date": "2026-09-02",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Maxim Khorozov",
     "score": "6-1 6-1"
    },
    {
     "id": "1292014",
     "date": "2026-09-03",
     "roundId": 5,
     "round": "Second",
     "won": true,
     "opponent": "Alessandro Bellifemine",
     "score": "6-3 6-2"
    },
    {
     "id": "1292033",
     "date": "2026-09-04",
     "roundId": 9,
     "round": "QF",
     "won": true,
     "opponent": "Antoni Fabre",
     "score": "6-7(8) 6-4 6-4"
    },
    {
     "id": "1292046",
     "date": "2026-09-05",
     "roundId": 10,
     "round": "SF",
     "won": true,
     "opponent": "Nikita Bilozertsev",
     "score": "6-1 6-2"
    },
    {
     "id": "1292008",
     "date": "2026-09-06",
     "roundId": 12,
     "round": "Final",
     "won": true,
     "opponent": "Dmitry Popko",
     "score": "6-7(3) 6-2 6-4"
    }
   ],
   "reached": "Title",
   "reachedTone": "gold"
  }
 ],
 "usf-m-p3": [
  {
   "key": "22077",
   "name": "M15 Curitiba",
   "date": "2026-09-21",
   "surface": "Clay",
   "tier": "ITF",
   "matches": [
    {
     "id": "106197257",
     "date": "2026-09-20",
     "roundId": 1,
     "round": "Q1",
     "won": true,
     "opponent": "Andrey Barbiero",
     "score": "6-2 6-1"
    }
   ],
   "reached": "Q1",
   "reachedTone": "neutral"
  }
 ],
 "uva-m-p2": [
  {
   "key": "22035",
   "name": "San Diego 2 Challenger",
   "date": "2026-09-21",
   "surface": "Hard",
   "tier": "Challenger",
   "matches": [
    {
     "id": "129972102",
     "date": "2026-09-21",
     "roundId": 4,
     "round": "First",
     "won": true,
     "opponent": "Dinko Dinev",
     "score": "6-3 6-1"
    }
   ],
   "reached": "First",
   "reachedTone": "neutral"
  }
 ],
 "wake-m-fp302": [
  {
   "key": "22115",
   "name": "Davis Cup, World Group, Q2, KOR-IND 3-1",
   "date": "2026-09-14",
   "surface": "Hard",
   "tier": "Davis/Fed Cup",
   "matches": [
    {
     "id": "6889432",
     "date": "2026-09-18",
     "roundId": 13,
     "round": "Rubber 1",
     "won": false,
     "opponent": "Soon-Woo Kwon",
     "score": "3-6 6-3 6-4"
    }
   ],
   "reached": "Rubber 1",
   "reachedTone": "neutral"
  }
 ]
};
