// GENERATED by scripts/build-upcoming.mjs -- do not edit by hand.
// "Coming up": SEC players with a SCHEDULED pro match today or tomorrow, from
// the LIVE fixtures endpoint (the only forward-looking source, ~1 day out, ITF
// included). Opponent + event, no result yet. Re-run the script to refresh.
export const upcoming = globalThis.__BAGEL_REMOTE__?.["upcoming"]?.upcoming ?? [
 {
  "playerId": "unc-w-n1",
  "name": "Alexis Nguyen",
  "teamId": "unc-w",
  "gender": "women",
  "opponent": "Catherine Rennard",
  "event": "W50 Lexington",
  "date": "2026-10-05",
  "day": "today"
 },
 {
  "playerId": "unc-w-p4",
  "name": "Anna Frey",
  "teamId": "unc-w",
  "gender": "women",
  "opponent": "Bella Bergkvist Larsson",
  "event": "W50 Lexington",
  "date": "2026-10-05",
  "day": "today"
 },
 {
  "playerId": "sc-p1",
  "name": "Bella Bergqvist Larsson",
  "teamId": "sc-w",
  "gender": "women",
  "opponent": "Anna Frey",
  "event": "W50 Lexington",
  "date": "2026-10-05",
  "day": "today"
 },
 {
  "playerId": "wake-m-h24",
  "name": "Borna Gojo",
  "teamId": "wake-m",
  "gender": "men",
  "opponent": "Maxi Carrascosa Diaz",
  "event": "Villena Challenger",
  "date": "2026-10-05",
  "day": "today"
 },
 {
  "playerId": "wake-w-n2",
  "name": "Catherine Rennard",
  "teamId": "wake-w",
  "gender": "women",
  "opponent": "Alexis Nguyen",
  "event": "W50 Lexington",
  "date": "2026-10-05",
  "day": "today"
 },
 {
  "playerId": "aub-p5",
  "name": "Eva Ionescu",
  "teamId": "aub-w",
  "gender": "women",
  "opponent": "Maria Kononova",
  "event": "W50 Lexington",
  "date": "2026-10-05",
  "day": "today"
 },
 {
  "playerId": "wake-m-h3",
  "name": "Filippo Moroni",
  "teamId": "wake-m",
  "gender": "men",
  "opponent": "Ignacio Parisca",
  "event": "Palermo Challenger",
  "date": "2026-10-05",
  "day": "today"
 },
 {
  "playerId": "sc-p3",
  "name": "Helena Buchwald",
  "teamId": "sc-w",
  "gender": "women",
  "opponent": "Tatum Evans",
  "event": "W50 Lexington",
  "date": "2026-10-05",
  "day": "today"
 },
 {
  "playerId": "tcu-m-h8",
  "name": "Jack Pinnington",
  "teamId": "tcu-m",
  "gender": "men",
  "opponent": "Diego Dedura",
  "event": "Villena Challenger",
  "date": "2026-10-05",
  "day": "today"
 },
 {
  "playerId": "sc-p6",
  "name": "Jane Dunyon",
  "teamId": "sc-w",
  "gender": "women",
  "opponent": "Pietra Rivoli",
  "event": "W50 Lexington",
  "date": "2026-10-05",
  "day": "today"
 },
 {
  "playerId": "tcu-w-p6",
  "name": "Kira Matushkina",
  "teamId": "tcu-w",
  "gender": "women",
  "opponent": "Megan Heuser",
  "event": "W50 Lexington",
  "date": "2026-10-05",
  "day": "today"
 },
 {
  "playerId": "ncst-w-p7",
  "name": "Mia Slama",
  "teamId": "ncst-w",
  "gender": "women",
  "opponent": "Kate Sharabura",
  "event": "W50 Lexington",
  "date": "2026-10-05",
  "day": "today"
 },
 {
  "playerId": "sc-w-n2",
  "name": "Mika Buchnik",
  "teamId": "sc-w",
  "gender": "women",
  "opponent": "Maria Herazo",
  "event": "W50 Heraklion",
  "date": "2026-10-05",
  "day": "today"
 },
 {
  "playerId": "sc-w-h3",
  "name": "Misa Malkin",
  "teamId": "sc-w",
  "gender": "women",
  "opponent": "Amaliia Elizarova",
  "event": "W50 Lexington",
  "date": "2026-10-05",
  "day": "today"
 },
 {
  "playerId": "sc-w-n3",
  "name": "Pietra Rivoli",
  "teamId": "sc-w",
  "gender": "women",
  "opponent": "Jane Dunyon",
  "event": "W50 Lexington",
  "date": "2026-10-05",
  "day": "today"
 },
 {
  "playerId": "unc-w-p3",
  "name": "Tatum Evans",
  "teamId": "unc-w",
  "gender": "women",
  "opponent": "Helena Buchwald",
  "event": "W50 Lexington",
  "date": "2026-10-05",
  "day": "today"
 },
 {
  "playerId": "ncst-w-p6",
  "name": "Victoria Osuigwe",
  "teamId": "ncst-w",
  "gender": "women",
  "opponent": "Carlota Moreno",
  "event": "W50 Lexington",
  "date": "2026-10-05",
  "day": "today"
 },
 {
  "playerId": "fla-m-h9",
  "name": "Abedallah Shelbayh",
  "teamId": "fla-m",
  "gender": "men",
  "opponent": "David Jorda Sanchis",
  "event": "Villena Challenger",
  "date": "2026-10-06",
  "day": "tomorrow"
 },
 {
  "playerId": "temple-m-n1",
  "name": "Adrien Ducruet",
  "teamId": "temple-m",
  "gender": "men",
  "opponent": "Max Purcell",
  "event": "Wuning 3 Challenger",
  "date": "2026-10-06",
  "day": "tomorrow"
 },
 {
  "playerId": "fla-w-h4",
  "name": "Alicia Dudeney",
  "teamId": "fla-w",
  "gender": "women",
  "opponent": "Antonia Ruzic",
  "event": "Samsun Open - Samsun",
  "date": "2026-10-06",
  "day": "tomorrow"
 },
 {
  "playerId": "usd-m-h8",
  "name": "August Holmgren",
  "teamId": "usd-m",
  "gender": "men",
  "opponent": "Pedro Martinez Portero",
  "event": "Villena Challenger",
  "date": "2026-10-06",
  "day": "tomorrow"
 },
 {
  "playerId": "uga-p7",
  "name": "Aysegul Mert",
  "teamId": "uga-w",
  "gender": "women",
  "opponent": "Viktoria Hruncakova",
  "event": "Samsun Open - Samsun",
  "date": "2026-10-06",
  "day": "tomorrow"
 },
 {
  "playerId": "msst-m-p8",
  "name": "Benito Sanchez Martinez",
  "teamId": "msst-m",
  "gender": "men",
  "opponent": "Michele Ribecai",
  "event": "Palermo Challenger",
  "date": "2026-10-06",
  "day": "tomorrow"
 },
 {
  "playerId": "tcu-m-h11",
  "name": "Cameron Norrie",
  "teamId": "tcu-m",
  "gender": "men",
  "opponent": "Denis Shapovalov",
  "event": "Shanghai Rolex Masters - Shanghai",
  "date": "2026-10-06",
  "day": "tomorrow"
 },
 {
  "playerId": "uga-w-h7",
  "name": "Dasha Vidmanova",
  "teamId": "uga-w",
  "gender": "women",
  "opponent": "Kyoka Okamura",
  "event": "Suzhou WTA 125 - Suzhou",
  "date": "2026-10-06",
  "day": "tomorrow"
 },
 {
  "playerId": "msst-m-h9",
  "name": "Florian Broska",
  "teamId": "msst-m",
  "gender": "men",
  "opponent": "Lukas Neumayer",
  "event": "Braga Challenger",
  "date": "2026-10-06",
  "day": "tomorrow"
 },
 {
  "playerId": "ariz-m-fp226",
  "name": "Jay Friend",
  "teamId": "ariz-m",
  "gender": "men",
  "opponent": "Yuta Kikuchi",
  "event": "Wuning 3 Challenger",
  "date": "2026-10-06",
  "day": "tomorrow"
 },
 {
  "playerId": "ucla-m-h15",
  "name": "Keegan Smith",
  "teamId": "ucla-m",
  "gender": "men",
  "opponent": "Hiroki Moriya",
  "event": "Wuning 3 Challenger",
  "date": "2026-10-06",
  "day": "tomorrow"
 },
 {
  "playerId": "uk-m-h1",
  "name": "Liam Draxl",
  "teamId": "uk-m",
  "gender": "men",
  "opponent": "Nikoloz Basilashvili",
  "event": "Shanghai Rolex Masters - Shanghai",
  "date": "2026-10-06",
  "day": "tomorrow"
 },
 {
  "playerId": "okst-w-h10",
  "name": "Mananchaya Sawangkaew",
  "teamId": "okst-w",
  "gender": "women",
  "opponent": "Linda Fruhvirtova",
  "event": "Suzhou WTA 125 - Suzhou",
  "date": "2026-10-06",
  "day": "tomorrow"
 },
 {
  "playerId": "ucla-m-h13",
  "name": "Marcos Giron",
  "teamId": "ucla-m",
  "gender": "men",
  "opponent": "Sebastian Baez",
  "event": "Shanghai Rolex Masters - Shanghai",
  "date": "2026-10-06",
  "day": "tomorrow"
 },
 {
  "playerId": "ncst-m-fp370",
  "name": "Martin Borisiouk",
  "teamId": "ncst-m",
  "gender": "men",
  "opponent": "Omar Jasika",
  "event": "Wuning 3 Challenger",
  "date": "2026-10-06",
  "day": "tomorrow"
 },
 {
  "playerId": "tex-m-n3",
  "name": "Matej Dodig",
  "teamId": "tex-m",
  "gender": "men",
  "opponent": "Andrea Pellegrino",
  "event": "Braga Challenger",
  "date": "2026-10-06",
  "day": "tomorrow"
 },
 {
  "playerId": "bay-m-h11",
  "name": "Matias Soto",
  "teamId": "bay-m",
  "gender": "men",
  "opponent": "Thiago Seyboth Wild",
  "event": "Antofagasta Challenger",
  "date": "2026-10-06",
  "day": "tomorrow"
 },
 {
  "playerId": "mich-m-p8",
  "name": "Pierce Shaya",
  "teamId": "mich-m",
  "gender": "men",
  "opponent": "Mitsuki Wei Kang Leong",
  "event": "Wuning 3 Challenger",
  "date": "2026-10-06",
  "day": "tomorrow"
 },
 {
  "playerId": "unc-m-h9",
  "name": "Ryan Seggerman",
  "teamId": "unc-m",
  "gender": "men",
  "opponent": "Hikaru Shiraishi",
  "event": "Wuning 3 Challenger",
  "date": "2026-10-06",
  "day": "tomorrow"
 },
 {
  "playerId": "usc-m-h13",
  "name": "Yannick Hanfmann",
  "teamId": "usc-m",
  "gender": "men",
  "opponent": "Kamil Majchrzak",
  "event": "Shanghai Rolex Masters - Shanghai",
  "date": "2026-10-06",
  "day": "tomorrow"
 },
 {
  "playerId": "cal-m-h3",
  "name": "Yuta Kikuchi",
  "teamId": "cal-m",
  "gender": "men",
  "opponent": "Jay Dylan Hara Friend",
  "event": "Wuning 3 Challenger",
  "date": "2026-10-06",
  "day": "tomorrow"
 }
];

export const upcomingDates = globalThis.__BAGEL_REMOTE__?.["upcoming"]?.upcomingDates ?? ["2026-10-05","2026-10-06"];

// Scheduled matches for a gender, soonest first (today before tomorrow).
export function getUpcoming(gender) {
  return gender ? upcoming.filter((r) => r.gender === gender) : upcoming;
}

export default upcoming;
