// GENERATED by scripts/build-upcoming.mjs -- do not edit by hand.
// "Coming up": SEC players with a SCHEDULED pro match today or tomorrow, from
// the LIVE fixtures endpoint (the only forward-looking source, ~1 day out, ITF
// included). Opponent + event, no result yet. Re-run the script to refresh.
export const upcoming = globalThis.__BAGEL_REMOTE__?.["upcoming"]?.upcoming ?? [
 {
  "playerId": "fla-m-h9",
  "name": "Abedallah Shelbayh",
  "teamId": "fla-m",
  "gender": "men",
  "opponent": "Daniil Ostapenkov",
  "event": "Columbus Challenger",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "bay-m-h12",
  "name": "Adrian Boitan",
  "teamId": "bay-m",
  "gender": "men",
  "opponent": "Cezar Stefan Bentzel",
  "event": "M25 Slobozia",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "ou-m-p3",
  "name": "Alejandro Melero",
  "teamId": "ou-m",
  "gender": "men",
  "opponent": "Johan Alexander Rodriguez",
  "event": "M15 Fayetteville",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "fla-w-h4",
  "name": "Alicia Dudeney",
  "teamId": "fla-w",
  "gender": "women",
  "opponent": "Linda Klimovicova",
  "event": "W75 Quinta do Lago",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "usf-m-h4",
  "name": "Alvin Tudorica",
  "teamId": "usf-m",
  "gender": "men",
  "opponent": "Neo Niedner",
  "event": "M15 Fayetteville",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "haw-m-h2",
  "name": "Andre Ilagan",
  "teamId": "haw-m",
  "gender": "men",
  "opponent": "Marat Sharipov (RUS)",
  "event": "Jingshan Challenger",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "uga-m-p1",
  "name": "Arda Azkara",
  "teamId": "uga-m",
  "gender": "men",
  "opponent": "Rohan Mehra",
  "event": "M15 Baku",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "tamu-m-h20",
  "name": "Arthur Rinderknech",
  "teamId": "tamu-m",
  "gender": "men",
  "opponent": "Alex Molcan",
  "event": "China Open - Beijing",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "wake-m-p6",
  "name": "Aryan Shah",
  "teamId": "wake-m",
  "gender": "men",
  "opponent": "Evan Bynoe",
  "event": "M15 Fayetteville",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "aub-p2",
  "name": "Ashton Bowers",
  "teamId": "aub-w",
  "gender": "women",
  "opponent": "Stefani Webb",
  "event": "W15 Nashville",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "wash-w-h8",
  "name": "Astrid Olsen",
  "teamId": "wash-w",
  "gender": "women",
  "opponent": "Patricia Georgiana Goina",
  "event": "W15 Varna",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "usd-m-h8",
  "name": "August Holmgren",
  "teamId": "usd-m",
  "gender": "men",
  "opponent": "Andrea Guerrieri",
  "event": "Porto Challenger",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "osu-m-p7",
  "name": "Bryce Nakashima",
  "teamId": "osu-m",
  "gender": "men",
  "opponent": "Keegan Smith",
  "event": "Columbus Challenger",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "lsu-p8",
  "name": "Cadence Brace",
  "teamId": "lsu-w",
  "gender": "women",
  "opponent": "Alba Rey Garcia",
  "event": "W35 Baza",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "tcu-m-h11",
  "name": "Cameron Norrie",
  "teamId": "tcu-m",
  "gender": "men",
  "opponent": "Alexander Zverev",
  "event": "China Open - Beijing",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "msst-m-h4",
  "name": "Carles Hernandez",
  "teamId": "msst-m",
  "gender": "men",
  "opponent": "Samir Hamza Reguig",
  "event": "M15 Monastir",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "pur-w-h6",
  "name": "Carmen Gallardo Guevara",
  "teamId": "pur-w",
  "gender": "women",
  "opponent": "Celia Cervino Ruiz",
  "event": "W35 Baza",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "lsu-p5",
  "name": "Carolina Kuhl",
  "teamId": "lsu-w",
  "gender": "women",
  "opponent": "Kristina Penickova",
  "event": "W100 Templeton",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "msst-p2",
  "name": "Chiara Di Genova",
  "teamId": "msst-w",
  "gender": "women",
  "opponent": "Valeria Ray",
  "event": "W15 Nashville",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "wash-m-h10",
  "name": "Clement Chidekh",
  "teamId": "wash-m",
  "gender": "men",
  "opponent": "Ugo Blanchet",
  "event": "Mouilleron-Le-Captif Challenger",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "ariz-m-h3",
  "name": "Colton Smith",
  "teamId": "ariz-m",
  "gender": "men",
  "opponent": "Aidan Mayo",
  "event": "Columbus Challenger",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "lsu-m-n1",
  "name": "Daniil Ostapenkov",
  "teamId": "lsu-m",
  "gender": "men",
  "opponent": "Abedallah Shelbayh",
  "event": "Columbus Challenger",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "okst-m-p6",
  "name": "Derek Pham",
  "teamId": "okst-m",
  "gender": "men",
  "opponent": "Jeremy Beale",
  "event": "M25 Darwin",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "ou-m-n1",
  "name": "Dragos Cazacu",
  "teamId": "ou-m",
  "gender": "men",
  "opponent": "Alexander Rozin",
  "event": "M15 Fayetteville",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "lsu-p1",
  "name": "Ella McDonald",
  "teamId": "lsu-w",
  "gender": "women",
  "opponent": "Whitney Osuigwe",
  "event": "W100 Templeton",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "aub-p6",
  "name": "Emma Kamper",
  "teamId": "aub-w",
  "gender": "women",
  "opponent": "Kristina Paskauskas",
  "event": "W15 Nashville",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "tenn-w-h3",
  "name": "Esther Adeshina",
  "teamId": "tenn-w",
  "gender": "women",
  "opponent": "Hania Abouelsaad",
  "event": "W15 Sharm ElSheikh",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "tex-p9",
  "name": "Eszter Meri",
  "teamId": "tex-w",
  "gender": "women",
  "opponent": "Astra Sharma",
  "event": "W15 Nashville",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "corn-m-h11",
  "name": "Evan Bynoe",
  "teamId": "corn-m",
  "gender": "men",
  "opponent": "Aryan Shah",
  "event": "M15 Fayetteville",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "msst-m-h1",
  "name": "Ewen Lumsden",
  "teamId": "msst-m",
  "gender": "men",
  "opponent": "Jack Loge",
  "event": "M15 Monastir",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "wich-m-fp92",
  "name": "Felix Bockelmann Evans",
  "teamId": "wich-m",
  "gender": "men",
  "opponent": "Stefan Kozlov",
  "event": "Columbus Challenger",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "ala-m-h4",
  "name": "Filip Planinsek",
  "teamId": "ala-m",
  "gender": "men",
  "opponent": "Borys Zgola",
  "event": "M25 Slobozia",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "ou-w-h9",
  "name": "Florencia Urrutia",
  "teamId": "ou-w",
  "gender": "women",
  "opponent": "Caira Delfina Vega Gudino",
  "event": "W15 Trelew",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "msst-m-h9",
  "name": "Florian Broska",
  "teamId": "msst-m",
  "gender": "men",
  "opponent": "Rares Teodor Pieleanu",
  "event": "M25 Slobozia",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "tenn-p5",
  "name": "Francesca Mattioli",
  "teamId": "tenn-w",
  "gender": "women",
  "opponent": "Rose Marie Nijkamp",
  "event": "W15 Nashville",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "ariz-m-h1",
  "name": "Herman Hoeyeraal",
  "teamId": "ariz-m",
  "gender": "men",
  "opponent": "Reece Falck",
  "event": "M25 Darwin",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "van-m-p8",
  "name": "Hoyoung Roh",
  "teamId": "van-m",
  "gender": "men",
  "opponent": "Charlie Robertson",
  "event": "M15 Fayetteville",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "van-m-p2",
  "name": "Hugo Coquelin",
  "teamId": "van-m",
  "gender": "men",
  "opponent": "Micah Braswell",
  "event": "M15 Ann Arbor",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "uva-m-h4",
  "name": "Inaki Montes de la Torre",
  "teamId": "uva-m",
  "gender": "men",
  "opponent": "Jacob Fearnley",
  "event": "Porto Challenger",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "okst-m-h5",
  "name": "Isaac Becroft",
  "teamId": "okst-m",
  "gender": "men",
  "opponent": "Yua Taka",
  "event": "M15 Luan",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "tcu-m-h1",
  "name": "Jacob Fearnley",
  "teamId": "tcu-m",
  "gender": "men",
  "opponent": "Inaki Montes-De La Torre",
  "event": "Porto Challenger",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "uva-m-h6",
  "name": "Jeffrey von der Schulenburg",
  "teamId": "uva-m",
  "gender": "men",
  "opponent": "Michel Hopp",
  "event": "M15 Sibenik",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "ou-m-p5",
  "name": "Johan Rodriguez",
  "teamId": "ou-m",
  "gender": "men",
  "opponent": "Alejandro Melero Kretzer",
  "event": "M15 Fayetteville",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "miss-m-h3",
  "name": "John Hallquist Lithen",
  "teamId": "miss-m",
  "gender": "men",
  "opponent": "Benjamin Azar",
  "event": "M15 Ann Arbor",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "tex-m-p2",
  "name": "Jonah Braswell",
  "teamId": "tex-m",
  "gender": "men",
  "opponent": "Jordan Lee",
  "event": "M15 Fayetteville",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "ou-m-h2",
  "name": "Jordan Hasson",
  "teamId": "ou-m",
  "gender": "men",
  "opponent": "Millen Hurrion",
  "event": "M15 Baku",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "ucla-m-h15",
  "name": "Keegan Smith",
  "teamId": "ucla-m",
  "gender": "men",
  "opponent": "Bryce Nakashima",
  "event": "Columbus Challenger",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "okst-w-h2",
  "name": "Kristina Novak",
  "teamId": "okst-w",
  "gender": "women",
  "opponent": "Nahia Berecoechea",
  "event": "W35 Baza",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "tamu-w-n1",
  "name": "Kristina Paskauskas",
  "teamId": "tamu-w",
  "gender": "women",
  "opponent": "Emma Kamper Malmkjaer",
  "event": "W15 Nashville",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "okst-w-h7",
  "name": "Kylie Collins",
  "teamId": "okst-w",
  "gender": "women",
  "opponent": "Francisca Jorge",
  "event": "W75 Quinta do Lago",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "corn-w-h13",
  "name": "Lan Mi",
  "teamId": "corn-w",
  "gender": "women",
  "opponent": "Ophelie Boullay",
  "event": "W15 Monastir",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "usc-m-h8",
  "name": "Learner Tien",
  "teamId": "usc-m",
  "gender": "men",
  "opponent": "Hubert Hurkacz",
  "event": "China Open - Beijing",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "tenn-p3",
  "name": "Leyla Britez Risso",
  "teamId": "tenn-w",
  "gender": "women",
  "opponent": "Maria Sofia Madrid Rocca",
  "event": "W15 Trelew",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "tex-w-h5",
  "name": "Malaika Rapolu",
  "teamId": "tex-w",
  "gender": "women",
  "opponent": "Akasha Urhobo",
  "event": "W100 Templeton",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "clem-m-fp162",
  "name": "Manuel Plunger",
  "teamId": "clem-m",
  "gender": "men",
  "opponent": "Corentin Denolly",
  "event": "M25 Kigali",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "clem-m-p6",
  "name": "Marko Mesarovic",
  "teamId": "clem-m",
  "gender": "men",
  "opponent": "Oliver Bonding",
  "event": "M15 Ann Arbor",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "mich-m-p6",
  "name": "Max Dahlin",
  "teamId": "mich-m",
  "gender": "men",
  "opponent": "Alexander Bernard",
  "event": "M15 Ann Arbor",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "aub-p10",
  "name": "Merna Refaat",
  "teamId": "aub-w",
  "gender": "women",
  "opponent": "Sophia Webster",
  "event": "W15 Nashville",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "tex-m-h2",
  "name": "Micah Braswell",
  "teamId": "tex-m",
  "gender": "men",
  "opponent": "Hugo Coquelin",
  "event": "M15 Ann Arbor",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "uk-m-h10",
  "name": "Millen Hurrion",
  "teamId": "uk-m",
  "gender": "men",
  "opponent": "Jordan Hasson",
  "event": "M15 Baku",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "usd-m-p6",
  "name": "Neo Niedner",
  "teamId": "usd-m",
  "gender": "men",
  "opponent": "Alvin Nicholas Tudorica",
  "event": "M15 Fayetteville",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "fau-m-h11",
  "name": "Nicolas Jadoun",
  "teamId": "fau-m",
  "gender": "men",
  "opponent": "James Connel",
  "event": "M15 Baku",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "asu-m-p10",
  "name": "Nikola Djosic",
  "teamId": "asu-m",
  "gender": "men",
  "opponent": "Thanaphat Boosarawongse",
  "event": "M15 Ann Arbor",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "mich-m-h4",
  "name": "Nino Ehrenschneider",
  "teamId": "mich-m",
  "gender": "men",
  "opponent": "James Van Herzeele",
  "event": "M15 Luan",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "lsu-m-p1",
  "name": "Olaf Pieczkowski",
  "teamId": "lsu-m",
  "gender": "men",
  "opponent": "Max Sheldon",
  "event": "M15 Ann Arbor",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "duke-m-fp157",
  "name": "Pedro Rodenas",
  "teamId": "duke-m",
  "gender": "men",
  "opponent": "Nicolas Ifi",
  "event": "M25 Zaragoza",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "corn-m-h6",
  "name": "Radu Papoe",
  "teamId": "corn-m",
  "gender": "men",
  "opponent": "Vladislav Melnic",
  "event": "M25 Slobozia",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "uva-m-h12",
  "name": "Rafael Jodar",
  "teamId": "uva-m",
  "gender": "men",
  "opponent": "Adolfo Daniel Vallejo",
  "event": "Japan Open Tennis Championships - Tokyo",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "tcu-w-p1",
  "name": "Raquel Caballero Chica",
  "teamId": "tcu-w",
  "gender": "women",
  "opponent": "Ashley Lahey",
  "event": "W15 Nashville",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "tulsa-m-p5",
  "name": "Reiya Komagata",
  "teamId": "tulsa-m",
  "gender": "men",
  "opponent": "Ryuki Matsuda",
  "event": "M15 Luan",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "tex-w-n1",
  "name": "Rose Marie Nijkamp",
  "teamId": "tex-w",
  "gender": "women",
  "opponent": "Francesca Mattioli",
  "event": "W15 Nashville",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "tex-p4",
  "name": "Salma Drugdova",
  "teamId": "tex-w",
  "gender": "women",
  "opponent": "Carlota Moreno",
  "event": "W15 Nashville",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "ucf-w-h5",
  "name": "Sophia Biolay",
  "teamId": "ucf-w",
  "gender": "women",
  "opponent": "Ella Haavisto",
  "event": "W15 Monastir",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "van-p8",
  "name": "Sophia Webster",
  "teamId": "van-w",
  "gender": "women",
  "opponent": "Merna Refaat",
  "event": "W15 Nashville",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "tenn-w-n5",
  "name": "Stefani Webb",
  "teamId": "tenn-w",
  "gender": "women",
  "opponent": "Ashton Bowers",
  "event": "W15 Nashville",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "tamu-m-p4",
  "name": "Theo Papamalamis",
  "teamId": "tamu-m",
  "gender": "men",
  "opponent": "Tito Chavez",
  "event": "M15 Fayetteville",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "sc-m-h4",
  "name": "Toby Samuel",
  "teamId": "sc-m",
  "gender": "men",
  "opponent": "Jerome Kym",
  "event": "Porto Challenger",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "cal-w-h2",
  "name": "Valentina Ivanov",
  "teamId": "cal-w",
  "gender": "women",
  "opponent": "Alba Maria Coromina Boluda",
  "event": "W35 Baza",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "van-p5",
  "name": "Valeria Ray",
  "teamId": "van-w",
  "gender": "women",
  "opponent": "Chiara Di Genova",
  "event": "W15 Nashville",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "unc-m-h2",
  "name": "Vladislav Melnic",
  "teamId": "unc-m",
  "gender": "men",
  "opponent": "Radu Mihai Papoe",
  "event": "M25 Slobozia",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "miss-m-p3",
  "name": "Vlado Jankanj",
  "teamId": "miss-m",
  "gender": "men",
  "opponent": "Dominick Mosejczuk",
  "event": "M15 Fayetteville",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "asu-m-p9",
  "name": "Xavi Palomar",
  "teamId": "asu-m",
  "gender": "men",
  "opponent": "Miguel Damas",
  "event": "M25 Zaragoza",
  "date": "2026-10-01",
  "day": "today"
 },
 {
  "playerId": "fla-m-h11",
  "name": "Andres Andrade",
  "teamId": "fla-m",
  "gender": "men",
  "opponent": "Mees Rottgering",
  "event": "Columbus Challenger",
  "date": "2026-10-02",
  "day": "tomorrow"
 },
 {
  "playerId": "ncst-w-h8",
  "name": "Diana Shnaider",
  "teamId": "ncst-w",
  "gender": "women",
  "opponent": "Janice Tjen",
  "event": "China Open - Beijing",
  "date": "2026-10-02",
  "day": "tomorrow"
 },
 {
  "playerId": "uva-m-p2",
  "name": "Dylan Dietrich",
  "teamId": "uva-m",
  "gender": "men",
  "opponent": "Darwin Blanch",
  "event": "Columbus Challenger",
  "date": "2026-10-02",
  "day": "tomorrow"
 },
 {
  "playerId": "pepp-w-h4",
  "name": "Janice Tjen",
  "teamId": "pepp-w",
  "gender": "women",
  "opponent": "Diana Shnaider",
  "event": "China Open - Beijing",
  "date": "2026-10-02",
  "day": "tomorrow"
 },
 {
  "playerId": "wake-m-p5",
  "name": "Mees Rottgering",
  "teamId": "wake-m",
  "gender": "men",
  "opponent": "Andres Andrade",
  "event": "Columbus Challenger",
  "date": "2026-10-02",
  "day": "tomorrow"
 },
 {
  "playerId": "tex-w-h12",
  "name": "Peyton Stearns",
  "teamId": "tex-w",
  "gender": "women",
  "opponent": "Viktorija Golubic",
  "event": "China Open - Beijing",
  "date": "2026-10-02",
  "day": "tomorrow"
 }
];

export const upcomingDates = globalThis.__BAGEL_REMOTE__?.["upcoming"]?.upcomingDates ?? ["2026-10-01","2026-10-02"];

// Scheduled matches for a gender, soonest first (today before tomorrow).
export function getUpcoming(gender) {
  return gender ? upcoming.filter((r) => r.gender === gender) : upcoming;
}

export default upcoming;
