// GENERATED by scripts/fetch-upcoming-duals.mjs (§172b) -- DO NOT EDIT.
// Scheduled (status UPCOMING) duals from the ITA dual system involving our
// programs, matched by ITA org id. Opponents outside the app keep their
// ITA display name and a null teamId. Regenerated by the weekly task.
export const upcomingDualsFetchedAt = globalThis.__BAGEL_REMOTE__?.["upcomingDuals"]?.upcomingDualsFetchedAt ?? "2026-08-24";
export const upcomingDuals = globalThis.__BAGEL_REMOTE__?.["upcomingDuals"]?.upcomingDuals ?? [
 {
  "id": "DCAAD99B-2EFD-4C23-820A-B021D94C3FBC",
  "date": "2027-01-15",
  "dateTime": "2027-01-15T16:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "tulsa-m",
   "name": "University of Tulsa",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "Bryant University",
   "side": 2
  }
 },
 {
  "id": "D5E33680-5C45-49B4-A8F0-4925C905BE4B",
  "date": "2027-01-15",
  "dateTime": "2027-01-15T23:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "tulsa-m",
   "name": "University of Tulsa",
   "side": 1
  },
  "t2": {
   "teamId": "smu-m",
   "name": "Southern Methodist Univ.",
   "side": 2
  }
 },
 {
  "id": "DF8AA976-456E-4DC6-A85B-99E220973915",
  "date": "2027-01-16",
  "dateTime": "2027-01-16T00:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "gonz-w",
   "name": "Gonzaga University",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "University Of Montana",
   "side": 2
  }
 },
 {
  "id": "B3701AF3-5E74-4FDB-94AC-7CEE8E8BF2EA",
  "date": "2027-01-16",
  "dateTime": "2027-01-16T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Texas State U-San Marcos",
   "side": 1
  },
  "t2": {
   "teamId": "wich-w",
   "name": "Wichita State University",
   "side": 2
  }
 },
 {
  "id": "8EB5E5FE-EDF0-4E08-BC43-E0D624B8AF17",
  "date": "2027-01-16",
  "dateTime": "2027-01-16T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Texas State U-San Marcos",
   "side": 1
  },
  "t2": {
   "teamId": "ou-w",
   "name": "University Of Oklahoma",
   "side": 2
  }
 },
 {
  "id": "0189E7DD-BD44-4CBC-9661-8F27DDFFC601",
  "date": "2027-01-16",
  "dateTime": "2027-01-16T06:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Univ. Of Nebraska, Omaha",
   "side": 1
  },
  "t2": {
   "teamId": "ou-m",
   "name": "University Of Oklahoma",
   "side": 2
  }
 },
 {
  "id": "2FA8D514-FCD3-4699-8E49-E17C58F97368",
  "date": "2027-01-16",
  "dateTime": "2027-01-16T17:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "dart-w",
   "name": "Dartmouth College",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "U.S. Military Academy",
   "side": 2
  }
 },
 {
  "id": "57CB38EC-7512-4EB8-89A7-7CD5AAD65D8E",
  "date": "2027-01-16",
  "dateTime": "2027-01-16T18:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Jackson State University",
   "side": 1
  },
  "t2": {
   "teamId": "hou-w",
   "name": "University Of Houston",
   "side": 2
  }
 },
 {
  "id": "DD99A9D2-0AE1-4C9C-95A3-1ED655D02FF6",
  "date": "2027-01-17",
  "dateTime": "2027-01-17T06:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "tamu-w",
   "name": "Texas A&M University",
   "side": 1
  },
  "t2": {
   "teamId": "tcu-w",
   "name": "Texas Christian University",
   "side": 2
  }
 },
 {
  "id": "25E7B743-ECD7-4344-99C7-C85C7E314C6E",
  "date": "2027-01-17",
  "dateTime": "2027-01-17T19:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "gonz-w",
   "name": "Gonzaga University",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "Seattle University",
   "side": 2
  }
 },
 {
  "id": "F9EF6BB4-86A3-400F-A5C5-4E9BC2A03235",
  "date": "2027-01-18",
  "dateTime": "2027-01-18T19:30:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Univ. Of Nebraska, Omaha",
   "side": 1
  },
  "t2": {
   "teamId": "iowa-w",
   "name": "University Of Iowa",
   "side": 2
  }
 },
 {
  "id": "3F31021D-326A-479B-AA1F-617C9DDE58C4",
  "date": "2027-01-18",
  "dateTime": "2027-01-18T20:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Northern Illinois Univ.",
   "side": 1
  },
  "t2": {
   "teamId": "wisc-w",
   "name": "Univ. Of Wisconsin, Madison",
   "side": 2
  }
 },
 {
  "id": "5EBC9876-3273-41D1-ACBB-0FF150C4C725",
  "date": "2027-01-19",
  "dateTime": "2027-01-19T00:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "tulsa-m",
   "name": "University of Tulsa",
   "side": 1
  },
  "t2": {
   "teamId": "prin-m",
   "name": "Princeton University",
   "side": 2
  }
 },
 {
  "id": "54CB8106-BB5B-4EA9-AEE1-F3B5A7E7DEE9",
  "date": "2027-01-22",
  "dateTime": "2027-01-22T06:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Univ. Of Nebraska, Omaha",
   "side": 1
  },
  "t2": {
   "teamId": "neb-m",
   "name": "University Of Nebraska",
   "side": 2
  }
 },
 {
  "id": "367E0C4E-B68F-4855-AB6D-758A3893C199",
  "date": "2027-01-23",
  "dateTime": "2027-01-23T00:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "gonz-w",
   "name": "Gonzaga University",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "Kennesaw State University",
   "side": 2
  }
 },
 {
  "id": "970A32D4-9A00-4200-97C0-06ADE446A111",
  "date": "2027-01-23",
  "dateTime": "2027-01-23T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "vt-w",
   "name": "Virginia Tech",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "Liberty University",
   "side": 2
  }
 },
 {
  "id": "192845A2-3D68-4994-896C-97B178EC9EC5",
  "date": "2027-01-23",
  "dateTime": "2027-01-23T06:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "tamu-w",
   "name": "Texas A&M University",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "Elon University",
   "side": 2
  }
 },
 {
  "id": "E256C98F-2D15-4BD9-9990-CD180A62B846",
  "date": "2027-01-23",
  "dateTime": "2027-01-23T16:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "dart-w",
   "name": "Dartmouth College",
   "side": 1
  },
  "t2": {
   "teamId": "duke-w",
   "name": "Duke University",
   "side": 2
  }
 },
 {
  "id": "ADC7AF04-701F-4806-A994-0622E10CA2EB",
  "date": "2027-01-23",
  "dateTime": "2027-01-23T17:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "U.S. Air Force Academy",
   "side": 1
  },
  "t2": {
   "teamId": "gonz-m",
   "name": "Gonzaga University",
   "side": 2
  }
 },
 {
  "id": "4257C28E-0C50-4C84-94C9-CE8618E8F96B",
  "date": "2027-01-23",
  "dateTime": "2027-01-23T20:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "tulsa-m",
   "name": "University of Tulsa",
   "side": 1
  },
  "t2": {
   "teamId": "ind-m",
   "name": "Indiana University",
   "side": 2
  }
 },
 {
  "id": "ADE73CD7-BDD4-461E-B3B7-8B84A45C06A4",
  "date": "2027-01-24",
  "dateTime": "2027-01-24T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "vt-w",
   "name": "Virginia Tech",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "East Tennessee State Univ.",
   "side": 2
  }
 },
 {
  "id": "DD8690C3-078C-477D-939F-7B9FED25C5DA",
  "date": "2027-01-24",
  "dateTime": "2027-01-24T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Texas State U-San Marcos",
   "side": 1
  },
  "t2": {
   "teamId": "unt-w",
   "name": "Univ. Of North Texas",
   "side": 2
  }
 },
 {
  "id": "413BD81A-4472-4383-85E1-AC79BBEE4A16",
  "date": "2027-01-24",
  "dateTime": "2027-01-24T16:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Stonehill College",
   "side": 1
  },
  "t2": {
   "teamId": "port-w",
   "name": "University Of Portland",
   "side": 2
  }
 },
 {
  "id": "63E53045-D41B-43C9-98D8-40D7B2331E99",
  "date": "2027-01-28",
  "dateTime": "2027-01-28T00:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "tulsa-m",
   "name": "University of Tulsa",
   "side": 1
  },
  "t2": {
   "teamId": "ou-m",
   "name": "University Of Oklahoma",
   "side": 2
  }
 },
 {
  "id": "B5BCB8C6-AAAD-45ED-BD92-ADD888910415",
  "date": "2027-01-29",
  "dateTime": "2027-01-29T06:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Univ. Of Nebraska, Omaha",
   "side": 1
  },
  "t2": {
   "teamId": "wich-m",
   "name": "Wichita State University",
   "side": 2
  }
 },
 {
  "id": "BA19EDDF-7A36-463F-87EE-1630974D0001",
  "date": "2027-01-29",
  "dateTime": "2027-01-29T06:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "tamu-w",
   "name": "Texas A&M University",
   "side": 1
  },
  "t2": {
   "teamId": "pepp-w",
   "name": "Pepperdine University",
   "side": 2
  }
 },
 {
  "id": "593E1D59-F892-465C-B9DB-66933DB3559C",
  "date": "2027-01-30",
  "dateTime": "2027-01-30T00:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "gonz-w",
   "name": "Gonzaga University",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "University Of St. Thomas",
   "side": 2
  }
 },
 {
  "id": "3CF30151-67B8-43D4-BEBB-D69EBD8BE940",
  "date": "2027-01-30",
  "dateTime": "2027-01-30T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Quinnipiac University",
   "side": 1
  },
  "t2": {
   "teamId": "yale-w",
   "name": "Yale University",
   "side": 2
  }
 },
 {
  "id": "78D0F455-B387-4D6F-95B3-3DE5BB54BBDC",
  "date": "2027-01-30",
  "dateTime": "2027-01-30T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "dart-w",
   "name": "Dartmouth College",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "Boston University",
   "side": 2
  }
 },
 {
  "id": "FA86785A-B96C-4B17-8099-5B91D9C0DA04",
  "date": "2027-01-30",
  "dateTime": "2027-01-30T05:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Tennessee Tech University",
   "side": 1
  },
  "t2": {
   "teamId": "tenn-m",
   "name": "Univ. Of Tennessee, Knoxville",
   "side": 2
  }
 },
 {
  "id": "EB8546EB-C5D0-44C0-A0DF-31473D04D6DB",
  "date": "2027-01-30",
  "dateTime": "2027-01-30T06:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Univ. Of Nebraska, Omaha",
   "side": 1
  },
  "t2": {
   "teamId": "miz-w",
   "name": "University Of Missouri",
   "side": 2
  }
 },
 {
  "id": "39D0E9BE-94EC-4680-934B-19C019EB7ED7",
  "date": "2027-01-30",
  "dateTime": "2027-01-30T22:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Northern Illinois Univ.",
   "side": 1
  },
  "t2": {
   "teamId": "nw-w",
   "name": "Northwestern University",
   "side": 2
  }
 },
 {
  "id": "D1DBC07E-E64A-4C22-BE30-AA9563BFCD3E",
  "date": "2027-01-31",
  "dateTime": "2027-01-31T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Quinnipiac University",
   "side": 1
  },
  "t2": {
   "teamId": "harv-w",
   "name": "Harvard University",
   "side": 2
  }
 },
 {
  "id": "0623C19C-248B-4070-97C6-F8726B5E1F24",
  "date": "2027-01-31",
  "dateTime": "2027-01-31T17:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "U.S. Air Force Academy",
   "side": 1
  },
  "t2": {
   "teamId": "ucsd-m",
   "name": "University Of California, San Diego",
   "side": 2
  }
 },
 {
  "id": "8BFB413A-1080-403A-8E7C-99B1BAE34565",
  "date": "2027-01-31",
  "dateTime": "2027-01-31T17:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "tulsa-m",
   "name": "University of Tulsa",
   "side": 1
  },
  "t2": {
   "teamId": "ark-m",
   "name": "Univ. Of Arkansas, Fayetteville",
   "side": 2
  }
 },
 {
  "id": "EA5271F8-2BA7-46D2-9836-E9AE925E8372",
  "date": "2027-01-31",
  "dateTime": "2027-01-31T18:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Univ. Of Nebraska, Omaha",
   "side": 1
  },
  "t2": {
   "teamId": "neb-w",
   "name": "University Of Nebraska",
   "side": 2
  }
 },
 {
  "id": "6D34DDDB-BE5C-4289-9084-DA9B5AAFDA50",
  "date": "2027-01-31",
  "dateTime": "2027-01-31T19:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "gonz-w",
   "name": "Gonzaga University",
   "side": 1
  },
  "t2": {
   "teamId": "utah-w",
   "name": "University Of Utah",
   "side": 2
  }
 },
 {
  "id": "A8A206BF-6C08-4880-A35C-58B3A564812F",
  "date": "2027-01-31",
  "dateTime": "2027-01-31T21:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "tulsa-m",
   "name": "University of Tulsa",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "Lamar University",
   "side": 2
  }
 },
 {
  "id": "789B5428-3D11-4CC8-AD46-A1860529F73B",
  "date": "2027-01-31",
  "dateTime": "2027-01-31T22:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Univ. Of Nebraska, Omaha",
   "side": 1
  },
  "t2": {
   "teamId": "neb-w",
   "name": "University Of Nebraska",
   "side": 2
  }
 },
 {
  "id": "286C846D-254F-4F32-A67F-C2576EB4873E",
  "date": "2027-02-04",
  "dateTime": "2027-02-04T17:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Georgia Southern University",
   "side": 1
  },
  "t2": {
   "teamId": "okst-w",
   "name": "Oklahoma State University",
   "side": 2
  }
 },
 {
  "id": "A3D7E0F0-A8EA-41A7-A66F-872A11287C94",
  "date": "2027-02-05",
  "dateTime": "2027-02-05T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "dart-w",
   "name": "Dartmouth College",
   "side": 1
  },
  "t2": {
   "teamId": "brown-w",
   "name": "Brown University",
   "side": 2
  }
 },
 {
  "id": "2BCAE6CC-855C-4E45-BC4A-15DC50749A99",
  "date": "2027-02-05",
  "dateTime": "2027-02-05T06:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Univ. Of Nebraska, Omaha",
   "side": 1
  },
  "t2": {
   "teamId": "okst-m",
   "name": "Oklahoma State University",
   "side": 2
  }
 },
 {
  "id": "CB13E6BE-A73C-4DDF-8017-97095219925C",
  "date": "2027-02-06",
  "dateTime": "2027-02-06T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "vt-w",
   "name": "Virginia Tech",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "Virginia Commonwealth Univ.",
   "side": 2
  }
 },
 {
  "id": "DCBE0F27-ED91-42C5-BE3A-467C26378555",
  "date": "2027-02-06",
  "dateTime": "2027-02-06T05:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Quinnipiac University",
   "side": 1
  },
  "t2": {
   "teamId": "brown-m",
   "name": "Brown University",
   "side": 2
  }
 },
 {
  "id": "3DFF111C-256D-4ECE-B3DE-833BDF8E5535",
  "date": "2027-02-06",
  "dateTime": "2027-02-06T17:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "tulsa-m",
   "name": "University of Tulsa",
   "side": 1
  },
  "t2": {
   "teamId": "penn-m",
   "name": "Univ. Of Pennsylvania",
   "side": 2
  }
 },
 {
  "id": "8980DF4A-AEAE-45CE-9868-CDE64EA4B913",
  "date": "2027-02-07",
  "dateTime": "2027-02-07T00:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "tulsa-m",
   "name": "University of Tulsa",
   "side": 1
  },
  "t2": {
   "teamId": "temple-m",
   "name": "Temple University",
   "side": 2
  }
 },
 {
  "id": "AC0FB74B-0F1C-47D5-9A94-8A3276EAECA4",
  "date": "2027-02-07",
  "dateTime": "2027-02-07T05:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Quinnipiac University",
   "side": 1
  },
  "t2": {
   "teamId": "harv-m",
   "name": "Harvard University",
   "side": 2
  }
 },
 {
  "id": "730EF0BC-FE75-4E11-8E8B-851B46FB0817",
  "date": "2027-02-07",
  "dateTime": "2027-02-07T06:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Northern Illinois Univ.",
   "side": 1
  },
  "t2": {
   "teamId": "minn-w",
   "name": "University Of Minnesota",
   "side": 2
  }
 },
 {
  "id": "94A3B97B-4995-4654-A0A1-88011F78007F",
  "date": "2027-02-07",
  "dateTime": "2027-02-07T16:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "College Of William & Mary",
   "side": 1
  },
  "t2": {
   "teamId": "wake-w",
   "name": "Wake Forest University",
   "side": 2
  }
 },
 {
  "id": "769F2CE2-8051-4AE2-B746-B224167AC7BC",
  "date": "2027-02-07",
  "dateTime": "2027-02-07T21:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Davidson College",
   "side": 1
  },
  "t2": {
   "teamId": "vt-m",
   "name": "Virginia Tech",
   "side": 2
  }
 },
 {
  "id": "28F004DE-03E5-4A8D-B0DA-5A52C07C7517",
  "date": "2027-02-12",
  "dateTime": "2027-02-12T16:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "tulsa-m",
   "name": "University of Tulsa",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "Creighton University",
   "side": 2
  }
 },
 {
  "id": "A37E75DA-1C80-4FCA-AABF-DA368E756529",
  "date": "2027-02-13",
  "dateTime": "2027-02-13T00:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "tulsa-m",
   "name": "University of Tulsa",
   "side": 1
  },
  "t2": {
   "teamId": "neb-m",
   "name": "University Of Nebraska",
   "side": 2
  }
 },
 {
  "id": "CE0102CE-79C0-4779-8AF4-C02939140960",
  "date": "2027-02-13",
  "dateTime": "2027-02-13T20:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "gonz-w",
   "name": "Gonzaga University",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "Middle Tennessee State University",
   "side": 2
  }
 },
 {
  "id": "7725758A-DAEF-49E9-8282-B6AF0EB3F7E9",
  "date": "2027-02-13",
  "dateTime": "2027-02-13T20:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Tennessee Tech University",
   "side": 1
  },
  "t2": {
   "teamId": "miss-m",
   "name": "University Of Mississippi",
   "side": 2
  }
 },
 {
  "id": "299B20A3-93B1-4F67-92A7-5C3945725666",
  "date": "2027-02-13",
  "dateTime": "2027-02-13T23:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Tennessee Tech University",
   "side": 1
  },
  "t2": {
   "teamId": "mem-m",
   "name": "University Of Memphis",
   "side": 2
  }
 },
 {
  "id": "BB0A1331-B747-41A5-BA85-2DBE7226C7B1",
  "date": "2027-02-14",
  "dateTime": "2027-02-14T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "vt-w",
   "name": "Virginia Tech",
   "side": 1
  },
  "t2": {
   "teamId": "ecu-w",
   "name": "East Carolina University",
   "side": 2
  }
 },
 {
  "id": "C18938B6-2D92-45A4-AC02-737F17311FB7",
  "date": "2027-02-14",
  "dateTime": "2027-02-14T06:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "University Of St. Thomas",
   "side": 1
  },
  "t2": {
   "teamId": "minn-w",
   "name": "University Of Minnesota",
   "side": 2
  }
 },
 {
  "id": "691B5BF6-C50F-4B9C-B683-0708BECFF1EE",
  "date": "2027-02-14",
  "dateTime": "2027-02-14T16:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "gonz-w",
   "name": "Gonzaga University",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "Lipscomb University",
   "side": 2
  }
 },
 {
  "id": "AB6068B9-B963-44A3-9364-9A156AC6D81D",
  "date": "2027-02-17",
  "dateTime": "2027-02-17T20:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "vt-w",
   "name": "Virginia Tech",
   "side": 1
  },
  "t2": {
   "teamId": "uva-w",
   "name": "University Of Virginia",
   "side": 2
  }
 },
 {
  "id": "4EBE5F9E-9950-4586-94FE-FD5F0A08B2F0",
  "date": "2027-02-18",
  "dateTime": "2027-02-18T00:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "tulsa-m",
   "name": "University of Tulsa",
   "side": 1
  },
  "t2": {
   "teamId": "okst-m",
   "name": "Oklahoma State University",
   "side": 2
  }
 },
 {
  "id": "294F8826-63EA-425E-B51C-5591FADC2D14",
  "date": "2027-02-19",
  "dateTime": "2027-02-19T21:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "University Of St. Thomas",
   "side": 1
  },
  "t2": {
   "teamId": "isu-w",
   "name": "Iowa State University",
   "side": 2
  }
 },
 {
  "id": "9D080B44-59D8-46F9-8EA8-2260F6C5EF8F",
  "date": "2027-02-19",
  "dateTime": "2027-02-19T22:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "dart-w",
   "name": "Dartmouth College",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "Univ. Of Massachusetts, Amherst",
   "side": 2
  }
 },
 {
  "id": "E897C84C-4CE8-4619-A7CA-97D4E0CF58CD",
  "date": "2027-02-20",
  "dateTime": "2027-02-20T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "vt-w",
   "name": "Virginia Tech",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "Morgan State University",
   "side": 2
  }
 },
 {
  "id": "7BF80C4B-5AE9-43B9-8C71-2FF409919EAB",
  "date": "2027-02-20",
  "dateTime": "2027-02-20T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Georgia Southern University",
   "side": 1
  },
  "t2": {
   "teamId": "sc-w",
   "name": "University Of South Carolina",
   "side": 2
  }
 },
 {
  "id": "BF0711AB-0519-4AD0-B9F8-2634D5FCDA8C",
  "date": "2027-02-20",
  "dateTime": "2027-02-20T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Georgia Southern University",
   "side": 1
  },
  "t2": {
   "teamId": "clt-w",
   "name": "UNC Charlotte",
   "side": 2
  }
 },
 {
  "id": "C19E5138-C5D9-431E-849D-D8C02645DBAC",
  "date": "2027-02-20",
  "dateTime": "2027-02-20T06:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "tamu-w",
   "name": "Texas A&M University",
   "side": 1
  },
  "t2": {
   "teamId": "usd-w",
   "name": "University Of San Diego",
   "side": 2
  }
 },
 {
  "id": "43047ABD-5676-43AF-9239-DCEE396E2D25",
  "date": "2027-02-20",
  "dateTime": "2027-02-20T07:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "gonz-w",
   "name": "Gonzaga University",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "Univ. Of South Dakota",
   "side": 2
  }
 },
 {
  "id": "A07F6163-A537-4389-93D9-797872657769",
  "date": "2027-02-21",
  "dateTime": "2027-02-21T07:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "gonz-w",
   "name": "Gonzaga University",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "U.S. Air Force Academy",
   "side": 2
  }
 },
 {
  "id": "3C3E344F-91BB-449E-B069-38CA7C544DF6",
  "date": "2027-02-21",
  "dateTime": "2027-02-21T15:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "vt-w",
   "name": "Virginia Tech",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "Furman University",
   "side": 2
  }
 },
 {
  "id": "B6D7BD94-4633-4707-9D90-0266D194A621",
  "date": "2027-02-21",
  "dateTime": "2027-02-21T15:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "dart-w",
   "name": "Dartmouth College",
   "side": 1
  },
  "t2": {
   "teamId": "cincy-w",
   "name": "University Of Cincinnati",
   "side": 2
  }
 },
 {
  "id": "C55D942B-DC03-408D-B00A-7B6958B32FD7",
  "date": "2027-02-21",
  "dateTime": "2027-02-21T16:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "College Of William & Mary",
   "side": 1
  },
  "t2": {
   "teamId": "ecu-w",
   "name": "East Carolina University",
   "side": 2
  }
 },
 {
  "id": "C097E7FE-B99B-40DD-93B0-48B4E076CEEF",
  "date": "2027-02-22",
  "dateTime": "2027-02-22T22:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "tulsa-m",
   "name": "University of Tulsa",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "San Diego State University",
   "side": 2
  }
 },
 {
  "id": "C5C6D261-C7D5-47A8-BB66-42B8DF3DC031",
  "date": "2027-02-23",
  "dateTime": "2027-02-23T20:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "tulsa-m",
   "name": "University of Tulsa",
   "side": 1
  },
  "t2": {
   "teamId": "usd-m",
   "name": "University Of San Diego",
   "side": 2
  }
 },
 {
  "id": "82F70478-0056-4D30-A91E-E4A7A001EB75",
  "date": "2027-02-25",
  "dateTime": "2027-02-25T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Texas State U-San Marcos",
   "side": 1
  },
  "t2": {
   "teamId": "usf-w",
   "name": "Univ. Of South Florida",
   "side": 2
  }
 },
 {
  "id": "CA1FCAA9-886B-44E8-BE45-7AC6102BE93C",
  "date": "2027-02-26",
  "dateTime": "2027-02-26T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "vt-w",
   "name": "Virginia Tech",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "Tarleton State Univ.",
   "side": 2
  }
 },
 {
  "id": "E7C7D13A-8A2C-479D-A64D-EF76217D046E",
  "date": "2027-02-26",
  "dateTime": "2027-02-26T19:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Stonehill College",
   "side": 1
  },
  "t2": {
   "teamId": "bc-w",
   "name": "Boston College",
   "side": 2
  }
 },
 {
  "id": "2847798C-E6D2-4040-8293-4AB60926981C",
  "date": "2027-02-27",
  "dateTime": "2027-02-27T16:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "dart-w",
   "name": "Dartmouth College",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "U.S. Naval Academy",
   "side": 2
  }
 },
 {
  "id": "34E59C60-23AC-4665-B9A8-1EDA719FA22D",
  "date": "2027-02-28",
  "dateTime": "2027-02-28T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "vt-w",
   "name": "Virginia Tech",
   "side": 1
  },
  "t2": {
   "teamId": "smu-w",
   "name": "Southern Methodist Univ.",
   "side": 2
  }
 },
 {
  "id": "C9F2A14E-E8B0-4CE5-B659-F5CA2486DC8D",
  "date": "2027-02-28",
  "dateTime": "2027-02-28T06:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "tamu-w",
   "name": "Texas A&M University",
   "side": 1
  },
  "t2": {
   "teamId": "tex-w",
   "name": "Univ. Of Texas, Austin",
   "side": 2
  }
 },
 {
  "id": "FACC3664-F1CF-4628-BF25-930D5D28E919",
  "date": "2027-02-28",
  "dateTime": "2027-02-28T19:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "gonz-w",
   "name": "Gonzaga University",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "Idaho State University",
   "side": 2
  }
 },
 {
  "id": "F04FC8BF-8F31-41A8-AE47-69A8E86DEB69",
  "date": "2027-03-05",
  "dateTime": "2027-03-05T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "vt-w",
   "name": "Virginia Tech",
   "side": 1
  },
  "t2": {
   "teamId": "clem-w",
   "name": "Clemson University",
   "side": 2
  }
 },
 {
  "id": "0A3468FD-3889-4A70-A9EE-4BB7AFCCFCF7",
  "date": "2027-03-05",
  "dateTime": "2027-03-05T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Texas State U-San Marcos",
   "side": 1
  },
  "t2": {
   "teamId": "utsa-w",
   "name": "Univ. Of Texas, San Antonio",
   "side": 2
  }
 },
 {
  "id": "349C5199-9EB0-477E-BE47-F31D09E99BBC",
  "date": "2027-03-05",
  "dateTime": "2027-03-05T06:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "tamu-w",
   "name": "Texas A&M University",
   "side": 1
  },
  "t2": {
   "teamId": "lsu-w",
   "name": "Louisiana State University",
   "side": 2
  }
 },
 {
  "id": "5CA0BF60-652A-47EA-B239-ADEE07503863",
  "date": "2027-03-06",
  "dateTime": "2027-03-06T00:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "tulsa-m",
   "name": "University of Tulsa",
   "side": 1
  },
  "t2": {
   "teamId": "ttu-m",
   "name": "Texas Tech University",
   "side": 2
  }
 },
 {
  "id": "A3A95250-9072-4864-8720-DAB31BDE4E50",
  "date": "2027-03-07",
  "dateTime": "2027-03-07T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "vt-w",
   "name": "Virginia Tech",
   "side": 1
  },
  "t2": {
   "teamId": "gt-w",
   "name": "Georgia Tech",
   "side": 2
  }
 },
 {
  "id": "C7F3F85B-8EB4-459D-AA6E-B4009B9B1FEF",
  "date": "2027-03-07",
  "dateTime": "2027-03-07T06:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "tamu-w",
   "name": "Texas A&M University",
   "side": 1
  },
  "t2": {
   "teamId": "miss-w",
   "name": "University Of Mississippi",
   "side": 2
  }
 },
 {
  "id": "D447813E-E28F-47BA-ADFE-3B86AAB15186",
  "date": "2027-03-07",
  "dateTime": "2027-03-07T18:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "tulsa-m",
   "name": "University of Tulsa",
   "side": 1
  },
  "t2": {
   "teamId": "bay-m",
   "name": "Baylor University",
   "side": 2
  }
 },
 {
  "id": "86E7AD03-8136-4351-891E-9E0D40A8EAF6",
  "date": "2027-03-07",
  "dateTime": "2027-03-07T23:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "tulsa-m",
   "name": "University of Tulsa",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "Oral Roberts University",
   "side": 2
  }
 },
 {
  "id": "5AD329E0-0A2B-4024-BEF6-1A42CB362C51",
  "date": "2027-03-08",
  "dateTime": "2027-03-08T14:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Georgia Southern University",
   "side": 1
  },
  "t2": {
   "teamId": "penn-w",
   "name": "Univ. Of Pennsylvania",
   "side": 2
  }
 },
 {
  "id": "B3BC3CE7-FBE6-41B2-AEDC-74AD37BFD10C",
  "date": "2027-03-09",
  "dateTime": "2027-03-09T17:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "gonz-w",
   "name": "Gonzaga University",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "Univ. Of Texas, Arlington",
   "side": 2
  }
 },
 {
  "id": "900E0E81-C2CA-4E4B-B204-4981F0118E45",
  "date": "2027-03-12",
  "dateTime": "2027-03-12T06:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "tamu-w",
   "name": "Texas A&M University",
   "side": 1
  },
  "t2": {
   "teamId": "ala-w",
   "name": "University Of Alabama",
   "side": 2
  }
 },
 {
  "id": "81EFE22E-D94C-49FC-9454-03F12AE462BD",
  "date": "2027-03-12",
  "dateTime": "2027-03-12T16:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "gonz-w",
   "name": "Gonzaga University",
   "side": 1
  },
  "t2": {
   "teamId": "unt-w",
   "name": "Univ. Of North Texas",
   "side": 2
  }
 },
 {
  "id": "C7273D39-1CEB-481A-B1CE-D88DA69120E2",
  "date": "2027-03-14",
  "dateTime": "2027-03-14T06:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "tamu-w",
   "name": "Texas A&M University",
   "side": 1
  },
  "t2": {
   "teamId": "msst-w",
   "name": "Mississippi State Univ.",
   "side": 2
  }
 },
 {
  "id": "F5C3D695-9EAC-4770-8AA0-0AA0CC73C96C",
  "date": "2027-03-14",
  "dateTime": "2027-03-14T08:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Tennessee Tech University",
   "side": 1
  },
  "t2": {
   "teamId": "lmu-m",
   "name": "Loyola Marymount University",
   "side": 2
  }
 },
 {
  "id": "D332D66F-BB52-4655-8687-B079D631371B",
  "date": "2027-03-14",
  "dateTime": "2027-03-14T16:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "tulsa-m",
   "name": "University of Tulsa",
   "side": 1
  },
  "t2": {
   "teamId": "ucf-m",
   "name": "University Of Central Florida",
   "side": 2
  }
 },
 {
  "id": "11BEE94F-0A9A-48AF-94E0-30183AAC85AD",
  "date": "2027-03-14",
  "dateTime": "2027-03-14T17:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "gonz-w",
   "name": "Gonzaga University",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "Eastern Washington Univ.",
   "side": 2
  }
 },
 {
  "id": "259AC8EC-8177-49E7-9003-61A2038EF58F",
  "date": "2027-03-17",
  "dateTime": "2027-03-17T18:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "tulsa-m",
   "name": "University of Tulsa",
   "side": 1
  },
  "t2": {
   "teamId": "usf-m",
   "name": "Univ. Of South Florida",
   "side": 2
  }
 },
 {
  "id": "04AB77E0-8F0C-40A6-8896-7C9914C3A5D3",
  "date": "2027-03-19",
  "dateTime": "2027-03-19T04:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "vt-w",
   "name": "Virginia Tech",
   "side": 1
  },
  "t2": {
   "teamId": "miami-w",
   "name": "University Of Miami",
   "side": 2
  }
 },
 {
  "id": "793BC4CA-7B5A-43FC-A1F7-C4B20CB6F675",
  "date": "2027-03-19",
  "dateTime": "2027-03-19T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "tamu-w",
   "name": "Texas A&M University",
   "side": 1
  },
  "t2": {
   "teamId": "uga-w",
   "name": "University Of Georgia",
   "side": 2
  }
 },
 {
  "id": "24ED696F-522F-4471-AA08-4FD8D606AC7B",
  "date": "2027-03-20",
  "dateTime": "2027-03-20T16:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "gonz-w",
   "name": "Gonzaga University",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "Univ. Of Texas, Rio Grande Valley",
   "side": 2
  }
 },
 {
  "id": "39C83B61-F0C8-40F1-BA93-508B839C20B9",
  "date": "2027-03-20",
  "dateTime": "2027-03-20T19:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "dart-w",
   "name": "Dartmouth College",
   "side": 1
  },
  "t2": {
   "teamId": "csuf-w",
   "name": "California State University, Fullerton",
   "side": 2
  }
 },
 {
  "id": "C191BFC2-7A16-472F-9759-05E53217D8B7",
  "date": "2027-03-21",
  "dateTime": "2027-03-21T04:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "vt-w",
   "name": "Virginia Tech",
   "side": 1
  },
  "t2": {
   "teamId": "fsu-w",
   "name": "Florida State University",
   "side": 2
  }
 },
 {
  "id": "E6597778-ECD8-4867-BD7C-3653955D4C74",
  "date": "2027-03-21",
  "dateTime": "2027-03-21T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "tamu-w",
   "name": "Texas A&M University",
   "side": 1
  },
  "t2": {
   "teamId": "sc-w",
   "name": "University Of South Carolina",
   "side": 2
  }
 },
 {
  "id": "DC886988-5357-4060-8723-80C2940D3A4B",
  "date": "2027-03-21",
  "dateTime": "2027-03-21T16:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "gonz-w",
   "name": "Gonzaga University",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "Texas State U-San Marcos",
   "side": 2
  }
 },
 {
  "id": "C511EAF7-0AC2-4C2C-9886-579E77A21A06",
  "date": "2027-03-21",
  "dateTime": "2027-03-21T17:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "tulsa-m",
   "name": "University of Tulsa",
   "side": 1
  },
  "t2": {
   "teamId": "mem-m",
   "name": "University Of Memphis",
   "side": 2
  }
 },
 {
  "id": "FE017F83-4265-4779-88DB-238E2942DD61",
  "date": "2027-03-21",
  "dateTime": "2027-03-21T18:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "dart-w",
   "name": "Dartmouth College",
   "side": 1
  },
  "t2": {
   "teamId": "ucsd-w",
   "name": "University Of California, San Diego",
   "side": 2
  }
 },
 {
  "id": "4C029253-DD94-4E36-87C3-ABC50B7F6ADA",
  "date": "2027-03-24",
  "dateTime": "2027-03-24T18:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "dart-w",
   "name": "Dartmouth College",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "San Diego State University",
   "side": 2
  }
 },
 {
  "id": "FE697DD9-F883-4118-A1EF-34476F6D69C9",
  "date": "2027-03-25",
  "dateTime": "2027-03-25T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "tamu-w",
   "name": "Texas A&M University",
   "side": 1
  },
  "t2": {
   "teamId": "miz-w",
   "name": "University Of Missouri",
   "side": 2
  }
 },
 {
  "id": "00915560-87F1-4C38-87C4-3E217BF7A6FC",
  "date": "2027-03-26",
  "dateTime": "2027-03-26T04:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "vt-w",
   "name": "Virginia Tech",
   "side": 1
  },
  "t2": {
   "teamId": "unc-w",
   "name": "UNC Chapel Hill",
   "side": 2
  }
 },
 {
  "id": "D25A404E-4C8A-4BDA-854D-AE980EA6993A",
  "date": "2027-03-26",
  "dateTime": "2027-03-26T04:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "gonz-w",
   "name": "Gonzaga University",
   "side": 1
  },
  "t2": {
   "teamId": "wsu-w",
   "name": "Washington State Univ.",
   "side": 2
  }
 },
 {
  "id": "56FD12AE-839F-4563-AF60-131EE606E51A",
  "date": "2027-03-26",
  "dateTime": "2027-03-26T17:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "College Of William & Mary",
   "side": 1
  },
  "t2": {
   "teamId": "clt-w",
   "name": "UNC Charlotte",
   "side": 2
  }
 },
 {
  "id": "113BE1A1-FA20-4B2D-8A12-5256F1FF2382",
  "date": "2027-03-26",
  "dateTime": "2027-03-26T23:30:00.000Z",
  "gender": "men",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "tulsa-m",
   "name": "University of Tulsa",
   "side": 1
  },
  "t2": {
   "teamId": "tuln-m",
   "name": "Tulane University",
   "side": 2
  }
 },
 {
  "id": "2AA565C5-D14B-4153-A968-FBDEF7F22F6E",
  "date": "2027-03-27",
  "dateTime": "2027-03-27T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "tamu-w",
   "name": "Texas A&M University",
   "side": 1
  },
  "t2": {
   "teamId": "van-w",
   "name": "Vanderbilt University",
   "side": 2
  }
 },
 {
  "id": "731E5D7A-8B07-4A9F-B151-C9DE97D9A86D",
  "date": "2027-03-28",
  "dateTime": "2027-03-28T04:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "vt-w",
   "name": "Virginia Tech",
   "side": 1
  },
  "t2": {
   "teamId": "duke-w",
   "name": "Duke University",
   "side": 2
  }
 },
 {
  "id": "CE97663A-93CE-4A78-8DE6-27E73E0140E7",
  "date": "2027-04-01",
  "dateTime": "2027-04-01T05:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "tulsa-m",
   "name": "University of Tulsa",
   "side": 1
  },
  "t2": {
   "teamId": "wich-m",
   "name": "Wichita State University",
   "side": 2
  }
 },
 {
  "id": "A8036EB3-CF46-438F-937D-4BE1434DDF3B",
  "date": "2027-04-02",
  "dateTime": "2027-04-02T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "tamu-w",
   "name": "Texas A&M University",
   "side": 1
  },
  "t2": {
   "teamId": "uk-w",
   "name": "University Of Kentucky",
   "side": 2
  }
 },
 {
  "id": "E1EF5692-2038-46D7-A996-C4CA15D97DED",
  "date": "2027-04-02",
  "dateTime": "2027-04-02T07:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "gonz-w",
   "name": "Gonzaga University",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "San Diego State University",
   "side": 2
  }
 },
 {
  "id": "3549939B-DDD0-4E4B-99E3-228C70DB3483",
  "date": "2027-04-03",
  "dateTime": "2027-04-03T04:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "vt-w",
   "name": "Virginia Tech",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "Appalachian State University",
   "side": 2
  }
 },
 {
  "id": "4F15E369-8D58-4501-BC1F-51D5742679C8",
  "date": "2027-04-03",
  "dateTime": "2027-04-03T18:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "dart-w",
   "name": "Dartmouth College",
   "side": 1
  },
  "t2": {
   "teamId": "harv-w",
   "name": "Harvard University",
   "side": 2
  }
 },
 {
  "id": "CF2138B8-B86A-4231-AB2D-50F044E425F7",
  "date": "2027-04-04",
  "dateTime": "2027-04-04T04:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "vt-w",
   "name": "Virginia Tech",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "UNC Greensboro",
   "side": 2
  }
 },
 {
  "id": "AEAC2226-171E-4DF2-B25A-E955BC2A09E1",
  "date": "2027-04-04",
  "dateTime": "2027-04-04T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": false,
  "t1": {
   "teamId": null,
   "name": "Univ. Of Nebraska, Omaha",
   "side": 1
  },
  "t2": {
   "teamId": "tulsa-w",
   "name": "University Of Tulsa",
   "side": 2
  }
 },
 {
  "id": "D2E40AAF-C268-4127-BDAB-551F447A327E",
  "date": "2027-04-04",
  "dateTime": "2027-04-04T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "tamu-w",
   "name": "Texas A&M University",
   "side": 1
  },
  "t2": {
   "teamId": "tenn-w",
   "name": "Univ. Of Tennessee, Knoxville",
   "side": 2
  }
 },
 {
  "id": "149902F9-8AA9-4F93-8FA9-31ADCA74F638",
  "date": "2027-04-04",
  "dateTime": "2027-04-04T07:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "gonz-w",
   "name": "Gonzaga University",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "California State University, Fresno",
   "side": 2
  }
 },
 {
  "id": "82DD1E05-84F1-4107-806F-E6FE726B106B",
  "date": "2027-04-09",
  "dateTime": "2027-04-09T04:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "vt-w",
   "name": "Virginia Tech",
   "side": 1
  },
  "t2": {
   "teamId": "cuse-w",
   "name": "Syracuse University",
   "side": 2
  }
 },
 {
  "id": "9CA15409-2EE8-48A1-A3BB-CBBFD899F780",
  "date": "2027-04-09",
  "dateTime": "2027-04-09T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "tamu-w",
   "name": "Texas A&M University",
   "side": 1
  },
  "t2": {
   "teamId": "aub-w",
   "name": "Auburn University",
   "side": 2
  }
 },
 {
  "id": "D9ACB94A-397A-43D9-B706-43639B494F3C",
  "date": "2027-04-09",
  "dateTime": "2027-04-09T15:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "tulsa-m",
   "name": "University of Tulsa",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "New Mexico State University",
   "side": 2
  }
 },
 {
  "id": "A6CF5C37-37DD-44B6-BE5E-06417A712A1F",
  "date": "2027-04-09",
  "dateTime": "2027-04-09T23:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "tulsa-m",
   "name": "University of Tulsa",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "New Mexico State University",
   "side": 2
  }
 },
 {
  "id": "4E883118-493C-41DA-BF79-F13EB9B6BEFA",
  "date": "2027-04-10",
  "dateTime": "2027-04-10T04:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": null,
   "name": "Texas State U-San Marcos",
   "side": 1
  },
  "t2": {
   "teamId": "wsu-w",
   "name": "Washington State Univ.",
   "side": 2
  }
 },
 {
  "id": "01AA9127-FAA5-4E0F-9674-22383F657018",
  "date": "2027-04-10",
  "dateTime": "2027-04-10T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "gonz-w",
   "name": "Gonzaga University",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "Colorado State University",
   "side": 2
  }
 },
 {
  "id": "DA472FA1-A5BC-4DE4-B550-8C7E2EC0C373",
  "date": "2027-04-10",
  "dateTime": "2027-04-10T17:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "dart-w",
   "name": "Dartmouth College",
   "side": 1
  },
  "t2": {
   "teamId": "colum-w",
   "name": "Columbia University",
   "side": 2
  }
 },
 {
  "id": "81797334-F374-41B3-90AF-97DD69CD8EE9",
  "date": "2027-04-11",
  "dateTime": "2027-04-11T04:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "vt-w",
   "name": "Virginia Tech",
   "side": 1
  },
  "t2": {
   "teamId": "bc-w",
   "name": "Boston College",
   "side": 2
  }
 },
 {
  "id": "0E15365A-13FA-4C1B-93B3-0CB6BA77FAC6",
  "date": "2027-04-11",
  "dateTime": "2027-04-11T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "tamu-w",
   "name": "Texas A&M University",
   "side": 1
  },
  "t2": {
   "teamId": "fla-w",
   "name": "University Of Florida",
   "side": 2
  }
 },
 {
  "id": "C6E821BE-4E2B-4BB6-8220-341AAE3F23F9",
  "date": "2027-04-11",
  "dateTime": "2027-04-11T15:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": false,
  "t1": {
   "teamId": "tulsa-m",
   "name": "University of Tulsa",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "DePaul University",
   "side": 2
  }
 },
 {
  "id": "10ECB2DD-24C1-431D-A96F-4FD50A7C533F",
  "date": "2027-04-11",
  "dateTime": "2027-04-11T17:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "dart-w",
   "name": "Dartmouth College",
   "side": 1
  },
  "t2": {
   "teamId": "corn-w",
   "name": "Cornell University",
   "side": 2
  }
 },
 {
  "id": "52F32A5C-CBF4-4B45-8633-17A28419F0A3",
  "date": "2027-04-16",
  "dateTime": "2027-04-16T04:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "vt-w",
   "name": "Virginia Tech",
   "side": 1
  },
  "t2": {
   "teamId": "nd-w",
   "name": "University of Notre Dame",
   "side": 2
  }
 },
 {
  "id": "66FE7A1B-A394-4ABA-B390-F19C2F2EC2CB",
  "date": "2027-04-16",
  "dateTime": "2027-04-16T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "tamu-w",
   "name": "Texas A&M University",
   "side": 1
  },
  "t2": {
   "teamId": "ou-w",
   "name": "University Of Oklahoma",
   "side": 2
  }
 },
 {
  "id": "8E0EB3CD-A50B-4A18-809B-E557E36ED6FA",
  "date": "2027-04-16",
  "dateTime": "2027-04-16T06:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "gonz-w",
   "name": "Gonzaga University",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "Boise State University",
   "side": 2
  }
 },
 {
  "id": "ABF09F2B-A88D-4973-9C85-E197BA869AAA",
  "date": "2027-04-16",
  "dateTime": "2027-04-16T23:00:00.000Z",
  "gender": "men",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "tulsa-m",
   "name": "University of Tulsa",
   "side": 1
  },
  "t2": {
   "teamId": "rice-m",
   "name": "Rice University",
   "side": 2
  }
 },
 {
  "id": "DF70A152-E755-4903-A2A9-4CCBE2F12F9F",
  "date": "2027-04-17",
  "dateTime": "2027-04-17T17:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "dart-w",
   "name": "Dartmouth College",
   "side": 1
  },
  "t2": {
   "teamId": "prin-w",
   "name": "Princeton University",
   "side": 2
  }
 },
 {
  "id": "549D4D24-83A1-4D9B-937E-D01412217B85",
  "date": "2027-04-18",
  "dateTime": "2027-04-18T04:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "vt-w",
   "name": "Virginia Tech",
   "side": 1
  },
  "t2": {
   "teamId": "lou-w",
   "name": "University Of Louisville",
   "side": 2
  }
 },
 {
  "id": "44BD1406-D4EE-495A-AE24-FE964F08B033",
  "date": "2027-04-18",
  "dateTime": "2027-04-18T05:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "tamu-w",
   "name": "Texas A&M University",
   "side": 1
  },
  "t2": {
   "teamId": "ark-w",
   "name": "Univ. Of Arkansas, Fayetteville",
   "side": 2
  }
 },
 {
  "id": "CB919B43-F141-4D41-9ABE-8C3FE0F90D88",
  "date": "2027-04-18",
  "dateTime": "2027-04-18T06:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "gonz-w",
   "name": "Gonzaga University",
   "side": 1
  },
  "t2": {
   "teamId": null,
   "name": "Utah State University",
   "side": 2
  }
 },
 {
  "id": "89EDDB24-A118-4601-A526-0EE05648B80F",
  "date": "2027-04-18",
  "dateTime": "2027-04-18T17:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "dart-w",
   "name": "Dartmouth College",
   "side": 1
  },
  "t2": {
   "teamId": "penn-w",
   "name": "Univ. Of Pennsylvania",
   "side": 2
  }
 },
 {
  "id": "75A6545B-67DA-4374-8050-5141708317AE",
  "date": "2027-04-23",
  "dateTime": "2027-04-23T18:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "dart-w",
   "name": "Dartmouth College",
   "side": 1
  },
  "t2": {
   "teamId": "brown-w",
   "name": "Brown University",
   "side": 2
  }
 },
 {
  "id": "1B058EE3-4B25-4541-9FE2-17A4A9E594E9",
  "date": "2027-04-25",
  "dateTime": "2027-04-25T17:00:00.000Z",
  "gender": "women",
  "isConferenceMatch": true,
  "t1": {
   "teamId": "dart-w",
   "name": "Dartmouth College",
   "side": 1
  },
  "t2": {
   "teamId": "yale-w",
   "name": "Yale University",
   "side": 2
  }
 }
];

// All scheduled duals for a gender, ascending; conference is applied by
// the caller (a dual belongs to a conference view when one of OUR sides
// plays in it).
export function getUpcomingDualsByGender(gender) {
  return upcomingDuals.filter((r) => r.gender === gender);
}

// The next scheduled dual for one team, from (and including) onDate.
export function nextUpcomingDual(teamId, onDate) {
  const from = onDate ?? upcomingDualsFetchedAt;
  return (
    upcomingDuals.find(
      (r) => r.date >= from && (r.t1?.teamId === teamId || r.t2?.teamId === teamId)
    ) ?? null
  );
}
